//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLCache.h"

@class NSMutableDictionary, NSString;

@interface AdCompURLCache : NSURLCache
{
    NSMutableDictionary *dicItems;
    NSMutableDictionary *dicMemStore;
    unsigned long long diskUseSize;
    unsigned long long diskMyCapacity;
    NSString *diskPath;
    int maxItem;
    _Bool modified;
}

+ (id)getFullUrlByRequest:(id)arg1;
- (void).cxx_destruct;
- (id)ItemsToData;
- (id)cachedResponseForRequest:(id)arg1;
- (void)calculateSize;
- (void)dealloc;
- (void)deleteFileInItem:(id)arg1 FileManager:(id)arg2;
- (void)deleteItemByKey:(id)arg1;
- (void)deleteItems;
@property(retain, nonatomic) NSMutableDictionary *dicItems; // @synthesize dicItems;
@property(retain, nonatomic) NSMutableDictionary *dicMemStore; // @synthesize dicMemStore;
@property(nonatomic) unsigned long long diskMyCapacity; // @synthesize diskMyCapacity;
@property(retain, nonatomic) NSString *diskPath; // @synthesize diskPath;
@property(nonatomic) unsigned long long diskUseSize; // @synthesize diskUseSize;
- (id)initWithMemoryCapacity:(unsigned long long)arg1 diskCapacity:(unsigned long long)arg2 diskPath:(id)arg3;
- (void)judgeChangeSize:(id)arg1;
- (void)loadItems;
- (void)logMemUsage;
@property(nonatomic) int maxItem; // @synthesize maxItem;
- (_Bool)myStoreToData:(_Bool)arg1;
- (void)removeAllCachedResponses;
- (void)removeCachedResponseForRequest:(id)arg1;
- (void)saveItems;
- (void)saveModified;
- (void)storeCachedResponse:(id)arg1 forRequest:(id)arg2;

@end

