//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface AdCompNativeData : NSObject
{
    NSDictionary *adProperties;
    NSString *nativeAdId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *adProperties; // @synthesize adProperties;
@property(retain, nonatomic) NSString *nativeAdId; // @synthesize nativeAdId;

@end

