//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ADConnectDataProcessor : NSObject
{
    NSMutableDictionary *infoDict;
}

- (void).cxx_destruct;
- (void)addTemporaryData:(id)arg1;
- (void)dealloc;
- (id)getUrlStr;
- (id)getVideoRequest:(id)arg1;
- (id)init;
- (void)initInfo;
- (_Bool)isFileExists:(id)arg1;
- (_Bool)parseResponse:(id)arg1 Error:(id)arg2 withVideoData:(id)arg3;

@end

