//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface AdCompCheckTool : NSObject
{
    NSArray *matchLanding;
}

+ (id)sharedTool;
- (void).cxx_destruct;
- (_Bool)CGColorEqualWithArray:(id)arg1;
- (id)captureView:(id)arg1;
- (void)dealloc;
- (id)getAllIndexColorWithImage:(id)arg1;
- (id)getAllIndexColorWithView:(id)arg1;
- (id)getColorDictWithSize:(struct CGSize)arg1 withImageData:(char *)arg2;
- (id)getPixelColorAtLocation:(struct CGPoint)arg1 withImage:(char *)arg2 andImageWidth:(unsigned long long)arg3;
- (id)getPixelColorStringAtLocation:(struct CGPoint)arg1 withImage:(char *)arg2 andImageWidth:(unsigned long long)arg3;
- (id)init;
- (_Bool)isEmptyAd:(id)arg1;
- (_Bool)isLandingUrl:(id)arg1;
@property(retain, nonatomic) NSArray *matchLanding; // @synthesize matchLanding;
- (double)randomFloatFrom:(double)arg1 To:(double)arg2;
- (struct CGPoint)randomGetPointAtIndex:(int)arg1 withSize:(struct CGSize)arg2;

@end

