//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdCompAdRequest.h"

@interface AdCompAdClickRequest : AdCompAdRequest
{
}

+ (id)requestWithAdContent:(id)arg1 Adapter:(id)arg2;
- (void)dealloc;

@end

