//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AdCompMraidOrientation;

@interface AdCompMraidModalViewController : UIViewController
{
    _Bool isStatusBarHidden;
    _Bool hasViewAppeared;
    _Bool hasRotated;
    AdCompMraidOrientation *orientationProperties;
    long long preferredOrientation;
    id <AdCompMraidModalViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) id <AdCompMraidModalViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)forceToOrientation:(id)arg1;
- (id)init;
- (id)initWithOrientationProperties:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)prefersStatusBarHidden;
- (_Bool)shouldAutorotate;
- (id)stringfromUIInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

