//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdCompMraidWebView, NSURL;

@protocol AdCompMraidViewDelegate <NSObject>

@optional
- (void)mraidViewAdFailed:(AdCompMraidWebView *)arg1;
- (void)mraidViewAdReady:(AdCompMraidWebView *)arg1;
- (void)mraidViewDidClose:(AdCompMraidWebView *)arg1;
- (void)mraidViewNavigate:(AdCompMraidWebView *)arg1 withURL:(NSURL *)arg2;
- (_Bool)mraidViewShouldResize:(AdCompMraidWebView *)arg1 toPosition:(struct CGRect)arg2 allowOffscreen:(_Bool)arg3;
- (void)mraidViewWillExpand:(AdCompMraidWebView *)arg1;
@end

