//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, UIImage;

@interface AdImageItem : NSObject
{
    NSString *imgUrl;
    NSData *imgData;
    UIImage *img;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain) UIImage *img; // @synthesize img;
@property(retain) NSData *imgData; // @synthesize imgData;
@property(retain) NSString *imgUrl; // @synthesize imgUrl;

@end

