//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdInstlManager.h"

#import "AdViewConfigDelegate.h"
#import "AdViewDeviceCollectorDelegate.h"

@class AdInstlAdNetworkAdapter, AdViewConfig, AdViewConfigStore, NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString, NSTimer, UIViewController;

@interface AdInstlManagerImpl : AdInstlManager <AdViewConfigDelegate, AdViewDeviceCollectorDelegate>
{
    AdViewConfig *config;
    AdViewConfig *config_backgroud;
    NSMutableArray *prioritizedAdNetCfgs;
    AdViewConfigStore *configStore;
    unsigned long long configFetchAttempts;
    _Bool gotConfig;
    _Bool isNeedHangUp;
    double totalPercent;
    NSMutableDictionary *pendingAdapters;
    AdInstlAdNetworkAdapter *lastAdapter;
    AdInstlAdNetworkAdapter *currAdapter;
    NSArray *testDarts;
    unsigned long long testDartIndex;
    _Bool bWaitPresent;
    NSDate *lastRequestTime;
    UIViewController *lastController;
    _Bool bLoadingAd;
    _Bool singleLoading;
    NSTimer *_configTimer;
}

- (void).cxx_destruct;
- (id)adInstlReportMetricBaseURLString;
- (void)adRequestReturnsForAdapter:(id)arg1;
- (void)adViewConfigDidFail;
- (void)adViewConfigDidReceiveConfig;
- (id)adViewConfigURL;
- (void)adapter:(id)arg1 didGetEvent:(int)arg2 error:(id)arg3;
- (void)adapter:(id)arg1 requestString:(id)arg2;
- (id)appKey;
- (void)buildPrioritizedAdNetCfgs;
- (void)clearLoadingFlagFunc;
@property(retain, nonatomic) AdViewConfig *config; // @synthesize config;
@property(retain, nonatomic) NSTimer *configTimer; // @synthesize configTimer=_configTimer;
@property(retain, nonatomic) AdViewConfig *config_backgroud; // @synthesize config_backgroud;
@property(retain, nonatomic) AdInstlAdNetworkAdapter *currAdapter; // @synthesize currAdapter;
- (id)currentNetworkName;
- (void)dealloc;
- (id)initWithAdInstlKey:(id)arg1 WithDelegate:(id)arg2;
- (_Bool)isReady;
@property(retain, nonatomic) AdInstlAdNetworkAdapter *lastAdapter; // @synthesize lastAdapter;
@property(nonatomic) __weak UIViewController *lastController; // @synthesize lastController;
- (_Bool)loadAdInstlView:(id)arg1;
- (_Bool)loadSingleAdInstlView:(id)arg1 withIndex:(int)arg2;
- (int)loadType;
- (_Bool)makeRequest:(id)arg1;
- (id)marketChannel;
- (void)metricPing:(id)arg1 nid:(id)arg2 netType:(int)arg3 reportString:(id)arg4;
- (void)moveNetCfgs:(id)arg1 AdFill:(_Bool)arg2;
- (double)nextDart;
- (id)nextNetworkCfgByPercent;
- (id)nextNetworkCfgByPriority;
- (void)notifyDelegateOfError:(id)arg1;
@property(retain, nonatomic) NSMutableArray *prioritizedAdNetCfgs; // @synthesize prioritizedAdNetCfgs;
- (void)reportExData:(id)arg1 netType:(int)arg2 reportType:(id)arg3;
- (void)rollOver;
- (void)setDelegate:(id)arg1;
- (void)setInLoading:(_Bool)arg1;
@property(retain, nonatomic) NSArray *testDarts; // @synthesize testDarts;
- (_Bool)showAdInstlView:(id)arg1;
- (void)startGetConfig;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

