//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdInstlAdNetworkAdapter.h"

#import "AdCompViewDelegate.h"

@class AdCompView, NSString, UIViewController;

@interface AdInstlAdapterOpenAPI : AdInstlAdNetworkAdapter <AdCompViewDelegate>
{
    AdCompView *adInstlKopen;
    _Bool isReuseRequest;
    UIViewController *parent;
}

+ (void)load;
+ (int)networkType;
- (void).cxx_destruct;
- (int)OpenAPIAdType;
- (void)adInstlDidDismissScreen:(id)arg1;
@property(retain, nonatomic) AdCompView *adInstlKopen; // @synthesize adInstlKopen;
- (void)adViewDidDismissScreen:(id)arg1;
- (void)adViewWillPresentScreen:(id)arg1;
- (id)appId;
- (void)dealloc;
- (void)didFailToReceiveAd:(id)arg1 Error:(id)arg2;
- (void)didReceivedAd:(id)arg1 reuse:(_Bool)arg2;
- (id)getLocation;
@property(nonatomic) _Bool isReuseRequest; // @synthesize isReuseRequest;
- (id)kAdViewHost;
- (_Bool)loadAdInstl:(id)arg1;
- (void)needPreAddView:(id)arg1;
@property(nonatomic) __weak UIViewController *parent; // @synthesize parent;
- (_Bool)showAdInstl:(id)arg1;
- (void)stopBeingDelegate;
- (_Bool)testMode;
- (_Bool)usingHTML5;
- (_Bool)usingSKStoreProductViewController;
- (id)viewControllerForShowModal;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

