//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdInstlAdNetworkAdapter.h"

#import "BaiduMobAdInterstitialDelegate.h"

@class BaiduMobAdInterstitial, NSString;

__attribute__((visibility("hidden")))
@interface AdInstlAdapterBaidu : AdInstlAdNetworkAdapter <BaiduMobAdInterstitialDelegate>
{
    BaiduMobAdInterstitial *interstitialView;
}

+ (void)load;
+ (int)networkType;
- (void).cxx_destruct;
- (id)appSpec;
- (id)channelId;
- (_Bool)enableLocation;
- (void)interstitialDidDismissScreen:(id)arg1;
- (void)interstitialFailPresentScreen:(id)arg1 withError:(int)arg2;
- (void)interstitialFailToLoadAd:(id)arg1;
- (void)interstitialSuccessPresentScreen:(id)arg1;
- (void)interstitialSuccessToLoadAd:(id)arg1;
@property(retain, nonatomic) BaiduMobAdInterstitial *interstitialView; // @synthesize interstitialView;
- (void)interstitialWillPresentScreen:(id)arg1;
- (_Bool)loadAdInstl:(id)arg1;
- (id)publisherId;
- (_Bool)showAdInstl:(id)arg1;
- (void)stopBeingDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

