//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdNativeAdNetworkAdapter.h"

#import "IMNativeDelegate.h"

@class IMNative, NSString;

__attribute__((visibility("hidden")))
@interface AdNativeAdapterInMobi : AdNativeAdNetworkAdapter <IMNativeDelegate>
{
    IMNative *_nativeAd;
}

+ (void)load;
+ (int)networkType;
- (void).cxx_destruct;
- (void)clickNativeAd:(id)arg1;
- (void)loadNativeAd:(int)arg1;
- (void)native:(id)arg1 didFailToLoadWithError:(id)arg2;
@property(retain, nonatomic) IMNative *nativeAd; // @synthesize nativeAd=_nativeAd;
- (void)nativeAdImpressed:(id)arg1;
- (void)nativeDidDismissScreen:(id)arg1;
- (void)nativeDidFinishLoading:(id)arg1;
- (void)nativeDidPresentScreen:(id)arg1;
- (void)nativeWillDismissScreen:(id)arg1;
- (void)nativeWillPresentScreen:(id)arg1;
- (void)showNativeAd:(id)arg1 withNativeData:(id)arg2;
- (void)stopBeingDelegate;
- (void)userWillLeaveApplicationFromNative:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

