//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class ADConnectDataProcessor, ADVideoData, NSMutableData, NSString, NSURLResponse;

@interface ADURLConnection : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    ADVideoData *videoData;
    id <ADURLConnectionDelegate> conDelegate;
    ADConnectDataProcessor *dataProcessor;
    int currentType;
    NSMutableData *httpData;
    NSURLResponse *conResponse;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <ADURLConnectionDelegate> conDelegate; // @synthesize conDelegate;
@property(retain, nonatomic) NSURLResponse *conResponse; // @synthesize conResponse;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSMutableData *httpData; // @synthesize httpData;
- (id)initWithConnectionType:(int)arg1 withTemporaryData:(id)arg2 delegate:(id)arg3;
- (void)makeConnectionWithTemporaryData:(id)arg1;
@property(retain, nonatomic) ADVideoData *videoData; // @synthesize videoData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

