//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface ADVASTUrlWithId : NSObject
{
    NSString *_id_;
    NSURL *_url;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *id_; // @synthesize id_=_id_;
- (id)initWithID:(id)arg1 url:(id)arg2;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;

@end

