//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface ADVASTModel : NSObject
{
    unsigned long long currentIndex;
    NSMutableArray *adsArray;
    NSMutableArray *vastDocumentArray;
}

- (void).cxx_destruct;
- (void)addVASTDocument:(id)arg1;
@property(retain, nonatomic) NSMutableArray *adsArray; // @synthesize adsArray;
- (id)clickThrough:(id)arg1;
- (id)clickTracking:(id)arg1;
- (id)companion:(id)arg1;
- (id)content:(id)arg1;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex;
- (void)dealloc;
- (id)errors:(id)arg1;
- (void)getAvailableCreativeAndInfo:(unsigned long long)arg1 dict:(id)arg2;
- (void)getCompanionAd:(unsigned long long)arg1 dict:(id)arg2;
- (id)getCurrentAd;
- (void)getInLineAvailableAd;
- (id)iconFiles:(id)arg1;
- (id)impressions:(id)arg1;
- (id)init;
- (id)mediaFiles:(id)arg1;
- (id)resultsForQuery:(id)arg1;
- (id)trackingEvents:(id)arg1;
- (id)urlWithCleanString:(id)arg1;
- (id)vastVersion;

@end

