//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ADVASTRequestTask, NSError;

@protocol ADVASTRequestTaskDelegate <NSObject>
- (void)requestTaskDidUpdateCache;

@optional
- (void)requestTaskDidFailWithError:(NSError *)arg1 task:(ADVASTRequestTask *)arg2;
- (void)requestTaskDidFinishLoadingWithCache:(_Bool)arg1 task:(ADVASTRequestTask *)arg2;
- (void)requestTaskDidReceiveResponse;
@end

