//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle;

@interface ADVASTFileHandle : NSObject
{
    NSFileHandle *_writeFileHandle;
    NSFileHandle *_readFileHandle;
}

+ (id)cacheFileExistsWithURL:(id)arg1;
+ (id)cacheFolderPath;
+ (void)cacheTempFileWithFileName:(id)arg1;
+ (_Bool)clearCache;
+ (void)clearCacheWithURL:(id)arg1;
+ (_Bool)createTempFile;
+ (id)fileNameWithURL:(id)arg1 fileType:(id)arg2;
+ (id)findTheOldFile:(id)arg1 newFileSize:(int)arg2;
+ (id)logVideoCacheInfoForTest;
+ (void)printCacheFile;
+ (id)readTempFileDataWithOffset:(unsigned long long)arg1 length:(unsigned long long)arg2;
+ (id)tempFilePath;
+ (void)writeTempFileData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSFileHandle *readFileHandle; // @synthesize readFileHandle=_readFileHandle;
@property(retain, nonatomic) NSFileHandle *writeFileHandle; // @synthesize writeFileHandle=_writeFileHandle;

@end

