//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADVASTRequestTaskDelegate.h"
#import "AVAssetResourceLoaderDelegate.h"

@class ADVASTRequestTask, NSMutableArray, NSString;

@interface ADVASTResourceLoader : NSObject <AVAssetResourceLoaderDelegate, ADVASTRequestTaskDelegate>
{
    _Bool _seekRequired;
    _Bool _cacheFinished;
    id <ADVASTResourceLoaderDelegate> _delegate;
    NSMutableArray *_requestList;
    ADVASTRequestTask *_requestTask;
}

- (void).cxx_destruct;
- (void)addLoadingRequest:(id)arg1;
@property(nonatomic) _Bool cacheFinished; // @synthesize cacheFinished=_cacheFinished;
@property(nonatomic) __weak id <ADVASTResourceLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)finishLoadingWithLoadingRequest:(id)arg1;
- (id)init;
- (void)newTaskWithLoadingRequest:(id)arg1 cache:(_Bool)arg2;
- (void)processRequestList;
- (void)removeLoadingRequest:(id)arg1;
@property(retain, nonatomic) NSMutableArray *requestList; // @synthesize requestList=_requestList;
@property(retain, nonatomic) ADVASTRequestTask *requestTask; // @synthesize requestTask=_requestTask;
- (void)requestTaskDidFailWithError:(id)arg1 task:(id)arg2;
- (void)requestTaskDidFinishLoadingWithCache:(_Bool)arg1 task:(id)arg2;
- (void)requestTaskDidUpdateCache;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
@property _Bool seekRequired; // @synthesize seekRequired=_seekRequired;
- (void)stopLoading;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

