//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface ADVASTEventProcessor : NSObject
{
    NSDictionary *_trackingEvents;
    id <ADVASTViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <ADVASTViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithTrackingEvents:(id)arg1 withDelegate:(id)arg2;
- (void)sendTrackingRequest:(id)arg1;
- (void)sendVASTUrlsWithId:(id)arg1;
@property(retain, nonatomic) NSDictionary *trackingEvents; // @synthesize trackingEvents=_trackingEvents;
- (void)trackEvent:(int)arg1;

@end

