//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AdVideoManager : NSObject
{
    id <AdVideoManagerDelegate> delegate;
    NSString *adVideoKey;
    NSString *appChannel;
    _Bool autoRoll;
    _Bool disableShowAlert;
}

+ (id)managerWithAdVideoKey:(id)arg1 WithDelegate:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adVideoKey; // @synthesize adVideoKey;
- (void)adapter:(id)arg1 didGetEvent:(int)arg2 error:(id)arg3;
@property(retain, nonatomic) NSString *appChannel; // @synthesize appChannel;
@property(nonatomic) _Bool autoRoll; // @synthesize autoRoll;
- (id)currentNetworkName;
- (void)dealloc;
@property(nonatomic) __weak id <AdVideoManagerDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool disableShowAlert; // @synthesize disableShowAlert;
- (_Bool)isReady;
- (_Bool)loadSingleAdVideoView:(id)arg1 withIndex:(int)arg2;
- (int)loadType;
- (_Bool)loadVideoAd:(id)arg1;
- (id)marketChannel;
- (_Bool)showVideoAdWithController:(id)arg1;
- (void)startGetConfig;
- (void)updateUserID:(id)arg1;

@end

