//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface AdViewReqItem : NSObject
{
    _Bool _bIsSending;
    int _nId;
    int _sdkVer;
    int _configVer;
    int _dataTime;
    int _nTrySend;
    NSString *_appid;
    NSString *_bundle;
    NSString *_uuid;
    NSString *_devKey;
    NSMutableDictionary *_data;
}

+ (int)curSecond;
+ (id)fromData:(id)arg1;
+ (_Bool)isVal:(id)arg1 InArray:(id)arg2;
+ (void)linkDic:(id)arg1 ToString:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property _Bool bIsSending; // @synthesize bIsSending=_bIsSending;
@property(retain, nonatomic) NSString *bundle; // @synthesize bundle=_bundle;
@property(nonatomic) int configVer; // @synthesize configVer=_configVer;
@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
- (id)dataJSON;
@property(nonatomic) int dataTime; // @synthesize dataTime=_dataTime;
@property(retain, nonatomic) NSString *devKey; // @synthesize devKey=_devKey;
- (_Bool)isEmpty;
- (id)makeData;
- (id)makePostBody;
@property(nonatomic) int nId; // @synthesize nId=_nId;
@property int nTrySend; // @synthesize nTrySend=_nTrySend;
@property(nonatomic) int sdkVer; // @synthesize sdkVer=_sdkVer;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)storeDataType:(int)arg1 ReqType:(id)arg2;

@end

