//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdVideoAdNetworkAdapter.h"

#import "AdViewVideoDelegate.h"

@class AdViewVideo, NSString, UIViewController;

@interface AdVideoAdapterOpenAPI : AdVideoAdNetworkAdapter <AdViewVideoDelegate>
{
    AdViewVideo *adVideoKopen;
    UIViewController *parent;
}

+ (void)load;
+ (int)networkType;
- (void).cxx_destruct;
- (void)AdViewVideoClosed;
- (void)AdViewVideoDidReceiveAd:(id)arg1;
- (void)AdViewVideoFailReceiveDataWithError:(id)arg1;
- (void)AdViewVideoIsReadyToPlay:(id)arg1;
- (void)AdViewVideoPlayEnded;
- (void)AdViewVideoPlayStarted;
- (int)OpenAPIAdType;
@property(retain, nonatomic) AdViewVideo *adVideoKopen; // @synthesize adVideoKopen;
- (id)appId;
- (void)dealloc;
- (_Bool)loadAdVideo:(id)arg1;
@property(nonatomic) __weak UIViewController *parent; // @synthesize parent;
- (id)positionId;
- (void)rotateToOrientation:(long long)arg1;
- (_Bool)showAdVideo:(id)arg1;
- (void)stopBeingDelegate;
- (_Bool)testMode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

