//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSURL, UIColor, UIImage, UILabel;

@interface AdViewCustomAdView : UIButton
{
    id <AdViewCustomAdViewDelegate> _delegate;
    UIImage *image;
    UILabel *textLabel;
    NSURL *redirectURL;
    NSURL *clickMetricsURL;
    int adType;
    int launchType;
    int animType;
    UIColor *backgroundColor;
    UIColor *textColor;
    id <AdViewCustomAdViewDelegate> delegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) int adType; // @synthesize adType;
@property(readonly, nonatomic) int animType; // @synthesize animType;
@property(readonly, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor;
- (void)buttonTapUp:(id)arg1;
@property(readonly, nonatomic) NSURL *clickMetricsURL; // @synthesize clickMetricsURL;
- (void)dealloc;
@property(nonatomic) __weak id <AdViewCustomAdViewDelegate> delegate; // @synthesize delegate;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
- (id)initWithDelegate:(id)arg1 text:(id)arg2 redirectURL:(id)arg3 clickMetricsURL:(id)arg4 adType:(int)arg5 launchType:(int)arg6 animType:(int)arg7 backgroundColor:(id)arg8 textColor:(id)arg9;
@property(readonly, nonatomic) int launchType; // @synthesize launchType;
@property(readonly, nonatomic) NSURL *redirectURL; // @synthesize redirectURL;
@property(readonly, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel;

@end

