//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface AdviewObjCollector : NSObject
{
    NSMutableArray *arrObjs;
    NSObject *lockObj;
    NSTimer *cTimer;
}

+ (id)sharedCollector;
- (void).cxx_destruct;
- (void)addObj:(id)arg1;
- (void)addObj:(id)arg1 wait:(int)arg2;
- (void)addTimer;
@property(retain) NSMutableArray *arrObjs; // @synthesize arrObjs;
- (void)dealloc;
- (void)handleTimer;
- (id)init;
- (void)removeObj:(id)arg1;
- (void)setAdapterAdViewViewNil:(id)arg1;

@end

