//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface ADVideoData : NSObject
{
    NSString *htmlData;
    struct CGSize videoSize;
    NSArray *showSourceUrlArr;
    NSString *actClickUrlStr;
    NSString *adBody;
    int adActionType;
    NSArray *clickReportArr;
    NSArray *showReportArr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *actClickUrlStr; // @synthesize actClickUrlStr;
@property(nonatomic) int adActionType; // @synthesize adActionType;
@property(retain, nonatomic) NSString *adBody; // @synthesize adBody;
@property(retain, nonatomic) NSArray *clickReportArr; // @synthesize clickReportArr;
- (void)dealloc;
@property(retain, nonatomic) NSString *htmlData; // @synthesize htmlData;
@property(retain, nonatomic) NSArray *showReportArr; // @synthesize showReportArr;
@property(retain, nonatomic) NSArray *showSourceUrlArr; // @synthesize showSourceUrlArr;
@property(nonatomic) struct CGSize videoSize; // @synthesize videoSize;

@end

