//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AdViewClassWrapper : NSObject
{
    Class theClass;
    _Bool theEnable;
    _Bool theHide;
}

- (id)initWithClass:(Class)arg1;
@property(nonatomic) _Bool theEnable; // @synthesize theEnable;
@property(nonatomic) _Bool theHide; // @synthesize theHide;
@property(readonly, nonatomic) Class theClass; // @synthesize theClass;

@end

