//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdViewAdNetworkAdapter.h"

#import "BaiduMobAdViewDelegate.h"

@class BaiduMobAdView, NSString;

__attribute__((visibility("hidden")))
@interface AdViewAdapterBaidu : AdViewAdNetworkAdapter <BaiduMobAdViewDelegate>
{
    BaiduMobAdView *sharedAdView;
}

+ (void)load;
+ (int)networkType;
- (void).cxx_destruct;
- (struct CGRect)adRect;
- (id)channelId;
- (void)cleanupDummyRetain;
- (void)dealloc;
- (void)didAdClicked;
- (void)didAdImpressed;
- (void)didDismissLandingPage;
- (_Bool)enableLocation;
- (void)failedDisplayAd:(int)arg1;
- (void)getAd;
- (id)publisherId;
@property(retain, nonatomic) BaiduMobAdView *sharedAdView; // @synthesize sharedAdView;
- (_Bool)shouldSendExMetric;
- (void)stopBeingDelegate;
- (void)updateSizeParameter;
- (void)willDisplayAd:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

