//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdVideoAdapterOpenAPI.h"

@interface AdVideoAdapterKyAdFill : AdVideoAdapterOpenAPI
{
}

+ (void)load;
+ (int)networkType;
- (int)OpenAPIAdType;
- (id)appId;
- (int)configVersion;
- (id)positionId;

@end

