//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdViewAdNetworkAdapter.h"

#import "AdCompViewDelegate.h"

@class NSString;

@interface AdViewAdapterOpenAPI : AdViewAdNetworkAdapter <AdCompViewDelegate>
{
}

+ (void)load;
+ (int)networkType;
- (int)OpenAPIAdType;
- (id)adBackgroundColor;
- (id)adTextColor;
- (void)adViewDidDismissScreen:(id)arg1;
- (void)adViewWillPresentScreen:(id)arg1;
- (id)appId;
- (int)autoRefreshInterval;
- (void)dealloc;
- (void)didFailToReceiveAd:(id)arg1 Error:(id)arg2;
- (void)didReceivedAd:(id)arg1 reuse:(_Bool)arg2;
- (void)getAd;
- (id)getLocation;
- (int)gradientBgType;
- (id)kAdViewHost;
- (_Bool)logMode;
- (void)needPreAddView:(id)arg1;
- (void)stopBeingDelegate;
- (_Bool)testMode;
- (void)updateSizeParameter;
- (_Bool)usingHTML5;
- (_Bool)usingSKStoreProductViewController;
- (id)viewControllerForShowModal;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

