//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdViewConfig, NSError, NSURL;

@protocol AdViewConfigDelegate <NSObject>

@optional
- (void)adViewConfigDidFail:(AdViewConfig *)arg1 error:(NSError *)arg2;
- (void)adViewConfigDidReceiveConfig:(AdViewConfig *)arg1;
- (NSURL *)adViewConfigURL;
@end

