//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIWebViewDelegate.h"

@class NSMutableArray, NSString, NSURL, NSURLRequest, UIActivityIndicatorView, UIWebView;

@interface ADVideoWebViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate>
{
    NSMutableArray *arrToolItems;
    UIActivityIndicatorView *indicatorView;
    NSURL *currURL;
    UIWebView *_webView;
    NSURLRequest *_urlRequest;
    NSString *_urlString;
    NSString *_bodyString;
    id <ADVideoWebViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSString *bodyString; // @synthesize bodyString=_bodyString;
- (void)closeButtonPressed:(id)arg1;
@property(retain, nonatomic) NSURL *currURL; // @synthesize currURL;
- (void)dealloc;
@property(nonatomic) __weak id <ADVideoWebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)goAction;
- (void)goBack;
- (void)goForward;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)loadWebView;
- (void)makeCloseButton;
- (void)makeToolBar;
- (void)openInSafari;
- (void)reload;
- (void)setItemStates;
@property(retain, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

