//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSArray, NSString, UIBarButtonItem, UIToolbar, UIWebView;

@interface AdViewWebBrowserController : UIViewController <UIWebViewDelegate>
{
    id <AdViewWebBrowserControllerDelegate> delegate;
    UIViewController *_viewControllerForPresenting;
    NSArray *loadingButtons;
    NSArray *loadedButtons;
    int transitionType;
    UIWebView *webView;
    UIToolbar *toolBar;
    UIBarButtonItem *backButton;
    UIBarButtonItem *forwardButton;
    UIBarButtonItem *reloadButton;
    UIBarButtonItem *stopButton;
    UIBarButtonItem *linkOutButton;
    UIBarButtonItem *closeButton;
    UIViewController *viewControllerForPresenting;
}

- (void).cxx_destruct;
- (void)back:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *backButton; // @synthesize backButton;
- (void)close:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *closeButton; // @synthesize closeButton;
- (void)dealloc;
@property(nonatomic) __weak id <AdViewWebBrowserControllerDelegate> delegate; // @synthesize delegate;
- (void)didReceiveMemoryWarning;
- (void)forward:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *forwardButton; // @synthesize forwardButton;
- (id)init;
- (void)linkOut:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *linkOutButton; // @synthesize linkOutButton;
- (void)loadURL:(id)arg1;
@property(retain, nonatomic) NSArray *loadedButtons; // @synthesize loadedButtons;
@property(retain, nonatomic) NSArray *loadingButtons; // @synthesize loadingButtons;
- (void)presentWithController:(id)arg1 transition:(int)arg2;
- (void)reload:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *reloadButton; // @synthesize reloadButton;
@property(retain, nonatomic) UIBarButtonItem *stopButton; // @synthesize stopButton;
@property(retain, nonatomic) UIToolbar *toolBar; // @synthesize toolBar;
@property(nonatomic) __weak UIViewController *viewControllerForPresenting; // @synthesize viewControllerForPresenting;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView;
- (_Bool)shouldAutorotate;
- (void)stop:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

