//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdVideoManager, AdViewAdNetworkConfig, AdViewConfig, UIViewController;

@interface AdVideoAdNetworkAdapter : NSObject
{
    id <AdVideoManagerDelegate> adVideoDelegate;
    AdVideoManager *adVideoManager;
    AdViewConfig *adVideoConfig;
    AdViewAdNetworkConfig *networkConfig;
    UIViewController *adVideoController;
    int loadType;
    _Bool _bWaitAd;
}

+ (int)networkType;
- (void).cxx_destruct;
@property(retain, nonatomic) AdViewConfig *adVideoConfig; // @synthesize adVideoConfig;
@property(retain, nonatomic) UIViewController *adVideoController; // @synthesize adVideoController;
@property(nonatomic) __weak id <AdVideoManagerDelegate> adVideoDelegate; // @synthesize adVideoDelegate;
@property(nonatomic) __weak AdVideoManager *adVideoManager; // @synthesize adVideoManager;
@property(nonatomic) _Bool bWaitAd; // @synthesize bWaitAd=_bWaitAd;
- (void)dealloc;
- (id)initWithAdVideoDelegate:(id)arg1 manager:(id)arg2 config:(id)arg3 networkConfig:(id)arg4;
- (_Bool)isBannerAnimationOK:(int)arg1;
- (_Bool)isOpenGps;
- (_Bool)isTestMode;
- (_Bool)loadAdVideo:(id)arg1;
@property(nonatomic) int loadType; // @synthesize loadType;
@property(retain, nonatomic) AdViewAdNetworkConfig *networkConfig; // @synthesize networkConfig;
- (void)rotateToOrientation:(long long)arg1;
- (_Bool)shouldSendExMetric;
- (_Bool)showAdVideo:(id)arg1;
- (void)stopBeingDelegate;

@end

