//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AdViewDBManager : NSObject
{
    struct sqlite3 *_database;
    NSString *_path;
}

+ (void)closeDBManager:(id)arg1;
+ (id)sharedDBManagerWithPath:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)delAdViewReqInfo:(int)arg1 SDKType:(int)arg2;
- (_Bool)ensureAdInstlReqInfoTable;
- (_Bool)ensureAdViewConfigTable;
- (_Bool)execSql:(id)arg1;
- (int)getMaxAdViewReqInfoId:(int)arg1;
- (id)initWithPath:(id)arg1;
- (id)loadAdViewConfig:(id)arg1 SDKType:(int)arg2;
- (_Bool)loadAdViewReqItems:(id)arg1 SDKType:(int)arg2;
- (id)path;
- (_Bool)saveAdViewConfig:(id)arg1 Key:(id)arg2 SDKType:(int)arg3;
- (_Bool)saveAdViewReqItem:(id)arg1 SDKType:(int)arg2;

@end

