//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AdviewObjCollectItem : NSObject
{
    int _waitVal;
    NSObject *_objVal;
    double _timeVal;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSObject *objVal; // @synthesize objVal=_objVal;
@property(nonatomic) double timeVal; // @synthesize timeVal=_timeVal;
@property(nonatomic) int waitVal; // @synthesize waitVal=_waitVal;

@end

