//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AVTemporaryData : NSObject
{
    NSString *appID;
    NSString *posID;
    NSString *videoTypeStr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
@property(retain, nonatomic) NSString *posID; // @synthesize posID;
@property(retain, nonatomic) NSString *videoTypeStr; // @synthesize videoTypeStr;

@end

