//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdImageRenderer.h"

@interface BaiduMobAdGifImageRenderer : BaiduMobAdImageRenderer
{
}

- (struct CGSize)getScaledImageSize:(id)arg1;
- (void)showGifImage:(id)arg1 withMIMEType:(id)arg2;
- (void)showResource:(id)arg1 withMimeType:(id)arg2;

@end

