//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XNonLinearAdSlot.h"

@interface BaiduMobAdInterstitialSlot : XNonLinearAdSlot
{
    _Bool _interstitialPreLoad;
    int _interstitialType;
}

- (id)buildFixedResponse;
@property(nonatomic) _Bool interstitialPreLoad; // @synthesize interstitialPreLoad=_interstitialPreLoad;
@property(nonatomic) int interstitialType; // @synthesize interstitialType=_interstitialType;
- (void)request;
- (void)start;
- (void)successCallback:(id)arg1 withRequestAndResponseDic:(id)arg2;
- (id)type;

@end

