//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RennParam.h"

@class NSArray;

@interface BatchUserParam : RennParam
{
    NSArray *_userIds;
}

- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSArray *userIds; // @synthesize userIds=_userIds;

@end

