//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBPlayerControlView;

@protocol BBPlayerControlViewDelegate <NSObject>
- (void)controlView:(BBPlayerControlView *)arg1 scrubbingToTime:(double)arg2;
- (void)controlViewDidBeginScrubbing:(BBPlayerControlView *)arg1;
- (void)controlViewDidEndScrubbing:(BBPlayerControlView *)arg1;
- (void)controlViewDidPause:(BBPlayerControlView *)arg1;
- (void)controlViewDidPlay:(BBPlayerControlView *)arg1;
- (void)controlViewDidToggleFullscreen:(BBPlayerControlView *)arg1;
- (void)controlViewDidToggleVRGlass:(BBPlayerControlView *)arg1;
@end

