//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BBPlayerViewController<BBPlayerControlViewDelegate>, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface BBPlayerNoCopyrightView : UIView
{
    UIButton *playButton;
    UILabel *messageLabel;
    BBPlayerViewController<BBPlayerControlViewDelegate> *_playerController;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)play:(id)arg1;
@property(nonatomic) BBPlayerViewController<BBPlayerControlViewDelegate> *playerController; // @synthesize playerController=_playerController;

@end

