//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BBPlayerControlViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class BBPlayerControlView, MDVRLibrary, NSDate, NSError, NSString, NSTimer, NSURL, UIView;

__attribute__((visibility("hidden")))
@interface BBPlayerViewController : UIViewController <BBPlayerControlViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _seekToZeroBeforePlay;
    _Bool _userPaused;
    _Bool _autoPaused;
    _Bool _readyToPlay;
    _Bool _playStarted;
    double _lastPlayTime;
    long long _gestureType;
    struct CGPoint _lastTouchLocation;
    double _lastScrubbedPlayTime;
    NSDate *_lastScrubberSetTimeTime;
    NSTimer *_timeObserver;
    struct CGRect _originalFrame;
    long long _originalStatusBarStyle;
    UIView *_originalSuperview;
    _Bool _isRotating;
    _Bool _noCopyright;
    long long _projectionMode;
    _Bool _fullscreen;
    _Bool _autoFullscreen;
    _Bool _autoPlay;
    id <IJKMediaPlayback> _player;
    BBPlayerControlView *_controlView;
    NSURL *_contentURL;
    NSError *_error;
    id <BBPlayerControllerDelegate> _delegate;
    MDVRLibrary *_vrLibrary;
}

+ (id)playerErrorWithCode:(int)arg1;
- (void).cxx_destruct;
- (void)assetFailedToPrepareForPlayback:(id)arg1;
@property(nonatomic) _Bool autoFullscreen; // @synthesize autoFullscreen=_autoFullscreen;
@property(readonly, nonatomic) _Bool autoPaused; // @synthesize autoPaused=_autoPaused;
@property(nonatomic) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
- (_Bool)canShowStatusBar;
@property(retain, nonatomic) NSURL *contentURL; // @synthesize contentURL=_contentURL;
@property(retain, nonatomic) BBPlayerControlView *controlView; // @synthesize controlView=_controlView;
- (void)controlView:(id)arg1 scrubbingToTime:(double)arg2;
- (void)controlViewDidBeginScrubbing:(id)arg1;
- (void)controlViewDidEndScrubbing:(id)arg1;
- (void)controlViewDidPause:(id)arg1;
- (void)controlViewDidPlay:(id)arg1;
- (void)controlViewDidToggleFullscreen:(id)arg1;
- (void)controlViewDidToggleVRGlass:(id)arg1;
- (double)currentTime;
- (void)dealloc;
@property(nonatomic) __weak id <BBPlayerControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didBeginScrubbing;
- (void)didEndScrubbing;
- (void)didEnterBackground:(id)arg1;
- (void)doubleTappedScreen:(id)arg1;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)hideControlView;
- (void)initScrubberTimer;
- (_Bool)isAtTheEnd;
@property(nonatomic, getter=isFullscreen) _Bool fullscreen; // @synthesize fullscreen=_fullscreen;
- (_Bool)isFullscreenPortrait;
- (_Bool)isPlaying;
- (void)loadView;
- (double)loadedDuration;
- (void)orientationChanged:(id)arg1;
- (void)pannedScreen:(id)arg1;
- (void)pause;
- (void)pinchedScreen:(id)arg1;
- (void)play;
@property(retain, nonatomic) id <IJKMediaPlayback> player; // @synthesize player=_player;
- (void)playerIsPreparedToPlayDidChange:(id)arg1;
- (double)playerItemDuration;
- (void)playerLoadStateDidChange:(id)arg1;
- (void)playerPlayBackDidFinish:(id)arg1;
- (void)playerPlayBackStateDidChange:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)reload;
- (double)remainingTime;
- (void)removePlayerTimeObserver;
- (void)resetControlsForNewPlayback;
- (void)resetPlaybackFlags;
- (void)seekTo:(double)arg1;
- (void)setContentURL:(id)arg1 isHLS:(_Bool)arg2;
- (void)setContentURL:(id)arg1 isHLS:(_Bool)arg2 projectionMode:(long long)arg3;
- (void)setContentURL:(id)arg1 isHLS:(_Bool)arg2 projectionMode:(long long)arg3 playerHeaders:(id)arg4;
- (void)setFullscreen:(_Bool)arg1 automatically:(_Bool)arg2;
- (void)setMessage:(id)arg1;
- (void)setNoCopyright:(_Bool)arg1 coverURL:(id)arg2;
- (void)setTimeWhileScrubbingPaused:(id)arg1;
@property(retain, nonatomic) MDVRLibrary *vrLibrary; // @synthesize vrLibrary=_vrLibrary;
- (void)showControlView;
- (void)showEndCounterViewWithTitle:(id)arg1;
- (void)shutdown;
- (void)stop;
- (void)syncScrubber:(id)arg1;
- (void)tappedScreen:(id)arg1;
- (void)toggleVideoFillMode;
- (void)willEnterForeground:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

