//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class BBPlayerEndCounterView, BBPlayerNoCopyrightView, BBPlayerViewController<BBPlayerControlViewDelegate>, MyPlayerLoadingView, MyPlayerScrubber, TTImageView, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface BBPlayerControlView : UIView
{
    TTImageView *coverImageView;
    UIView *bottomView;
    MyPlayerScrubber *scrubber;
    UILabel *currentTimeLabel;
    UILabel *remainingTimeLabel;
    UIButton *playButton;
    UIButton *pauseButton;
    UIButton *fullscreenButton;
    UIButton *vrGlassButton;
    MyPlayerLoadingView *loadingView;
    BBPlayerNoCopyrightView *noCopyrightView;
    BBPlayerEndCounterView *endCounterView;
    _Bool vrGlassEnabled;
    BBPlayerViewController<BBPlayerControlViewDelegate> *_playerController;
}

+ (id)stringForSeconds:(double)arg1;
- (void).cxx_destruct;
- (void)beginScrubbing:(id)arg1;
- (void)dealloc;
- (void)disablePlayerButtons;
- (void)disableScrubber;
- (void)enablePlayerButtons;
- (void)enableScrubber;
- (void)endScrubbing:(id)arg1;
- (float)getScrubberValue;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)pause:(id)arg1;
- (void)play:(id)arg1;
@property(nonatomic) __weak BBPlayerViewController<BBPlayerControlViewDelegate> *playerController; // @synthesize playerController=_playerController;
- (void)resetControls;
- (void)scrub:(id)arg1;
- (void)seekToValue:(double)arg1;
- (void)setMessage:(id)arg1;
- (void)setNoCopyright:(_Bool)arg1 coverURL:(id)arg2;
- (void)showControlButtons:(_Bool)arg1;
- (void)showEndCounterView:(_Bool)arg1 withTitle:(id)arg2;
- (void)showLoading:(_Bool)arg1;
- (void)showPauseButton;
- (void)showPlayButton;
- (void)showVRGlassButton:(_Bool)arg1;
- (void)syncPlayPauseButtons;
- (void)syncScrubber:(_Bool)arg1;
- (void)syncScrubberToTime:(double)arg1 animated:(_Bool)arg2;
- (void)toggleFullscreen:(id)arg1;
- (void)vrGlassButtonTapped:(id)arg1;

@end

