//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ConfigFetchItem;

@protocol ConfigFetchItemDelegate
- (void)configFetchFailed:(ConfigFetchItem *)arg1;
- (void)configFetchFinished:(ConfigFetchItem *)arg1;
- (void)configFetchToStore:(ConfigFetchItem *)arg1;
@end

