//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabase, NSMutableArray, NSString, TTURLRequest;

__attribute__((visibility("hidden")))
@interface FavoritesManager : NSObject
{
    FMDatabase *_db;
    _Bool _syncingFavorites;
    _Bool _downloadingFavorites;
    NSString *_syncingUid;
    int _syncingCategory;
    int _syncMode;
    int _downloadType;
    _Bool _continueFirstSync;
    long long _firstSyncCount;
    long long _continueSyncCount;
    TTURLRequest *_syncingRequest;
    NSMutableArray *_favIDsToAdd;
    NSMutableArray *_favIDsToDelete;
}

+ (id)commentDigTableNameForComment:(id)arg1;
+ (id)digTableNameForWeibo:(id)arg1;
+ (id)favoriteTableCreateSQLForType:(int)arg1;
+ (id)favoriteTableNameForType:(int)arg1;
+ (id)postHistoryTableNameForType:(int)arg1;
+ (id)searchHistoryTableNameForType:(int)arg1;
+ (id)sharedManager;
+ (id)userDBFilePath;
- (void).cxx_destruct;
- (void)__downloadFavorites;
- (void)__uploadFavorites;
- (id)accessTokenForUid:(id)arg1;
- (_Bool)addAlbum:(id)arg1;
- (_Bool)addContributeHistoryWithType:(int)arg1 pid:(long long)arg2 title:(id)arg3 picURL:(id)arg4 vsourceURL:(id)arg5;
- (_Bool)addDigWithType:(int)arg1 forAlbum:(id)arg2;
- (_Bool)addDigWithType:(int)arg1 forComment:(id)arg2;
- (_Bool)addDigWithType:(int)arg1 forWeibo:(id)arg2;
- (_Bool)addEmoticonWithText:(id)arg1 filename:(id)arg2;
- (_Bool)addPhotoUploadHistoryWithTitle:(id)arg1 picURL:(id)arg2;
- (_Bool)addSearchHistoryWithType:(int)arg1 keyword:(id)arg2;
- (_Bool)addWeibo:(id)arg1;
- (id)albumsWithType:(int)arg1 ofSize:(unsigned long long)arg2 maxTime:(id)arg3;
- (_Bool)canContributeForType:(int)arg1;
- (_Bool)canEmitEmojiRainForWeibo:(id)arg1;
- (_Bool)canSearchForType:(int)arg1;
- (_Bool)canSync;
- (_Bool)canSyncMoreForType:(int)arg1 lastTimestamp:(double)arg2;
- (_Bool)canUploadPhoto;
- (void)createTables;
- (_Bool)deleteAlbum:(id)arg1;
- (_Bool)deleteWeibo:(id)arg1;
- (int)digTypeForAlbum:(id)arg1;
- (int)digTypeForComment:(id)arg1;
- (int)digTypeForWeibo:(id)arg1;
- (void)downloadFavorites:(int)arg1;
- (id)emoticonFilename:(id)arg1;
- (id)getDatabase;
- (id)init;
- (void)initFavSyncStatusTable;
- (long long)integerForSyncKey:(id)arg1 weiboType:(int)arg2;
- (_Bool)isAlbumReadWithId:(id)arg1;
- (_Bool)isAlbumSeriesSubscribedWithId:(id)arg1;
- (_Bool)isDatabaseUpgradeSuccess;
- (_Bool)isFavoritedForAlbum:(id)arg1;
- (_Bool)isFavoritedForWeibo:(id)arg1;
- (_Bool)isNullForSyncKey:(id)arg1 weiboType:(int)arg2;
- (_Bool)isPublicMsgReadWithId:(id)arg1;
- (_Bool)isUIDFieldInTableWithType:(int)arg1;
- (_Bool)isVideoReadWithId:(id)arg1 source:(int)arg2;
- (long long)lastReadPageForAlbumID:(id)arg1;
- (double)lastReadPositionForAlbumID:(id)arg1;
- (id)lastSessionIdForPlatform:(id)arg1 platformUid:(id)arg2;
- (id)lastSessionIdForUid:(id)arg1;
- (id)maxFavoritedTimeForType:(int)arg1;
- (id)minFavoritedTimeForType:(int)arg1;
- (void)recreateFavTableForType:(int)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
- (_Bool)saveLastReadPage:(long long)arg1 position:(double)arg2 total:(long long)arg3 forAlbumID:(id)arg4;
- (_Bool)setAlbumReadWithId:(id)arg1;
- (void)setEmittedEmojiRainForWeibo:(id)arg1 emoji:(id)arg2;
- (void)setInteger:(long long)arg1 forSyncKey:(id)arg2;
- (void)setNullForSyncKey:(id)arg1;
- (_Bool)setPublicMsgReadWithId:(id)arg1;
- (_Bool)setSessionId:(id)arg1 accessToken:(id)arg2 forUid:(id)arg3 platform:(id)arg4 platformUid:(id)arg5;
- (void)setUid:(id)arg1;
- (_Bool)setVideoReadWithId:(id)arg1 source:(int)arg2;
- (void)stopSyncingFavorites;
- (_Bool)subscribeAlbumSeriesWithId:(id)arg1;
- (id)syncDeviceID;
- (void)syncFavorites:(_Bool)arg1;
- (void)syncStateChanged:(_Bool)arg1;
@property(readonly, nonatomic) _Bool syncingFavorites; // @synthesize syncingFavorites=_syncingFavorites;
- (_Bool)unsubscribeAlbumSeriesWithId:(id)arg1;
- (_Bool)upgradeFavTablesAndTransferData;
- (void)uploadFavorites;
- (_Bool)usedEmoticonWithText:(id)arg1;
- (id)usedEmoticons;
- (long long)weiboCountForAlbumID:(id)arg1;
- (id)weibosWithType:(int)arg1 minDate:(id)arg2 maxDate:(id)arg3 keyword:(id)arg4 ofSize:(unsigned long long)arg5 maxTime:(id)arg6;

@end

