//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RennParam.h"

@class NSString;

@interface GetNewsCountParam : RennParam
{
    NSString *_newTypes;
}

- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSString *newTypes; // @synthesize newTypes=_newTypes;

@end

