//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriter;

__attribute__((visibility("hidden")))
@interface GIFConverter : NSObject
{
    AVAssetWriter *_videoWriter;
}

- (void).cxx_destruct;
- (void)convertGIFToMP4:(id)arg1 speed:(float)arg2 size:(struct CGSize)arg3 repeat:(int)arg4 output:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (id)init;
- (id)loadGIFData:(id)arg1 resize:(struct CGSize)arg2 repeat:(int)arg3;
- (struct __CVBuffer *)pixelBufferFromCGImage:(struct CGImage *)arg1 size:(struct CGSize)arg2;
@property(retain, nonatomic) AVAssetWriter *videoWriter; // @synthesize videoWriter=_videoWriter;

@end

