//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMAdUnitDelegate.h"
#import "IMConfigDelegate.h"

@class IMAdsConfig, NSMutableArray, NSString;

@interface IMAdUnitCache : NSObject <IMAdUnitDelegate, IMConfigDelegate>
{
    NSMutableArray *_preloadedAdUnits;
    IMAdsConfig *_config;
}

+ (id)sharedCache;
- (void).cxx_destruct;
@property(retain, nonatomic) IMAdsConfig *config; // @synthesize config=_config;
- (void)configUpdated:(id)arg1;
- (id)getAdPoolForPlacementID:(long long)arg1 ofAdType:(id)arg2;
- (id)init;
- (_Bool)isPreloadEnabled:(id)arg1;
- (void)preloadAdUnits;
@property(retain, nonatomic) NSMutableArray *preloadedAdUnits; // @synthesize preloadedAdUnits=_preloadedAdUnits;
- (void)start;
- (void)stop;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

