//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

@class NSNumber;

@interface IMAdsConfigBitRate : IMJSONModel
{
    _Bool _bitrate_mandatory;
    NSNumber *_headerTimeout;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bitrate_mandatory; // @synthesize bitrate_mandatory=_bitrate_mandatory;
@property(retain, nonatomic) NSNumber *headerTimeout; // @synthesize headerTimeout=_headerTimeout;
- (id)init;
- (_Bool)validate:(id *)arg1;

@end

