//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMAdUnitDelegate.h"
#import "IMConfigDelegate.h"

@class IMAdsConfig, NSDictionary, NSMutableArray, NSString, NSTimer;

@interface IMAdPool : NSObject <IMAdUnitDelegate, IMConfigDelegate>
{
    _Bool _shouldHandoverAdUnitsInProgress;
    long long _placementID;
    NSMutableArray *_adUnitArray;
    long long _maxAdLimit;
    IMAdsConfig *_config;
    NSTimer *_expiryTimer;
    NSString *_lastAdContext;
    NSDictionary *_extras;
    NSString *_keywords;
    NSMutableArray *_delegateArray;
}

+ (id)getSharedAdPoolForPlacementID:(long long)arg1;
- (void).cxx_destruct;
- (void)ad:(id)arg1 didFailToLoadWithErrorCode:(int)arg2 andDescription:(id)arg3;
- (void)adDidFinishLoad:(id)arg1;
- (void)adIsAvailable:(id)arg1;
@property(retain, nonatomic) NSMutableArray *adUnitArray; // @synthesize adUnitArray=_adUnitArray;
- (_Bool)addDelegatetoDelegateArray:(id)arg1;
- (void)broadcastAdReceivedCallback;
- (void)broadcastFailureCallbackWithErrorCode:(int)arg1 andDescription:(id)arg2;
- (void)broadcastSuccessCallback;
- (void)cleanUpDelegateArray;
- (void)cleanupExpiredAds;
@property(retain, nonatomic) IMAdsConfig *config; // @synthesize config=_config;
- (void)configUpdated:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSMutableArray *delegateArray; // @synthesize delegateArray=_delegateArray;
- (void)deregisterForAd:(id)arg1;
@property(retain, nonatomic) NSTimer *expiryTimer; // @synthesize expiryTimer=_expiryTimer;
@property(retain, nonatomic) NSDictionary *extras; // @synthesize extras=_extras;
- (id)getAdForShow;
- (id)getAdUnitForPlacementID:(long long)arg1;
- (void)gotLowMemoryWarning;
- (id)initWithPlacementID:(long long)arg1;
- (_Bool)isAdContainedInAdUnitArray:(id)arg1;
- (_Bool)isAnyAdReceived;
- (_Bool)isAnyAdinProgress;
- (_Bool)isReadyAdAvailable;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSString *lastAdContext; // @synthesize lastAdContext=_lastAdContext;
- (void)loadAdAndAddAdUnitDataArrayForPreload:(long long)arg1;
@property(nonatomic) long long maxAdLimit; // @synthesize maxAdLimit=_maxAdLimit;
@property(nonatomic) long long placementID; // @synthesize placementID=_placementID;
- (void)registerForAdWithDelegate:(id)arg1;
- (void)removeAdUnitFromPool:(id)arg1;
- (void)scheduleExpiryTimer;
- (void)sendFailureToFirstObjectWithErrorCode:(int)arg1 andDescription:(id)arg2;
- (void)sendSuccessToFirstObject;
@property(nonatomic) _Bool shouldHandoverAdUnitsInProgress; // @synthesize shouldHandoverAdUnitsInProgress=_shouldHandoverAdUnitsInProgress;
- (id)telemetryPayload;
- (long long)totalNumberOfReadyAdsAvailable;
- (long long)totalNumberOfReceivedAd;
- (long long)totalNumberOfValidAdsAvailable;
- (long long)totalRegisteredObjects;
- (void)warmCache;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

