//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface ImageTextInstlView : UIView
{
    UIView *titleView;
    UIImageView *icon;
    UILabel *mainTitle;
    UILabel *subTitle;
    UILabel *mesLabel;
    UIButton *downLoadBtn;
    struct CGSize toSize;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) UIButton *downLoadBtn; // @synthesize downLoadBtn;
- (void)drawRect:(struct CGRect)arg1;
- (id)hexStringToColor:(id)arg1;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon;
- (id)initWithIconImage:(id)arg1 Title:(id)arg2 subTitle:(id)arg3 message:(id)arg4 actinonType:(int)arg5 delegate:(id)arg6;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *mainTitle; // @synthesize mainTitle;
@property(retain, nonatomic) UILabel *mesLabel; // @synthesize mesLabel;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView;
@property(nonatomic) struct CGSize toSize; // @synthesize toSize;

@end

