//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMAsset, IMNativeVideoProperties, IMRenderView, IMRenderViewController, IMVideoAssetMetaData, NSArray, NSData, NSDictionary, NSObject, NSString, UIView;

@protocol IMAssetActionDelegate <NSObject>
- (NSString *)fetchAdUnitType;

@optional
- (void)asset:(IMAsset *)arg1 builtNonObstuctiveViewForVideoViewability:(UIView *)arg2;
- (void)assetClicked:(IMAsset *)arg1 withParams:(NSDictionary *)arg2;
- (void)assetVisibleOnScreen:(IMAsset *)arg1;
- (void)countdownTimerFireAction:(NSString *)arg1;
- (NSString *)fetchAdBlobForWebView;
- (void)fireCloseActionFromWebView;
- (void)fireGenericEventUrl:(NSString *)arg1 forAsset:(IMAsset *)arg2;
- (void)fireShowEndCardFromWebView;
- (void)fireSkipActionFromWebView;
- (void)fireWebViewDidDismissScreen:(IMRenderView *)arg1;
- (void)fireWebViewDidInteractWithParams:(NSDictionary *)arg1;
- (void)fireWebViewDidPresentScreen:(IMRenderViewController *)arg1;
- (void)fireWebViewWillDismissScreen:(IMRenderView *)arg1;
- (void)fireWebViewWillLeaveApplication;
- (void)fireWebViewWillPresentScreen:(IMRenderViewController *)arg1;
- (void)imActionFoundCompanionExtensionTrackers:(NSArray *)arg1;
- (void)imActionFoundSKStoreWithID:(NSString *)arg1;
- (void)imActionFoundVastAds:(NSData *)arg1;
- (IMAsset *)imActionGetAssetWithID:(NSString *)arg1;
- (NSObject *)imActionGetNotificationSender;
- (NSData *)imActionGetVastTagIfAvailable;
- (IMVideoAssetMetaData *)imActionGetVideoMetadataForAssetId:(NSString *)arg1;
- (_Bool)imActionIsCloseScheduled;
- (void)imActionMediaFinishedPlaying:(IMAsset *)arg1;
- (double)imActionMinimumVisiblePercentage;
- (void)imActionRewardedActionComplete;
- (_Bool)imActionShouldRequireCustomViewabilityTracker:(IMAsset *)arg1;
- (_Bool)imActionShouldScrollToTopForRoot:(IMAsset *)arg1;
- (void)imActionShowVideoEndCardForAsset:(IMAsset *)arg1;
- (void)imActionTrackVideoViewabilityForAsset:(IMAsset *)arg1;
- (void)imActionVideoCompletedQuartile:(long long)arg1 forVideoAssetId:(NSString *)arg2;
- (void)imActionVideoSkipped;
- (IMNativeVideoProperties *)imAssetActionRequireVideoPropertiesWithRoot:(IMAsset *)arg1;
- (_Bool)saveAdBlobFromWebView:(NSString *)arg1;
@end

