//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMAssetCacheDAO : NSObject
{
}

- (id)createRetryTableQuery;
- (_Bool)createTable;
- (id)createTableQuery;
- (void)deleteRetries;
- (id)deleteRetriesQuery;
- (id)deleteTupleFromTable:(id)arg1 withHash:(id)arg2;
- (void)deleteTuplesFromTable:(id)arg1 forKeys:(id)arg2;
- (id)deleteTuplesQueryFromTable:(id)arg1 forKeys:(id)arg2;
- (id)expiredAds;
- (id)getExpiredAdsQuery;
- (id)init;
- (void)insertIntoRetryTable:(id)arg1;
- (void)insertQuery:(id)arg1;
- (void)insertToTableHash:(id)arg1 withName:(id)arg2 timestamp:(double)arg3 expiry:(double)arg4 staleWhileRevalidate:(double)arg5;
- (id)queryToGetAllHashValuesStored;
- (id)queryToInsertIntoTableHash:(id)arg1 withName:(id)arg2 timestamp:(double)arg3 expiry:(double)arg4 staleWhileRevalidate:(double)arg5;
- (id)queryToInsertIntoTableforKey:(id)arg1;
- (id)queryToResetExpiryOfAssetWithKey:(id)arg1;
- (id)queryToUpdateTableNoOfTries:(long long)arg1 forKey:(id)arg2;
- (id)queryToUpdateTimeStampOfAssetForKey:(id)arg1;
- (void)resetExpiryForKey:(id)arg1;
- (id)selectTupleFromTable:(id)arg1 withHash:(id)arg2;
- (id)selectTuplesInAscendingOrderOfExpiry;
- (id)selectTuplesInAscendingOrderOfTimestamp;
- (id)tupleFromTable:(id)arg1 withHash:(id)arg2;
- (id)tuplesForQuery:(id)arg1;
- (id)tuplesInAscendingOrderOfExpiry;
- (id)tuplesInAscendingOrderOfTimestamp;
- (id)tuplesWithAllHashValues;
- (void)updateRetryTableWithNoOfTries:(long long)arg1 forKey:(id)arg2;
- (void)updateTimeStampForKey:(id)arg1;

@end

