//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMConfigDelegate.h"
#import "IMNetworkDelegate.h"

@class IMAdsConfig, IMAssetCacheDAO, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface IMAssetCache : NSObject <IMNetworkDelegate, IMConfigDelegate>
{
    NSString *_assetCacheDirectory;
    double _defaultExpiry;
    double _maximumCacheSize;
    long long _maxRetries;
    NSObject<OS_dispatch_queue> *_databaseQueue;
    NSMutableArray *_pendingRequests;
    IMAssetCacheDAO *_dao;
    IMAdsConfig *_adsConfig;
    NSMutableDictionary *_refCounts;
    unsigned long long _contentLength;
}

+ (id)sharedCache;
- (void).cxx_destruct;
- (void)addRequestData:(id)arg1;
- (void)addToCacheAsset:(id)arg1 withName:(id)arg2 expiry:(double)arg3 staleWhileRevalidate:(double)arg4;
- (void)addToTableNoOfTries:(long long)arg1 forKey:(id)arg2;
@property(retain, nonatomic) IMAdsConfig *adsConfig; // @synthesize adsConfig=_adsConfig;
@property(retain, nonatomic) NSString *assetCacheDirectory; // @synthesize assetCacheDirectory=_assetCacheDirectory;
- (double)cacheSize;
- (_Bool)checkIfFilePresentInCache:(id)arg1;
- (void)cleanupExpiredAssets;
- (void)cleanupRetries;
- (void)clearupCacheToMakeSize;
- (void)configUpdated:(id)arg1;
@property(nonatomic) unsigned long long contentLength; // @synthesize contentLength=_contentLength;
- (id)createHashForString:(id)arg1;
@property(retain, nonatomic) IMAssetCacheDAO *dao; // @synthesize dao=_dao;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *databaseQueue; // @synthesize databaseQueue=_databaseQueue;
@property(nonatomic) double defaultExpiry; // @synthesize defaultExpiry=_defaultExpiry;
- (_Bool)deleteAssetAtPath:(id)arg1;
- (void)deleteAssetForUrl:(id)arg1;
- (void)downloadAsset:(id)arg1 ofFileType:(id)arg2 forAllowedContentType:(id)arg3 withDelegate:(id)arg4;
- (void)downloadAsset:(id)arg1 ofFileType:(id)arg2 forContentTyep:(id)arg3;
- (id)extractCacheControlHeader:(id)arg1;
- (void)fileDownloadFailed:(id)arg1 ofFileType:(id)arg2 forURL:(id)arg3 forAllowedContentType:(id)arg4 withError:(id)arg5 shouldRetry:(_Bool)arg6;
- (void)fileDownloadSucceeded:(id)arg1 withName:(id)arg2 withExpiry:(double)arg3 staleWhileRevalidate:(double)arg4 forURL:(id)arg5;
- (id)fileExtensionFromFileType:(id)arg1;
- (id)getCachedFileHash;
- (double)getDirectorySize:(id)arg1;
- (_Bool)hasCacheForKey:(id)arg1 inTable:(id)arg2;
- (id)init;
- (_Bool)isBeingUsed:(id)arg1;
@property(nonatomic) long long maxRetries; // @synthesize maxRetries=_maxRetries;
@property(nonatomic) double maximumCacheSize; // @synthesize maximumCacheSize=_maximumCacheSize;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetHeaders:(id)arg3;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
@property(retain, nonatomic) NSMutableArray *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
@property(retain, nonatomic) NSMutableDictionary *refCounts; // @synthesize refCounts=_refCounts;
- (void)removeAssetFromCache:(id)arg1 atPath:(id)arg2;
- (void)removeLRUAssetsForSize:(double)arg1;
- (void)removeRequestDataFromPendingRequests:(id)arg1;
- (id)requestDataForHashString:(id)arg1;
- (id)requestDataForNsp:(id)arg1;
- (_Bool)saveFileContent:(id)arg1 atPath:(id)arg2;
- (void)sendCallbackForFileDownloadSucceededForAsset:(id)arg1 toPath:(id)arg2 forURL:(id)arg3;
- (void)sendCallbackForFileFetchFromCacheSucceededForAsset:(id)arg1 toPath:(id)arg2 forURL:(id)arg3;
- (void)sendSuccessCallbackForAsset:(id)arg1 toPath:(id)arg2 forURL:(id)arg3 withBlock:(CDUnknownBlockType)arg4;
- (void)start;
- (void)stop;
- (double)timeIntervalFromDateString:(id)arg1;
- (id)tupleForKey:(id)arg1 fromTable:(id)arg2;
- (void)unuseURL:(id)arg1 withUserId:(id)arg2;
- (void)updateDefaults;
- (void)useURL:(id)arg1 withUserId:(id)arg2;
- (_Bool)validateContentLength:(long long)arg1;
- (_Bool)validateContentType:(id)arg1 forAllowedContentType:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

