//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, IMAdCloseButton, IMRenderView, IMUISlider, NSString, UIView;

@interface IMAVPlayer : NSObject
{
    _Bool _notificationsRegistered;
    _Bool _frameObserverAdded;
    _Bool _statusObserverAdded;
    id <IMAVPlayerDelegate> _delegate;
    NSString *_mediaURL;
    AVPlayer *_player;
    AVPlayerItem *_playerItem;
    UIView *_playerView;
    UIView *_parentView;
    IMRenderView *_renderView;
    AVPlayerLayer *_layer;
    IMAdCloseButton *_closeButton;
    IMUISlider *_progressSlider;
    id _timeObserver;
    struct CGRect _mediaFrame;
}

- (void).cxx_destruct;
- (void)addCloseButtonToMediaPlayer;
- (void)addPlayerToView;
- (void)addSeekBarToMediaPlayer;
- (void)appBecameActive;
- (void)appBecameInactive;
- (void)close;
@property(retain, nonatomic) IMAdCloseButton *closeButton; // @synthesize closeButton=_closeButton;
- (void)closeButtonAction;
- (void)dealloc;
- (void)deinit;
@property(nonatomic) __weak id <IMAVPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deregisterNotifications;
@property(nonatomic) _Bool frameObserverAdded; // @synthesize frameObserverAdded=_frameObserverAdded;
- (struct CGRect)getFullScreenBounds;
- (id)getParentViewForPlayer;
- (id)getRenderView;
- (id)initWithMediaURL:(id)arg1 delegate:(id)arg2 renderView:(id)arg3;
@property(retain, nonatomic) AVPlayerLayer *layer; // @synthesize layer=_layer;
- (void)mediaEndNotification:(id)arg1;
@property(nonatomic) struct CGRect mediaFrame; // @synthesize mediaFrame=_mediaFrame;
@property(retain, nonatomic) NSString *mediaURL; // @synthesize mediaURL=_mediaURL;
@property(nonatomic) _Bool notificationsRegistered; // @synthesize notificationsRegistered=_notificationsRegistered;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView=_parentView;
- (void)play;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) UIView *playerView; // @synthesize playerView=_playerView;
- (void)prepareAndPlayMedia;
@property(retain, nonatomic) IMUISlider *progressSlider; // @synthesize progressSlider=_progressSlider;
- (void)readyToPlay;
- (void)refreshPlayerControls;
- (void)registerNotifications;
- (void)removeAllControls;
- (void)removePlayerTimeObserver;
@property(nonatomic) __weak IMRenderView *renderView; // @synthesize renderView=_renderView;
@property(nonatomic) _Bool statusObserverAdded; // @synthesize statusObserverAdded=_statusObserverAdded;
@property(retain, nonatomic) id timeObserver; // @synthesize timeObserver=_timeObserver;

@end

