//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMContainerAsset.h"

#import "IMUICollectionViewSliderLayoutDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSMutableArray, NSString;

@interface IMCardScrollableAsset : IMContainerAsset <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, IMUICollectionViewSliderLayoutDelegate>
{
    NSMutableArray *_buildingAssets;
    long long _currentIndex;
    unsigned long long _transitionEffect;
    long long _noOfCellsInCollView;
    double _scale;
}

- (void).cxx_destruct;
- (void)assetDidFinishBuilding:(id)arg1;
- (void)assetFailedToBuild:(id)arg1;
- (id)buildAssetViewWithScale:(double)arg1;
@property(retain, nonatomic) NSMutableArray *buildingAssets; // @synthesize buildingAssets=_buildingAssets;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)createViewWithProperties:(id)arg1;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
- (void)fetchAssetResources;
- (void)handleViewableAsset:(id)arg1;
- (void)imUICollectionViewSliderLayoutCurrentPage:(long long)arg1;
@property(nonatomic) long long noOfCellsInCollView; // @synthesize noOfCellsInCollView=_noOfCellsInCollView;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)prepareChildAsset:(id)arg1;
- (id)propertiesFromJson:(id)arg1;
- (void)recycleView;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(nonatomic) unsigned long long transitionEffect; // @synthesize transitionEffect=_transitionEffect;
- (void)updateItemsInCollectionViewWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)updatePropertiesOnView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

