//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMAsset.h"

#import "IMAssetBuilderDelegate.h"
#import "IMTimerDelegate.h"

@class IMTimerManager, NSArray, NSMutableArray, NSString;

@interface IMContainerAsset : IMAsset <IMTimerDelegate, IMAssetBuilderDelegate>
{
    _Bool _preloadWebviews;
    NSMutableArray *_assets;
    NSMutableArray *_builtAssets;
    NSArray *_assetOrderReference;
    IMTimerManager *_timerManager;
    double _prevPercentage;
}

- (void).cxx_destruct;
- (void)assetDidFinishBuilding:(id)arg1;
- (void)assetFailedToBuild:(id)arg1;
@property(retain, nonatomic) NSArray *assetOrderReference; // @synthesize assetOrderReference=_assetOrderReference;
@property(retain, nonatomic) NSMutableArray *assets; // @synthesize assets=_assets;
- (id)buildAssetViewWithScale:(double)arg1;
@property(retain, nonatomic) NSMutableArray *builtAssets; // @synthesize builtAssets=_builtAssets;
- (id)createViewWithProperties:(id)arg1;
- (void)dealloc;
- (void)fetchAssetResources;
- (id)getAllTrackersOfType:(id)arg1;
- (id)initWithJson:(id)arg1 withStyles:(id)arg2 atJPath:(id)arg3;
- (id)jPathForChildWithJson:(id)arg1 atIndex:(int)arg2;
@property(nonatomic) _Bool preloadWebviews; // @synthesize preloadWebviews=_preloadWebviews;
- (void)prepareChildAsset:(id)arg1;
@property(nonatomic) double prevPercentage; // @synthesize prevPercentage=_prevPercentage;
- (void)recycleView;
- (void)screenDismissed;
- (void)screenPresented;
- (void)setShowTimeStampForAsset:(unsigned long long)arg1;
@property(retain, nonatomic) IMTimerManager *timerManager; // @synthesize timerManager=_timerManager;
- (void)startAnimating;
- (void)timerHitForManager:(id)arg1;
- (void)updatePropertiesOnView;
- (void)viewVisibilityComputedAs:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

