//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMJSONModel.h"

#import "IMConfig.h"

@class IMTelemetryComponentConfigs<IMOptional>, NSMutableDictionary, NSString;

@interface IMConfig : IMJSONModel <IMConfig>
{
    NSMutableDictionary *_includeIds;
    IMTelemetryComponentConfigs<IMOptional> *_componentConfigs;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IMTelemetryComponentConfigs<IMOptional> *componentConfigs; // @synthesize componentConfigs=_componentConfigs;
- (id)getType;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSMutableDictionary *includeIds; // @synthesize includeIds=_includeIds;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isValid;
- (id)newInstance;
- (_Bool)updatefromDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

