//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMRequest.h"

@class NSMutableDictionary, NSString;

@interface IMConfigNetworkRequest : IMRequest
{
    long long _maxRetries;
    NSMutableDictionary *_requestedConfig;
    long long _requestState;
    NSString *_fallbackUrl;
}

- (void).cxx_destruct;
- (id)configPayload;
@property(retain, nonatomic) NSString *fallbackUrl; // @synthesize fallbackUrl=_fallbackUrl;
- (id)initWithURL:(id)arg1 requestedConfig:(id)arg2 maxRetries:(long long)arg3 retryInterval:(long long)arg4;
@property(nonatomic) long long maxRetries; // @synthesize maxRetries=_maxRetries;
- (void)removeConfigFromRequestedMap:(id)arg1;
@property(nonatomic) long long requestState; // @synthesize requestState=_requestState;
- (id)requestURL;
@property(retain, nonatomic) NSMutableDictionary *requestedConfig; // @synthesize requestedConfig=_requestedConfig;

// Remaining properties
@property(nonatomic) long long retryInterval;

@end

