//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMNetworkDelegate.h"

@class IMConfigNetworkRequest, IMNetworkServiceProvider, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface IMConfigNetworkInterface : NSObject <IMNetworkDelegate>
{
    id <IMConfigNetworkDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_serialQueue;
    NSObject<OS_dispatch_source> *_timer;
    IMNetworkServiceProvider *_nsp;
    long long _retryCount;
    long long _maxRetry;
    long long _retryInterval;
    IMConfigNetworkRequest *_request;
    unsigned long long _startTime;
}

- (void).cxx_destruct;
- (void)cancelTimer;
@property(nonatomic) __weak id <IMConfigNetworkDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithConfigRequest:(id)arg1;
- (_Bool)isNetworkError:(id)arg1;
@property(nonatomic) long long maxRetry; // @synthesize maxRetry=_maxRetry;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
@property(retain, nonatomic) IMNetworkServiceProvider *nsp; // @synthesize nsp=_nsp;
- (void)process;
- (void)processFailedResponse:(id)arg1 shouldProcessRoot:(_Bool)arg2;
- (void)processSuccessResponse:(id)arg1 forRequest:(id)arg2;
@property(retain, nonatomic) IMConfigNetworkRequest *request; // @synthesize request=_request;
- (_Bool)requestContainsRootConfig:(id)arg1;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) long long retryInterval; // @synthesize retryInterval=_retryInterval;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void)stopProcessing;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

