//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMConfig;

@interface IMConfigResponseContent : NSObject
{
    _Bool _error;
    int _statusCode;
    IMConfig *_config;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IMConfig *config; // @synthesize config=_config;
@property(nonatomic) _Bool error; // @synthesize error=_error;
- (id)initWithConfigDictionary:(id)arg1 validConfig:(id)arg2;
@property(nonatomic) int statusCode; // @synthesize statusCode=_statusCode;
- (void)validateConfigResponseAndUpdateConfig:(id)arg1;

@end

