//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface IMGIFImage : UIImage
{
    NSObject<OS_dispatch_queue> *readFrameQueue;
    struct CGImageSource *_imageSourceRef;
    double _scale;
    NSMutableArray *images;
    double *_frameDurations;
    double _totalDuration;
    unsigned long long _loopCount;
    struct CGImageSource *_incrementalSource;
}

+ (id)imageNamed:(id)arg1;
+ (id)imageWithContentsOfFile:(id)arg1;
+ (id)imageWithData:(id)arg1;
+ (id)imageWithData:(id)arg1 scale:(double)arg2;
- (void).cxx_destruct;
- (struct CGImage *)CGImage;
- (void)dealloc;
- (double)duration;
@property(nonatomic) double *frameDurations; // @synthesize frameDurations=_frameDurations;
- (id)getFrameWithIndex:(unsigned long long)arg1;
- (long long)imageOrientation;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images;
@property(nonatomic) struct CGImageSource *incrementalSource; // @synthesize incrementalSource=_incrementalSource;
- (id)initWithCGImageSource:(struct CGImageSource *)arg1 scale:(double)arg2;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithData:(id)arg1 scale:(double)arg2;
@property(nonatomic) unsigned long long loopCount; // @synthesize loopCount=_loopCount;
- (double)scale;
@property(nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
- (struct CGSize)size;

@end

