//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMNetworkDelegate.h"

@class IMHealthReportingConfig, IMHealthReportingDao, IMNetworkServiceProvider, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString;

@interface IMHealthReportingManager : NSObject <IMNetworkDelegate>
{
    _Bool _requestInProgress;
    IMHealthReportingConfig *_configData;
    id <IMHealthReportingDelegate> _delegate;
    IMNetworkServiceProvider *_nsp;
    IMHealthReportingDao *_dao;
    NSObject<OS_dispatch_queue> *_dBQueue;
    NSObject<OS_dispatch_source> *_timer;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

+ (_Bool)isAppRunningOnWifi;
- (void).cxx_destruct;
- (void)cancelTimer;
- (_Bool)checkBatchSizeAndTransmit;
- (_Bool)checkEventDict:(id)arg1 forInjestionLatency:(long long)arg2;
- (void)checkLastTransmitionTimeAndSetIfNotPresent;
- (_Bool)checkPreviousTransmissionAndSendEvents;
- (void)checkProcessingIntervalAndTransmit;
@property(retain, nonatomic) IMHealthReportingConfig *configData; // @synthesize configData=_configData;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dBQueue; // @synthesize dBQueue=_dBQueue;
@property(retain, nonatomic) IMHealthReportingDao *dao; // @synthesize dao=_dao;
@property(nonatomic) __weak id <IMHealthReportingDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getValueFromUserDefaults:(id)arg1;
- (id)initWithConfigData:(id)arg1 forDao:(id)arg2;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
@property(retain, nonatomic) IMNetworkServiceProvider *nsp; // @synthesize nsp=_nsp;
@property _Bool requestInProgress; // @synthesize requestInProgress=_requestInProgress;
- (void)saveTimeForTransmissionSuccess;
- (_Bool)sendToserver:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
- (void)setValueInUserDefaults:(id)arg1 forKey:(id)arg2;
- (void)startComponent;
- (void)stopComponent;
- (_Bool)transmitBatchRequest:(id)arg1 forAdType:(id)arg2;
- (void)updateTimerWithProcessingIntrval:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

