//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IMKeyValueStore : NSObject
{
    NSString *_storeDomain;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)arrayForKey:(id)arg1;
- (_Bool)boolForKey:(id)arg1;
- (id)dataForKey:(id)arg1;
- (id)dateForKey:(id)arg1;
- (void)dealloc;
- (id)dictionaryForKey:(id)arg1;
- (id)generateKeyFor:(id)arg1;
- (id)getObjectForKey:(id)arg1;
- (id)initWithDomain:(id)arg1;
- (id)numberForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)setArray:(id)arg1 forKey:(id)arg2;
- (void)setBool:(_Bool)arg1 forKey:(id)arg2;
- (void)setData:(id)arg1 forKey:(id)arg2;
- (void)setDate:(id)arg1 forKey:(id)arg2;
- (void)setDictionary:(id)arg1 forKey:(id)arg2;
- (id)setForKey:(id)arg1;
- (void)setNumber:(id)arg1 forKey:(id)arg2;
- (void)setSet:(id)arg1 forKey:(id)arg2;
@property(retain, nonatomic) NSString *storeDomain; // @synthesize storeDomain=_storeDomain;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (_Bool)sync;

@end

