//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMAVPlayerDelegate.h"

@class IMAVPlayer, IMRenderView;

@interface IMMediaManager : NSObject <IMAVPlayerDelegate>
{
    id <IMMediaManagerDelegate> _delegate;
    IMAVPlayer *_imavPlayer;
    IMRenderView *_renderView;
}

- (void).cxx_destruct;
- (id)avVideoView;
- (void)closeAllMedia;
- (void)dealloc;
@property(nonatomic) __weak id <IMMediaManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IMAVPlayer *imavPlayer; // @synthesize imavPlayer=_imavPlayer;
- (id)initWithDelegate:(id)arg1;
- (void)playVideo:(id)arg1;
- (void)playVideoWithParams:(id)arg1 inRenderView:(id)arg2 withScheme:(id)arg3;
@property(nonatomic) __weak IMRenderView *renderView; // @synthesize renderView=_renderView;

@end

