//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMSDKGeoLocationManager, IMSignalsConfig, NSMutableArray, NSOperationQueue, NSString;

@interface IMNice : NSObject
{
    _Bool _started;
    IMSignalsConfig *_config;
    NSMutableArray *_wifiData;
    NSOperationQueue *_collectionQueue;
    NSOperationQueue *_networkQueue;
    IMSDKGeoLocationManager *_locationManager;
    NSString *_sessionId;
    double _sessionStartTime;
    double _sessionEndTime;
    unsigned long long _identifier;
}

+ (_Bool)cellularInfoEnabled;
+ (_Bool)iCEEnabled;
+ (_Bool)locationEnabled;
+ (id)sharedInstance;
+ (_Bool)wifiEnabled;
- (void).cxx_destruct;
- (void)clearSessionInfo;
- (void)collectWifiInfo;
@property(retain, nonatomic) NSOperationQueue *collectionQueue; // @synthesize collectionQueue=_collectionQueue;
@property(retain, nonatomic) IMSignalsConfig *config; // @synthesize config=_config;
@property(nonatomic) unsigned long long identifier; // @synthesize identifier=_identifier;
- (id)init;
@property(retain, nonatomic) IMSDKGeoLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSOperationQueue *networkQueue; // @synthesize networkQueue=_networkQueue;
- (id)nicePayload;
- (void)sendNiceRequest;
@property(nonatomic) double sessionEndTime; // @synthesize sessionEndTime=_sessionEndTime;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) double sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property(nonatomic) _Bool started; // @synthesize started=_started;
@property(retain, nonatomic) NSMutableArray *wifiData; // @synthesize wifiData=_wifiData;
- (void)start;
- (void)startSession;
- (void)startWifi;
- (void)stop;
- (void)stopNiceOperations;
- (void)stopSession;
- (void)stopWifi;

@end

