//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMOBFDataModel.h"

@class NSArray, NSDate, NSDictionary, NSString;

@protocol IMOBFSocialUser <IMOBFDataModel>
@property(copy, nonatomic) NSString *aboutMe;
@property(retain, nonatomic) NSDate *birthday;
@property(retain, nonatomic) NSArray *educations;
@property(nonatomic) long long followerCount;
@property(nonatomic) long long friendCount;
@property(nonatomic) long long gender;
@property(copy, nonatomic) NSString *icon;
@property(nonatomic) long long level;
@property(copy, nonatomic) NSString *nickname;
@property(nonatomic) long long platformType;
@property(retain, nonatomic) NSDictionary *rawData;
@property(nonatomic) double regAt;
@property(nonatomic) long long shareCount;
@property(copy, nonatomic) NSString *uid;
@property(copy, nonatomic) NSString *url;
@property(copy, nonatomic) NSString *verifyReason;
@property(nonatomic) long long verifyType;
@property(retain, nonatomic) NSArray *works;
@end

