//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMOBFDataModel.h"

@class NSArray, NSDictionary, NSString;

@protocol IMOBFContentEntity <IMOBFDataModel>
@property(copy, nonatomic) NSString *cid;
@property(retain, nonatomic) NSArray *images;
@property(retain, nonatomic) NSDictionary *rawData;
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) NSArray *urls;
@end

