//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IMOrientationProperties : NSObject
{
    _Bool _allowOrientationChange;
    NSString *_launchOrientation;
    NSString *_direction;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool allowOrientationChange; // @synthesize allowOrientationChange=_allowOrientationChange;
@property(retain, nonatomic) NSString *direction; // @synthesize direction=_direction;
- (void)fromDictionary:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSString *launchOrientation; // @synthesize launchOrientation=_launchOrientation;

@end

