//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMRdbmsDataStore : NSObject
{
}

+ (id)sharedDataStore;
- (_Bool)closeDataStoreConnection:(struct sqlite3 *)arg1;
- (id)columnDataForStatement:(struct sqlite3_stmt *)arg1 atIndex:(int)arg2;
- (_Bool)createDatabaseDirectory;
- (id)databasePath;
- (_Bool)executeBoolSQLSynchronously:(id)arg1 returningError:(id *)arg2;
- (_Bool)executeQuery:(id)arg1 returningError:(id *)arg2;
- (id)executeSQL:(id)arg1 withConnection:(struct sqlite3 *)arg2 returningError:(id *)arg3;
- (_Bool)executeSQLForBoolResult:(id)arg1 withConnection:(struct sqlite3 *)arg2 returningError:(id *)arg3;
- (id)executeSQLSynchronously:(id)arg1 deleteStatement:(id)arg2 returningError:(id *)arg3;
- (id)executeSQLSynchronously:(id)arg1 returningError:(id *)arg2;
- (id)fetchDBError:(struct sqlite3 *)arg1;
- (id)getRecords:(id)arg1 AndDelete:(id)arg2 returningError:(id *)arg3;
- (id)getRecords:(id)arg1 returningError:(id *)arg2;
- (id)init;
- (struct sqlite3 *)openDataStoreConnection;
- (id)rowDataForStatement:(struct sqlite3_stmt *)arg1;
- (_Bool)satisfiesPrerequisites:(id)arg1 withConnection:(struct sqlite3 *)arg2;

@end

