//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IMRenderViewDismissDelegate.h"

@class IMRenderView, NSString;

@interface IMRenderViewController : UIViewController <IMRenderViewDismissDelegate>
{
    _Bool _willDismiss;
    _Bool _shouldFitInSafeArea;
    IMRenderView *_renderView;
}

- (void).cxx_destruct;
- (unsigned long long)creativeMask;
- (void)dealloc;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)imRenderViewDismissCalled:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)imRenderViewHasPresentedScreen:(id)arg1;
- (_Bool)imRenderViewShouldFireViewableEventsForPresentationAndDismiss:(id)arg1;
- (id)initWithRenderView:(id)arg1 shouldFitInSafeAreaBounds:(_Bool)arg2 withUnsafeAreaColor:(id)arg3;
- (_Bool)loadHtmlString:(id)arg1;
- (_Bool)loadRequest:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)prefersStatusBarHidden;
- (void)presentRenderViewControllerFromParent:(id)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) IMRenderView *renderView; // @synthesize renderView=_renderView;
- (id)rootViewController;
@property(nonatomic) _Bool shouldFitInSafeArea; // @synthesize shouldFitInSafeArea=_shouldFitInSafeArea;
@property(nonatomic) _Bool willDismiss; // @synthesize willDismiss=_willDismiss;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

