//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IMResizeProperties : NSObject
{
    _Bool _allowOffScreen;
    long long _width;
    long long _height;
    long long _offsetX;
    long long _offsetY;
    NSString *_closeButtonPosition;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool allowOffScreen; // @synthesize allowOffScreen=_allowOffScreen;
@property(retain, nonatomic) NSString *closeButtonPosition; // @synthesize closeButtonPosition=_closeButtonPosition;
- (void)fromDictionary:(id)arg1;
@property(nonatomic) long long height; // @synthesize height=_height;
- (id)init;
@property(nonatomic) long long offsetX; // @synthesize offsetX=_offsetX;
@property(nonatomic) long long offsetY; // @synthesize offsetY=_offsetY;
@property(nonatomic) long long width; // @synthesize width=_width;

@end

