//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMCommProcessor, IMDeviceProcessor, IMExtrasProcessor, IMMultiMediaProcessor, IMPingProcessor, IMRenderView, IMSKStoreProcessor, IMViewProcessor;

@interface IMRichMediaResolver : NSObject
{
    IMMultiMediaProcessor *_multiMediaProcessor;
    IMRenderView *_renderView;
    IMCommProcessor *_commProcessor;
    IMDeviceProcessor *_deviceProcessor;
    IMViewProcessor *_viewProcessor;
    IMPingProcessor *_pingProcessor;
    IMExtrasProcessor *_extrasProcessor;
    IMSKStoreProcessor *_skStoreProcessor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IMCommProcessor *commProcessor; // @synthesize commProcessor=_commProcessor;
- (void)dealloc;
@property(retain, nonatomic) IMDeviceProcessor *deviceProcessor; // @synthesize deviceProcessor=_deviceProcessor;
@property(retain, nonatomic) IMExtrasProcessor *extrasProcessor; // @synthesize extrasProcessor=_extrasProcessor;
- (void)getCommProcessor;
- (void)getDeviceProcessor;
- (void)getExtrasProcessor;
- (void)getMultiMediaProcessor;
- (void)getPingProcessor;
- (void)getSkStoreProcessor;
- (void)getViewProcessor;
- (_Bool)handleCommand:(id)arg1 withParameters:(id)arg2 onScheme:(id)arg3;
- (id)initWithRenderView:(id)arg1;
@property(retain, nonatomic) IMMultiMediaProcessor *multiMediaProcessor; // @synthesize multiMediaProcessor=_multiMediaProcessor;
@property(retain, nonatomic) IMPingProcessor *pingProcessor; // @synthesize pingProcessor=_pingProcessor;
@property(nonatomic) __weak IMRenderView *renderView; // @synthesize renderView=_renderView;
@property(retain, nonatomic) IMSKStoreProcessor *skStoreProcessor; // @synthesize skStoreProcessor=_skStoreProcessor;
@property(retain, nonatomic) IMViewProcessor *viewProcessor; // @synthesize viewProcessor=_viewProcessor;

@end

