//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMConfigDelegate.h"

@class IMRootConfig, NSString;

@interface IMRootConfigManager : NSObject <IMConfigDelegate>
{
    IMRootConfig *_config;
}

+ (id)sharedConfig;
- (void).cxx_destruct;
@property(readonly, nonatomic) IMRootConfig *config; // @synthesize config=_config;
- (void)configUpdated:(id)arg1;
- (id)init;
- (void)updateConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

