//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMBaseProcessor.h"

#import "IMSKStoreProductViewControllerDelegate.h"

@class NSMutableDictionary, NSString;

@interface IMSKStoreProcessor : IMBaseProcessor <IMSKStoreProductViewControllerDelegate>
{
    _Bool _isSkStoreScreenShown;
    NSMutableDictionary *skStoreDictionary;
}

- (void).cxx_destruct;
- (void)fireSKStoreClosedWithProductID:(id)arg1 withScheme:(id)arg2;
- (void)fireSKStoreLoadedWithProductID:(id)arg1 withScheme:(id)arg2;
- (void)fireSKStoreOpenedWithProductID:(id)arg1 withScheme:(id)arg2;
- (void)imProductViewControllerDidDismissScreen:(id)arg1;
- (void)imProductViewControllerDidPresentScreen:(id)arg1;
- (void)imProductViewControllerLoadFailed:(id)arg1 error:(id)arg2;
- (void)imProductViewControllerLoadSuccessful:(id)arg1;
- (void)imProductViewControllerWillDismissScreen:(id)arg1;
- (void)imProductViewControllerWillPresentScreen:(id)arg1;
- (id)initWithRenderView:(id)arg1;
@property(nonatomic) _Bool isSkStoreScreenShown; // @synthesize isSkStoreScreenShown=_isSkStoreScreenShown;
- (void)loadSKStoreWithParams:(id)arg1 withScheme:(id)arg2;
- (void)loadSKStoreWithParams:(id)arg1 withScheme:(id)arg2 withAutoShow:(_Bool)arg3;
- (void)openSKStoreWithParams:(id)arg1 withScheme:(id)arg2;
- (void)sendTelemetryEventForEvent:(id)arg1 withProductID:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *skStoreDictionary; // @synthesize skStoreDictionary;
- (void)showSKStoreWithParams:(id)arg1 withScheme:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

