//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMConfigDelegate.h"
#import "IMHealthReportingDelegate.h"

@class IMAdsConfig, IMHealthReportingManager, IMTRCDao, NSObject<OS_dispatch_queue>, NSString;

@interface IMTRCManager : NSObject <IMConfigDelegate, IMHealthReportingDelegate>
{
    IMAdsConfig *_adsConfig;
    IMHealthReportingManager *_bannerManager;
    IMHealthReportingManager *_interstitialManager;
    IMHealthReportingManager *_nativeManager;
    IMTRCDao *_dao;
    NSObject<OS_dispatch_queue> *_dBQueue;
}

+ (id)convertObjectToDictionary:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addTRCEventToDB:(id)arg1 withConfig:(id)arg2;
@property(retain, nonatomic) IMAdsConfig *adsConfig; // @synthesize adsConfig=_adsConfig;
@property(retain, nonatomic) IMHealthReportingManager *bannerManager; // @synthesize bannerManager=_bannerManager;
- (void)checkAndStartManagerIfNotPresent:(id)arg1;
- (void)checkDBAndStartManager:(id)arg1;
- (void)configUpdated:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dBQueue; // @synthesize dBQueue=_dBQueue;
@property(retain, nonatomic) IMTRCDao *dao; // @synthesize dao=_dao;
- (id)getNetworkTypeConfig:(id)arg1;
- (id)getPollingManager:(id)arg1 andUserKey:(id)arg2;
- (id)init;
@property(retain, nonatomic) IMHealthReportingManager *interstitialManager; // @synthesize interstitialManager=_interstitialManager;
@property(retain, nonatomic) IMHealthReportingManager *nativeManager; // @synthesize nativeManager=_nativeManager;
- (id)provideNetworkRequestObject:(id)arg1 forAdType:(id)arg2;
- (void)restartPollingManagers;
- (void)startBannerManager;
- (void)startComponent;
- (void)startInterstitialManager;
- (void)startNativeManager;
- (void)stopComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

