//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMWebViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIWebView;

@interface IMUIWebViewController : IMWebViewController <UIWebViewDelegate>
{
    UIWebView *_uiWebView;
}

+ (long long)navigationTypeFrom:(long long)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (id)evaluateJavaScriptAndReturnStringIfPossible:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (long long)getWebViewType;
- (id)initWithWebViewFrame:(struct CGRect)arg1;
- (_Bool)isLoading;
- (void)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (void)loadRequest:(id)arg1;
- (_Bool)requiresVolumeUpdateBeforeShowWithPublisherMuteEnabled:(_Bool)arg1;
- (void)setAllowBounceAndScrollOnWebView:(_Bool)arg1;
@property(retain, nonatomic) UIWebView *uiWebView; // @synthesize uiWebView=_uiWebView;
- (void)stopLoading;
- (void)stringByEvaluatingJavaScriptFromString:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (id)webview;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

