//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMUIView.h"

#import "IMTimerDelegate.h"
#import "IMUIInflator.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, IMTimerManager, IMUIVideoProperties, NSArray, NSNumber, NSString, UIButton, UITapGestureRecognizer;

@interface IMUIVideoView : IMUIView <IMTimerDelegate, IMUIInflator>
{
    _Bool _isVideoPaused;
    _Bool _isFullScreen;
    _Bool _isVideoEnded;
    _Bool _touchToFullScreen;
    _Bool _autoplay;
    _Bool _playMuted;
    _Bool _autoReplay;
    _Bool _fallbackTimersRegistered;
    _Bool _rateObserverAdded;
    _Bool _fallbackTimerAdded;
    _Bool _pauseTimerAdded;
    _Bool _kvoRegistered;
    float _pauseAfter;
    id <IMUIVideoViewDelegate> _delegate;
    AVPlayerItem *_playerItem;
    NSArray *_viewabilityTimes;
    NSNumber *_isVideoMuted;
    double _playerRate;
    double _minViewablePercentage;
    double _currentViewedPercentage;
    NSNumber *_completeAfter;
    IMUIVideoProperties *_properties;
    UITapGestureRecognizer *_gestureRecognizer;
    id _boundaryObserver;
    id _viewabilityBoundaryObserver;
    id _completionBoundaryObserver;
    UIButton *_volumeCtrlButton;
    IMTimerManager *_fallbackTimer;
    IMTimerManager *_pauseTimer;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (id)addPeriodicTimeObserverForInterval:(CDStruct_1b6d18a9)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)appEnteredBackground:(id)arg1;
- (void)appEnteredForeground:(id)arg1;
- (void)audioRouteChanged:(id)arg1;
@property(nonatomic) _Bool autoReplay; // @synthesize autoReplay=_autoReplay;
@property(nonatomic) _Bool autoplay; // @synthesize autoplay=_autoplay;
@property(retain, nonatomic) id boundaryObserver; // @synthesize boundaryObserver=_boundaryObserver;
- (void)checkAndAddPlayerRateObserver;
- (void)checkAndAutoplayIfRequired;
- (void)checkAndFireVideoEnd;
- (void)checkAndRemoveFallbackTimer;
- (void)checkAndRemovePauseTimer;
- (void)checkAndRemovePlayerRateObserver;
- (void)checkAndStartFallbackTimerWithCurrentTime:(CDStruct_1b6d18a9)arg1;
- (void)checkAndStartPauseTimerWithDelayTime:(float)arg1;
- (void)clearProperties;
@property(retain, nonatomic) NSNumber *completeAfter; // @synthesize completeAfter=_completeAfter;
@property(retain, nonatomic) id completionBoundaryObserver; // @synthesize completionBoundaryObserver=_completionBoundaryObserver;
@property(readonly) double currentViewedPercentage; // @synthesize currentViewedPercentage=_currentViewedPercentage;
- (void)dealloc;
@property(nonatomic) __weak id <IMUIVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deregisterNotifications;
- (void)didPlayToEnd;
@property(retain, nonatomic) IMTimerManager *fallbackTimer; // @synthesize fallbackTimer=_fallbackTimer;
@property(nonatomic) _Bool fallbackTimerAdded; // @synthesize fallbackTimerAdded=_fallbackTimerAdded;
@property(nonatomic) _Bool fallbackTimersRegistered; // @synthesize fallbackTimersRegistered=_fallbackTimersRegistered;
@property(retain, nonatomic) UITapGestureRecognizer *gestureRecognizer; // @synthesize gestureRecognizer=_gestureRecognizer;
- (id)initWithProperties:(id)arg1;
- (void)initializeRecycledView;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
- (_Bool)isPlayerMuted;
@property(nonatomic) _Bool isVideoEnded; // @synthesize isVideoEnded=_isVideoEnded;
@property(retain, nonatomic) NSNumber *isVideoMuted; // @synthesize isVideoMuted=_isVideoMuted;
@property(nonatomic) _Bool isVideoPaused; // @synthesize isVideoPaused=_isVideoPaused;
@property(nonatomic) _Bool kvoRegistered; // @synthesize kvoRegistered=_kvoRegistered;
@property(nonatomic) double minViewablePercentage; // @synthesize minViewablePercentage=_minViewablePercentage;
- (void)mute;
- (void)muteAndFireEvents:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)pause;
@property(nonatomic) float pauseAfter; // @synthesize pauseAfter=_pauseAfter;
@property(retain, nonatomic) IMTimerManager *pauseTimer; // @synthesize pauseTimer=_pauseTimer;
@property(nonatomic) _Bool pauseTimerAdded; // @synthesize pauseTimerAdded=_pauseTimerAdded;
- (void)pauseVideo;
- (void)play;
@property(nonatomic) _Bool playMuted; // @synthesize playMuted=_playMuted;
- (void)playVideo;
@property(retain) AVPlayer *player;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(readonly) AVPlayerLayer *playerLayer;
@property(nonatomic) double playerRate; // @synthesize playerRate=_playerRate;
- (void)prepareForRecycle;
@property(retain, nonatomic) IMUIVideoProperties *properties; // @synthesize properties=_properties;
@property(nonatomic) _Bool rateObserverAdded; // @synthesize rateObserverAdded=_rateObserverAdded;
- (void)registerNotifications;
- (void)reloadVideo;
- (void)replacePlayer:(id)arg1;
- (void)resume;
- (void)seekVideoToTime:(CDStruct_1b6d18a9)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setCurrentViewablePercentageAndAutoplay:(double)arg1;
@property(nonatomic) _Bool touchToFullScreen; // @synthesize touchToFullScreen=_touchToFullScreen;
@property(retain, nonatomic) id viewabilityBoundaryObserver; // @synthesize viewabilityBoundaryObserver=_viewabilityBoundaryObserver;
@property(retain, nonatomic) NSArray *viewabilityTimes; // @synthesize viewabilityTimes=_viewabilityTimes;
@property(retain, nonatomic) UIButton *volumeCtrlButton; // @synthesize volumeCtrlButton=_volumeCtrlButton;
- (void)showMuteButton;
- (void)stop;
- (void)tapGesture:(id)arg1;
- (void)timerHitForManager:(id)arg1;
- (void)toggleMuteState;
- (void)unmute;
- (void)unmuteAndFireEvents:(_Bool)arg1;
- (void)updateMuteButton;
- (void)videoStallDetected;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

