//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@interface IMUICollectionViewSliderLayout : UICollectionViewFlowLayout
{
    _Bool _pagingEnabled;
    double _previousOffset;
    long long _currentPage;
    id <IMUICollectionViewSliderLayoutDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) __weak id <IMUICollectionViewSliderLayoutDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithDelegate:(id)arg1 pagingEnabled:(_Bool)arg2;
@property(nonatomic) _Bool pagingEnabled; // @synthesize pagingEnabled=_pagingEnabled;
@property(nonatomic) double previousOffset; // @synthesize previousOffset=_previousOffset;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;

@end

