//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMVastObject.h"

@class NSArray, NSMutableDictionary, NSNumber, NSString;

@interface IMVastCompanion : IMVastObject
{
    NSMutableDictionary *_resourceDict;
    NSArray *_trackers;
    NSArray *_companionClickTrackers;
    NSString *_companionClickThrough;
    NSNumber *_width;
    NSNumber *_height;
    NSString *_companionID;
}

+ (id)getKeyForResourceType:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *companionClickThrough; // @synthesize companionClickThrough=_companionClickThrough;
@property(retain, nonatomic) NSArray *companionClickTrackers; // @synthesize companionClickTrackers=_companionClickTrackers;
@property(retain, nonatomic) NSString *companionID; // @synthesize companionID=_companionID;
- (id)fetchURLsFromArray:(id)arg1;
- (id)getValueForResourceType:(unsigned long long)arg1;
- (_Bool)hasCompanionResourceOfType:(unsigned long long)arg1;
@property(retain, nonatomic) NSNumber *height; // @synthesize height=_height;
- (id)initWithDictionary:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *resourceDict; // @synthesize resourceDict=_resourceDict;
@property(retain, nonatomic) NSArray *trackers; // @synthesize trackers=_trackers;
@property(retain, nonatomic) NSNumber *width; // @synthesize width=_width;

@end

