//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMNetworkDelegate.h"

@class IMNetworkServiceProvider, IMVastAd, IMVastBitRateMediaFileNode, NSString;

@interface IMVastMediaFileUtil : NSObject <IMNetworkDelegate>
{
    id <IMVastMediaFileUtilDelegate> _delegate;
    IMVastAd *_ad;
    IMVastBitRateMediaFileNode *_mediaFileNode;
    IMNetworkServiceProvider *_nsp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IMVastAd *ad; // @synthesize ad=_ad;
@property(nonatomic) __weak id <IMVastMediaFileUtilDelegate> delegate; // @synthesize delegate=_delegate;
- (void)downloadHeadersForMediaFiles;
- (id)initWithMediaFile:(id)arg1 andVastAd:(id)arg2;
@property(retain, nonatomic) IMVastBitRateMediaFileNode *mediaFileNode; // @synthesize mediaFileNode=_mediaFileNode;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetHeaders:(id)arg3;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
@property(retain, nonatomic) IMNetworkServiceProvider *nsp; // @synthesize nsp=_nsp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

