//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMNetworkDelegate.h"
#import "IMVastXMLParserDelegate.h"

@class IMNetworkServiceProvider, IMVastUnwrapperConfig, IMVastXMLParser, NSData, NSMutableArray, NSString;

@interface IMVastUnwrapper : NSObject <IMNetworkDelegate, IMVastXMLParserDelegate>
{
    _Bool _isFetchingData;
    id <IMVastUnwrapperDelegate> _delegate;
    IMVastXMLParser *_parser;
    IMNetworkServiceProvider *_nsp;
    NSString *_vastURL;
    NSData *_vastTagData;
    NSMutableArray *_pendingTagURIs;
    NSMutableArray *_ads;
    IMVastUnwrapperConfig *_config;
    long long _numRedirects;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *ads; // @synthesize ads=_ads;
@property(retain, nonatomic) IMVastUnwrapperConfig *config; // @synthesize config=_config;
@property(nonatomic) __weak id <IMVastUnwrapperDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)hasInlineAd;
- (_Bool)hasLinearAd;
- (id)init;
- (id)initWithVastTag:(id)arg1 withConfig:(id)arg2;
- (id)initWithVastUrl:(id)arg1 withConfig:(id)arg2;
@property(nonatomic) _Bool isFetchingData; // @synthesize isFetchingData=_isFetchingData;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
@property(retain, nonatomic) IMNetworkServiceProvider *nsp; // @synthesize nsp=_nsp;
@property(nonatomic) long long numRedirects; // @synthesize numRedirects=_numRedirects;
@property(retain, nonatomic) IMVastXMLParser *parser; // @synthesize parser=_parser;
@property(retain, nonatomic) NSMutableArray *pendingTagURIs; // @synthesize pendingTagURIs=_pendingTagURIs;
- (void)sendErrorWithCode:(long long)arg1;
- (void)sendRequestWithURI:(id)arg1;
@property(retain, nonatomic) NSData *vastTagData; // @synthesize vastTagData=_vastTagData;
@property(retain, nonatomic) NSString *vastURL; // @synthesize vastURL=_vastURL;
- (void)setupconfig:(id)arg1;
- (void)startUnwrapping;
- (void)vastXMLParser:(id)arg1 failedToParseDataWithError:(id)arg2;
- (void)vastXMLParser:(id)arg1 foundAdObjects:(id)arg2;
- (void)vastXMLParser:(id)arg1 foundVastTagURI:(id)arg2;
- (void)vastXMLParserProcessedAllPendingTags:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

