//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface IMVastWrapperTagOrder : NSObject
{
    _Bool _hasAdTag;
    _Bool _hasWrapperTag;
    _Bool _hasAdTagURITag;
    _Bool _canModifyValidity;
    NSMutableArray *_impressions;
}

- (void).cxx_destruct;
- (void)addAdTag;
- (void)addImpression;
- (void)addVastAdTagURITag;
- (void)addWrapperTag;
@property(readonly) _Bool canModifyValidity; // @synthesize canModifyValidity=_canModifyValidity;
- (_Bool)checkValidity;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) _Bool hasAdTag; // @synthesize hasAdTag=_hasAdTag;
@property(readonly) _Bool hasAdTagURITag; // @synthesize hasAdTagURITag=_hasAdTagURITag;
@property(readonly) _Bool hasWrapperTag; // @synthesize hasWrapperTag=_hasWrapperTag;
@property(retain, nonatomic) NSMutableArray *impressions; // @synthesize impressions=_impressions;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end

