//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "INMMoatBaseTracker.h"

#import "UIGestureRecognizerDelegate.h"

@class NSDictionary, NSMutableArray, NSMutableSet, NSString, UIView;

@interface INMMoatNativeDisplayTracker : INMMoatBaseTracker <UIGestureRecognizerDelegate>
{
    _Bool _cleanedUp;
    _Bool _initialized;
    UIView *_adView;
    NSDictionary *_adIds;
    NSMutableSet *_userInteractionEvents;
    NSMutableArray *_getstureRecognizers;
}

+ (id)getAdIdsAsJson:(id)arg1;
+ (id)trackerWithAdView:(id)arg1 withAdIds:(id)arg2;
- (void).cxx_destruct;
@property(retain) NSDictionary *adIds; // @synthesize adIds=_adIds;
@property __weak UIView *adView; // @synthesize adView=_adView;
- (void)addTouchGestureRecognizers:(id)arg1;
- (void)cleanUp;
@property _Bool cleanedUp; // @synthesize cleanedUp=_cleanedUp;
- (void)dealloc;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)getAdInfoAsJson;
- (id)getAdSizeAsJson;
- (id)getUserInteractionEventAsJson:(unsigned long long)arg1;
@property(retain) NSMutableArray *getstureRecognizers; // @synthesize getstureRecognizers=_getstureRecognizers;
- (void)handleUserInteraction:(id)arg1;
- (id)initWithAdView:(id)arg1 withAdIds:(id)arg2;
@property _Bool initialized; // @synthesize initialized=_initialized;
@property(retain) NSMutableSet *userInteractionEvents; // @synthesize userInteractionEvents=_userInteractionEvents;
- (void)startTracking;
- (void)stopTracking;
- (id)userInteractionEventAsString:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

