//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, NSTimer;

@interface INMMoatJSUpdateTimer : NSObject
{
    double viewabilityTimerDuration;
    NSHashTable *setupNeededBridges;
    NSHashTable *activeTrackers;
    NSTimer *metadataTimer;
    NSTimer *viewabilityTimer;
}

+ (id)sharedJSUpdateTimer;
- (void).cxx_destruct;
@property(retain) NSHashTable *activeTrackers; // @synthesize activeTrackers;
- (void)addActiveTracker:(id)arg1;
- (void)addSetupNeededBridge:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)metadataLoopEnded:(id)arg1;
@property(retain) NSTimer *metadataTimer; // @synthesize metadataTimer;
- (void)removeActiveTracker:(id)arg1;
- (void)removeSetupNeededBridge:(id)arg1;
@property(retain) NSHashTable *setupNeededBridges; // @synthesize setupNeededBridges;
@property(retain) NSTimer *viewabilityTimer; // @synthesize viewabilityTimer;
@property double viewabilityTimerDuration; // @synthesize viewabilityTimerDuration;
- (void)startMetadataTimer;
- (void)startViewabilityTimer;
- (void)viewabilityLoopEnded:(id)arg1;

@end

