//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface INMMoatOnOff : NSObject
{
}

+ (void)checkQueue;
+ (void)enqueueResurrection:(id)arg1;
+ (unsigned long long)getDebug;
+ (unsigned long long)getStatus;
+ (void)initialize;
+ (_Bool)isAllDebuggingOn;
+ (_Bool)isClientDebuggingOn;
+ (_Bool)isDevelopmentEnvironment;
+ (void)load;
+ (void)onResurrectionDo:(CDUnknownBlockType)arg1 withQueue:(id)arg2 withKey:(id)arg3;
+ (void)processQueue:(id)arg1 withQueue:(id)arg2;
+ (void)resurrect;
+ (void)runEnablerCheck;
+ (void)runStatusCheckInThread;
+ (void)setDebug:(unsigned long long)arg1;

@end

