//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, INMMoatLocationFetch, NSString, NSTimer;

@interface INMMoatLocationManager : NSObject <CLLocationManagerDelegate>
{
    double _maxLocationAge;
    double _desiredAccuracy;
    double _locationFetchInterval;
    double _locationFetchTimeout;
    CLLocation *_bestLocation;
    CLLocationManager *_cl_locationManager;
    INMMoatLocationFetch *_currentLocationFetch;
    NSTimer *_locationFetchTimer;
    NSTimer *_fetchTimeoutTimer;
}

+ (unsigned long long)authorizationStatus;
+ (id)chooseBestLocation:(id)arg1 compareAgainst:(id)arg2;
+ (_Bool)isAccurateEnoughLocation:(id)arg1;
+ (_Bool)isOutdatedLocation:(id)arg1;
+ (unsigned long long)isValidLocation:(id)arg1;
+ (_Bool)locationServicesAvailable;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) CLLocation *bestLocation; // @synthesize bestLocation=_bestLocation;
@property(readonly, nonatomic) CLLocationManager *cl_locationManager; // @synthesize cl_locationManager=_cl_locationManager;
- (void)commonInit;
@property(retain, nonatomic) INMMoatLocationFetch *currentLocationFetch; // @synthesize currentLocationFetch=_currentLocationFetch;
@property(nonatomic) double desiredAccuracy; // @synthesize desiredAccuracy=_desiredAccuracy;
- (void)fetchDidTimeout;
@property(retain, nonatomic) NSTimer *fetchTimeoutTimer; // @synthesize fetchTimeoutTimer=_fetchTimeoutTimer;
- (id)init;
@property(nonatomic) double locationFetchInterval; // @synthesize locationFetchInterval=_locationFetchInterval;
@property(nonatomic) double locationFetchTimeout; // @synthesize locationFetchTimeout=_locationFetchTimeout;
@property(retain, nonatomic) NSTimer *locationFetchTimer; // @synthesize locationFetchTimer=_locationFetchTimer;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
@property(nonatomic) double maxLocationAge; // @synthesize maxLocationAge=_maxLocationAge;
- (void)receivedDidEnterBackgroundNotification:(id)arg1;
- (void)receivedWillEnterForegroundNotification:(id)arg1;
- (void)resetFetchTimer;
- (_Bool)shouldStartNewFetch;
- (void)startLocationFetch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

