//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "InMobi_InternalAvidAdSessionDelegate.h"

@class NSArray, NSMutableDictionary, NSString;

@interface InMobi_AvidAdSessionRegistry : NSObject <InMobi_InternalAvidAdSessionDelegate>
{
    NSMutableDictionary *_avidAdSessions;
    NSMutableDictionary *_internalAvidAdSessions;
    long long _activeSessionCount;
}

+ (id)getInstance;
- (void).cxx_destruct;
@property(nonatomic) long long activeSessionCount; // @synthesize activeSessionCount=_activeSessionCount;
- (void)adSessionBecomeActive:(id)arg1;
- (void)adSessionDidEnd:(id)arg1;
- (void)adSessionResignActive:(id)arg1;
@property(readonly, nonatomic) NSArray *avidAdSessions;
- (id)findAvidAdSessionById:(id)arg1;
- (id)findInternalAvidAdSessionById:(id)arg1;
- (id)findInternalAvidAdSessionByView:(id)arg1;
@property(readonly, nonatomic) _Bool hasActiveSessions;
- (id)init;
@property(readonly, nonatomic) NSArray *internalAvidAdSessions;
@property(readonly, nonatomic) _Bool isEmpty;
- (void)postHasActiveSessionChanged;
- (void)postIsEmptyChanged;
- (void)registerAvidAdSession:(id)arg1 withInternalAvidAdSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

