//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@protocol iRateDelegate <NSObject>

@optional
- (void)iRateCouldNotConnectToAppStore:(NSError *)arg1;
- (void)iRateDidDetectAppUpdate;
- (void)iRateDidOpenAppStore;
- (void)iRateDidPromptForRating;
- (_Bool)iRateShouldOpenAppStore;
- (_Bool)iRateShouldPromptForRating;
- (void)iRateUserDidAttemptToRateApp;
- (void)iRateUserDidDeclineToRateApp;
- (void)iRateUserDidRequestReminderToRateApp;
@end

