//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface iRate : NSObject
{
    _Bool _useSKStoreReviewControllerIfAvailable;
    _Bool _useUIAlertControllerIfAvailable;
    _Bool _useAllAvailableLanguages;
    _Bool _promptForNewVersionIfUserRated;
    _Bool _onlyPromptIfLatestVersion;
    _Bool _onlyPromptIfMainWindowIsAvailable;
    _Bool _promptAtLaunch;
    _Bool _verboseLogging;
    _Bool _previewMode;
    _Bool _checkingForPrompt;
    _Bool _checkingForAppStoreID;
    float _daysUntilPrompt;
    float _usesPerWeekForPrompt;
    float _remindPeriod;
    unsigned long long _appStoreID;
    unsigned long long _appStoreGenreID;
    NSString *_appStoreCountry;
    NSString *_applicationName;
    NSString *_applicationVersion;
    NSString *_applicationBundleID;
    unsigned long long _usesUntilPrompt;
    unsigned long long _eventsUntilPrompt;
    NSString *_messageTitle;
    NSString *_message;
    NSString *_updateMessage;
    NSString *_cancelButtonLabel;
    NSString *_remindButtonLabel;
    NSString *_rateButtonLabel;
    NSURL *_ratingsURL;
    id <iRateDelegate> _delegate;
    id _visibleAlert;
}

+ (void)load;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
@property(copy, nonatomic) NSString *appStoreCountry; // @synthesize appStoreCountry=_appStoreCountry;
@property(nonatomic) unsigned long long appStoreGenreID; // @synthesize appStoreGenreID=_appStoreGenreID;
@property(nonatomic) unsigned long long appStoreID; // @synthesize appStoreID=_appStoreID;
@property(copy, nonatomic) NSString *applicationBundleID; // @synthesize applicationBundleID=_applicationBundleID;
- (void)applicationLaunched;
@property(copy, nonatomic) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property(copy, nonatomic) NSString *applicationVersion; // @synthesize applicationVersion=_applicationVersion;
- (void)applicationWillEnterForeground;
@property(copy, nonatomic) NSString *cancelButtonLabel; // @synthesize cancelButtonLabel=_cancelButtonLabel;
- (void)checkForConnectivity;
- (void)checkForConnectivityInBackground;
@property(nonatomic) _Bool checkingForAppStoreID; // @synthesize checkingForAppStoreID=_checkingForAppStoreID;
@property(nonatomic) _Bool checkingForPrompt; // @synthesize checkingForPrompt=_checkingForPrompt;
- (void)connectionError:(id)arg1;
- (void)connectionSucceeded;
@property(nonatomic) float daysUntilPrompt; // @synthesize daysUntilPrompt=_daysUntilPrompt;
- (void)dealloc;
- (void)declineThisVersion;
@property(readonly, nonatomic) _Bool declinedAnyVersion;
@property(nonatomic) _Bool declinedThisVersion;
@property(nonatomic) __weak id <iRateDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didDismissAlert:(id)arg1 withButtonAtIndex:(long long)arg2;
@property(nonatomic) unsigned long long eventCount;
@property(nonatomic) unsigned long long eventsUntilPrompt; // @synthesize eventsUntilPrompt=_eventsUntilPrompt;
@property(retain, nonatomic) NSDate *firstUsed;
- (void)incrementEventCount;
- (void)incrementUseCount;
- (id)init;
@property(retain, nonatomic) NSDate *lastReminded;
- (id)localizedStringForKey:(id)arg1 withDefault:(id)arg2;
- (void)logEvent:(_Bool)arg1;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *messageTitle; // @synthesize messageTitle=_messageTitle;
@property(nonatomic) _Bool onlyPromptIfLatestVersion; // @synthesize onlyPromptIfLatestVersion=_onlyPromptIfLatestVersion;
@property(nonatomic) _Bool onlyPromptIfMainWindowIsAvailable; // @synthesize onlyPromptIfMainWindowIsAvailable=_onlyPromptIfMainWindowIsAvailable;
- (void)openRatingsPageInAppStore;
@property(nonatomic) _Bool previewMode; // @synthesize previewMode=_previewMode;
@property(nonatomic) _Bool promptAtLaunch; // @synthesize promptAtLaunch=_promptAtLaunch;
@property(nonatomic) _Bool promptForNewVersionIfUserRated; // @synthesize promptForNewVersionIfUserRated=_promptForNewVersionIfUserRated;
- (void)promptForRating;
- (void)promptForRating:(_Bool)arg1;
- (void)promptIfAllCriteriaMet;
- (void)promptIfNetworkAvailable;
- (void)rate;
@property(copy, nonatomic) NSString *rateButtonLabel; // @synthesize rateButtonLabel=_rateButtonLabel;
@property(readonly, nonatomic) _Bool ratedAnyVersion;
@property(nonatomic) _Bool ratedThisVersion;
- (_Bool)ratedVersion:(id)arg1;
@property(retain, nonatomic) NSURL *ratingsURL; // @synthesize ratingsURL=_ratingsURL;
@property(copy, nonatomic) NSString *remindButtonLabel; // @synthesize remindButtonLabel=_remindButtonLabel;
- (void)remindLater;
@property(nonatomic) float remindPeriod; // @synthesize remindPeriod=_remindPeriod;
- (void)setAppStoreIDOnMainThread:(id)arg1;
@property(copy, nonatomic) NSString *updateMessage; // @synthesize updateMessage=_updateMessage;
@property(nonatomic) _Bool useAllAvailableLanguages; // @synthesize useAllAvailableLanguages=_useAllAvailableLanguages;
@property(nonatomic) _Bool useSKStoreReviewControllerIfAvailable; // @synthesize useSKStoreReviewControllerIfAvailable=_useSKStoreReviewControllerIfAvailable;
@property(nonatomic) _Bool useUIAlertControllerIfAvailable; // @synthesize useUIAlertControllerIfAvailable=_useUIAlertControllerIfAvailable;
@property(nonatomic) unsigned long long usesCount;
@property(nonatomic) float usesPerWeekForPrompt; // @synthesize usesPerWeekForPrompt=_usesPerWeekForPrompt;
@property(nonatomic) unsigned long long usesUntilPrompt; // @synthesize usesUntilPrompt=_usesUntilPrompt;
@property(nonatomic) _Bool verboseLogging; // @synthesize verboseLogging=_verboseLogging;
@property(retain, nonatomic) id visibleAlert; // @synthesize visibleAlert=_visibleAlert;
- (_Bool)shouldPromptForRating;
- (_Bool)showCancelButton;
- (_Bool)showRemindButton;
@property(readonly, nonatomic) float usesPerWeek;
- (id)valueForKey:(id)arg1 inJSON:(id)arg2;

@end

