//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SSDKHttpServiceModel;

@protocol ISSPSliceUpload <NSObject>
- (unsigned long long)setPlatform;
- (NSString *)setPlatformName;
- (void)upLoadAppend:(SSDKHttpServiceModel *)arg1;
- (void)upLoadFinalize:(SSDKHttpServiceModel *)arg1;
- (void)upLoadInit:(SSDKHttpServiceModel *)arg1;
@end

