//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface JYSegmentBarItem : UICollectionViewCell
{
    UILabel *_titleLabel;
    UIImageView *_dotView;
}

- (void).cxx_destruct;
- (void)__layoutSubviews;
@property(retain, nonatomic) UIImageView *dotView; // @synthesize dotView=_dotView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)showNewDot:(_Bool)arg1;

@end

