//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIScrollView, UIViewController;

@protocol JYSlideSegmentDelegate <NSObject>

@optional
- (void)didFullyShowViewController:(UIViewController *)arg1;
- (void)didSelectViewController:(UIViewController *)arg1;
- (_Bool)shouldSelectViewController:(UIViewController *)arg1;
- (void)slideSegmentDidScroll:(UIScrollView *)arg1;
- (void)slideSegmentDidTapAgain:(UIScrollView *)arg1;
- (void)slideViewDidScroll:(UIScrollView *)arg1;
@end

