//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RennParam.h"

@class NSString;

@interface ListPlaceFeedParam : RennParam
{
    long long _pageSize;
    long long _pageNumber;
    NSString *_placeId;
    NSString *_locationFeedType;
}

- (void)dealloc;
- (id)init;
@property(retain, nonatomic) NSString *locationFeedType; // @synthesize locationFeedType=_locationFeedType;
@property(nonatomic) long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(retain, nonatomic) NSString *placeId; // @synthesize placeId=_placeId;

@end

