//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface LSAdNetworkConfig : NSObject
{
    int _networkType;
    NSString *_networkID;
    NSString *_publishID;
    NSString *_slotID;
    long long _weight;
    double _loadTimeout;
    Class _adapterClass;
    NSDate *_lastBannedTime;
    long long _requestFailTimes;
}

+ (id)networkIDForType:(int)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) Class adapterClass; // @synthesize adapterClass=_adapterClass;
- (id)initWithData:(id)arg1 networkID:(id)arg2;
@property(retain, nonatomic) NSDate *lastBannedTime; // @synthesize lastBannedTime=_lastBannedTime;
@property(readonly, nonatomic) double loadTimeout; // @synthesize loadTimeout=_loadTimeout;
@property(readonly, nonatomic) NSString *networkID; // @synthesize networkID=_networkID;
@property(readonly, nonatomic) int networkType; // @synthesize networkType=_networkType;
@property(readonly, nonatomic) NSString *publishID; // @synthesize publishID=_publishID;
@property(nonatomic) long long requestFailTimes; // @synthesize requestFailTimes=_requestFailTimes;
@property(readonly, nonatomic) NSString *slotID; // @synthesize slotID=_slotID;
@property(readonly, nonatomic) long long weight; // @synthesize weight=_weight;

@end

