//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MDDisplayStrategyManager, MDPluginManager, MDProjectionStrategyManager;

__attribute__((visibility("hidden")))
@interface MD360RendererBuilder : NSObject
{
    MDPluginManager *_pluginManager;
    MDDisplayStrategyManager *_displayStrategyManager;
    MDProjectionStrategyManager *_projectionStrategyManager;
}

- (void).cxx_destruct;
- (id)build;
@property(nonatomic) __weak MDDisplayStrategyManager *displayStrategyManager; // @synthesize displayStrategyManager=_displayStrategyManager;
@property(nonatomic) __weak MDPluginManager *pluginManager; // @synthesize pluginManager=_pluginManager;
@property(nonatomic) __weak MDProjectionStrategyManager *projectionStrategyManager; // @synthesize projectionStrategyManager=_projectionStrategyManager;

@end

