//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMDDestroyable.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MD360Program : NSObject <IMDDestroyable>
{
    unsigned int vertexShaderHandle;
    unsigned int fragmentShaderHandle;
    int _mMVPMatrixHandle;
    int _mMVMatrixHandle;
    int _mPositionHandle;
    int _mTextureCoordinateHandle;
    int _mProgramHandle;
    int _mContentType;
    int _mColorConversionHandle;
    int *_mTextureUniformHandle;
}

- (void)build;
- (void)destroy;
- (int)getTextureUniformSize;
@property(nonatomic) int mColorConversionHandle; // @synthesize mColorConversionHandle=_mColorConversionHandle;
@property(nonatomic) int mContentType; // @synthesize mContentType=_mContentType;
@property(nonatomic) int mMVMatrixHandle; // @synthesize mMVMatrixHandle=_mMVMatrixHandle;
@property(nonatomic) int mMVPMatrixHandle; // @synthesize mMVPMatrixHandle=_mMVPMatrixHandle;
@property(nonatomic) int mPositionHandle; // @synthesize mPositionHandle=_mPositionHandle;
@property(nonatomic) int mProgramHandle; // @synthesize mProgramHandle=_mProgramHandle;
@property(nonatomic) int mTextureCoordinateHandle; // @synthesize mTextureCoordinateHandle=_mTextureCoordinateHandle;
@property(nonatomic) int *mTextureUniformHandle; // @synthesize mTextureUniformHandle=_mTextureUniformHandle;
- (void)use;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

