//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMDDestroyable.h"
#import "MDAbsObject3DDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MDAbsObject3D : NSObject <MDAbsObject3DDelegate, IMDDestroyable>
{
    float *mVertexBuffer0;
    float *mTextureBuffer0;
    float *mVertexBuffer1;
    float *mTextureBuffer1;
    short *mIndicesBuffer;
    int mVertexSize;
    int mTextureSize;
    int _mNumIndices;
}

- (void)dealloc;
- (void)destroy;
- (void)executeLoad;
- (void)freeBuffer:(float *)arg1;
- (short *)getIndices;
- (float *)getTextureBuffer:(int)arg1;
- (float *)getVertexBuffer:(int)arg1;
@property(readonly, nonatomic) int mNumIndices; // @synthesize mNumIndices=_mNumIndices;
- (void)onDraw;
- (void)setIndicesBuffer:(short *)arg1 size:(int)arg2;
- (void)setNumIndices:(int)arg1;
- (void)setTextureIndex:(int)arg1 buffer:(float *)arg2 size:(int)arg3;
- (void)setVertexIndex:(int)arg1 buffer:(float *)arg2 size:(int)arg3;
- (void)uploadTexCoordinateBufferIfNeed:(id)arg1 index:(int)arg2;
- (void)uploadVerticesBufferIfNeed:(id)arg1 index:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

