//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMDModeStrategy.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface MDModeManager : NSObject <IMDModeStrategy>
{
    int _mMode;
    id _mStrategy;
    NSArray *_mModes;
}

- (void).cxx_destruct;
- (id)createModes;
- (id)createStrategy:(int)arg1;
- (void)initMode:(int)arg1;
- (id)initWithDefault:(int)arg1;
@property(readonly, nonatomic) int mMode; // @synthesize mMode=_mMode;
@property(retain, nonatomic) NSArray *mModes; // @synthesize mModes=_mModes;
@property(retain, nonatomic) id mStrategy; // @synthesize mStrategy=_mStrategy;
- (void)off;
- (void)on;
- (void)prepare;
- (void)switchMode;
- (void)switchMode:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

