//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MD360Program, MD360Texture, MDPluginManager, MDProjectionStrategyManager;

__attribute__((visibility("hidden")))
@interface MDPanoramaPluginBuilder : NSObject
{
    MD360Texture *_texture;
    MD360Program *_program;
    MDPluginManager *_pluginManager;
    MDProjectionStrategyManager *_projectionStrategyManager;
}

- (void).cxx_destruct;
- (id)build;
@property(nonatomic) __weak MDPluginManager *pluginManager; // @synthesize pluginManager=_pluginManager;
@property(readonly, nonatomic) MD360Program *program; // @synthesize program=_program;
@property(nonatomic) __weak MDProjectionStrategyManager *projectionStrategyManager; // @synthesize projectionStrategyManager=_projectionStrategyManager;
- (void)setProgram:(id)arg1;
- (void)setTexture:(id)arg1;
@property(readonly, nonatomic) MD360Texture *texture; // @synthesize texture=_texture;

@end

