//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDAbsObject3D.h"

__attribute__((visibility("hidden")))
@interface MDStereoSphere3D : MDAbsObject3D
{
}

+ (int)generateStereoSphere:(float)arg1 numSlices:(int)arg2 object3D:(id)arg3;
- (void)executeLoad;
- (id)obtainObjPath;

@end

