//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPlayerItemOutputPullDelegate.h"
#import "MDVideoDataAdapter.h"

@class AVPlayerItem, AVPlayerItemVideoOutput, NSString;

__attribute__((visibility("hidden")))
@interface MDVideoDataAdatperAVPlayerImpl : NSObject <AVPlayerItemOutputPullDelegate, MDVideoDataAdapter>
{
    AVPlayerItemVideoOutput *_output;
    AVPlayerItem *_playerItem;
}

- (void).cxx_destruct;
- (void)addObserver;
- (struct __CVBuffer *)copyPixelBuffer;
- (void)dealloc;
- (id)initWithPlayerItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) AVPlayerItemVideoOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
- (void)removeObserver;
- (void)setup;
- (void)teardown;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

