//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MOBFDataModelPropertyInfo;

@interface MOBFMethodRouteInfo : NSObject
{
    _Bool _isSet;
    MOBFDataModelPropertyInfo *_propertyInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isSet; // @synthesize isSet=_isSet;
@property(retain, nonatomic) MOBFDataModelPropertyInfo *propertyInfo; // @synthesize propertyInfo=_propertyInfo;

@end

