//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

__attribute__((visibility("hidden")))
@interface MyPlayerLoadingView : UIView
{
    UIActivityIndicatorView *indicatorView;
    UILabel *messageLabel;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutMessage;
- (void)layoutSubviews;
- (void)setMessage:(id)arg1;

@end

