//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (Style)
- (id)absoluteDurationFromDictionary:(id)arg1;
- (id)absoluteStartOffset;
- (id)absoluteTimerDuration;
- (unsigned long long)animationStyle;
- (id)backgroundColor;
- (id)borderColor;
- (unsigned long long)borderCorner;
- (unsigned long long)borderStyle;
- (double)borderWidth;
- (long long)contentMode;
- (struct CGRect)finalGeometry;
- (struct CGRect)geometry;
- (struct CGRect)getCGRectFromArray:(id)arg1;
- (id)getFontDescriptorWithName:(id)arg1 style:(unsigned long long)arg2 withSize:(double)arg3;
- (_Bool)isAutoPlay;
- (id)nonSafeAreaBackgroundColor;
- (unsigned long long)orientation;
- (id)percentageFromDictionary:(id)arg1;
- (id)startOffSet;
- (id)startOffsetPercentage;
- (id)startOffsetReference;
- (_Bool)string:(id)arg1 hasSubString:(id)arg2;
- (long long)textAlignment;
- (id)textColor;
- (id)textFont;
- (double)textSize;
- (unsigned long long)textStyle;
- (id)textStyleAttributes;
- (long long)textTruncateLength;
- (id)timerDuration;
- (id)timerDurationPercentage;
- (id)timerDurationReference;
- (id)timerReferenceFromDictionary:(id)arg1;
- (unsigned long long)transitionDirection;
- (unsigned long long)transitionEffect;
@end

