//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TTAdditions)
- (_Bool)isEmptyOrWhitespace;
- (_Bool)isWhitespaceAndNewlines;
@property(readonly, nonatomic) NSString *md5Hash;
- (id)queryContentsUsingEncoding:(unsigned long long)arg1;
- (id)queryDictionaryUsingEncoding:(unsigned long long)arg1;
@property(readonly, nonatomic) NSString *sha1Hash;
- (id)stringByAddingQueryDictionary:(id)arg1;
- (id)stringByAddingURLEncodedQueryDictionary:(id)arg1;
- (id)stringByRemovingHTMLTags;
- (id)urlEncoded;
- (long long)versionStringCompare:(id)arg1;
@end

