//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class CADisplayLink, NSString, OLImage;

__attribute__((visibility("hidden")))
@interface OLImageView : UIImageView
{
    struct {
        unsigned int didLoop:1;
        unsigned int shouldStartAnimating:1;
    } _delegateFlags;
    NSString *_runLoopMode;
    CADisplayLink *_displayLink;
    id <OLImageViewDelegate> _delegate;
    OLImage *_animatedImage;
    double _accumulator;
    unsigned long long _currentFrameIndex;
    unsigned long long _loopCountdown;
}

- (void).cxx_destruct;
@property(nonatomic) double accumulator; // @synthesize accumulator=_accumulator;
@property(retain, nonatomic) OLImage *animatedImage; // @synthesize animatedImage=_animatedImage;
- (void)changeKeyframe:(id)arg1;
- (unsigned long long)currentAnimatedImageIndex;
@property(nonatomic) unsigned long long currentFrameIndex; // @synthesize currentFrameIndex=_currentFrameIndex;
@property(nonatomic) __weak id <OLImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)delegateDidLoop;
- (_Bool)delegateShouldStartAnimating;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)displayLayer:(id)arg1;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (id)image;
- (id)init;
- (_Bool)isAnimating;
@property(nonatomic) unsigned long long loopCountdown; // @synthesize loopCountdown=_loopCountdown;
@property(copy, nonatomic) NSString *runLoopMode; // @synthesize runLoopMode=_runLoopMode;
- (void)setCurrentAnimatedImageIndex:(unsigned long long)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setImage:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)startAnimating;
- (void)stopAnimating;

@end

