//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

#import "YYAnimatedImage.h"

@class NSArray, NSString, OLImageSourceArray;

__attribute__((visibility("hidden")))
@interface OLImage : UIImage <YYAnimatedImage>
{
    NSArray *images;
    double *_frameDurations;
    double _totalDuration;
    unsigned long long _loopCount;
    struct CGImageSource *_incrementalSource;
    OLImageSourceArray *_imageSourceArray;
}

+ (id)imageNamed:(id)arg1;
+ (id)imageWithContentsOfFile:(id)arg1;
+ (id)imageWithData:(id)arg1;
+ (id)imageWithData:(id)arg1 scale:(double)arg2;
+ (id)imageWithIncrementalData:(id)arg1;
- (void).cxx_destruct;
- (struct CGImage *)CGImage;
- (unsigned long long)animatedImageBytesPerFrame;
- (double)animatedImageDurationAtIndex:(unsigned long long)arg1;
- (id)animatedImageFrameAtIndex:(unsigned long long)arg1;
- (unsigned long long)animatedImageFrameCount;
- (unsigned long long)animatedImageLoopCount;
- (void)dealloc;
- (double)duration;
@property(nonatomic) double *frameDurations; // @synthesize frameDurations=_frameDurations;
- (long long)imageOrientation;
@property(retain, nonatomic) OLImageSourceArray *imageSourceArray; // @synthesize imageSourceArray=_imageSourceArray;
- (id)images;
@property(nonatomic) struct CGImageSource *incrementalSource; // @synthesize incrementalSource=_incrementalSource;
- (id)initWithCGImageSource:(struct CGImageSource *)arg1 scale:(double)arg2;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithData:(id)arg1 scale:(double)arg2;
@property(readonly, nonatomic, getter=isPartial) _Bool partial;
@property(nonatomic) unsigned long long loopCount; // @synthesize loopCount=_loopCount;
- (double)scale;
@property(nonatomic) double totalDuration; // @synthesize totalDuration=_totalDuration;
- (struct CGSize)size;
- (void)updateDurations;
- (void)updateWithData:(id)arg1;
- (void)updateWithData:(id)arg1 final:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

