//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OpenApi : NSObject
{
}

+ (_Bool)authorizeWithPermission:(id)arg1 delegate:(id)arg2 firstCall:(int)arg3;
+ (_Bool)canHandleOpenURL:(id)arg1;
+ (_Bool)canParseURL:(id)arg1;
+ (void)clearParam;
+ (id)dictionaryByParseUrlFromSeparator:(id)arg1 separator:(id)arg2;
+ (id)getDictionaryFromGeneralPasteBoard:(id)arg1;
+ (id)getDictionaryFromPasteBoard:(id)arg1;
+ (id)getGeneralPastboardNameKey;
+ (_Bool)handleOpenURL:(id)arg1;
+ (_Bool)isQZoneSupportGeneralPastboard;
+ (_Bool)isSupportGeneralPastboard;
+ (_Bool)openQQWithCommand:(int)arg1 andPasteBoardName:(id)arg2 data:(id)arg3 callApp:(int)arg4;
+ (_Bool)processMessage:(id)arg1;
+ (void)processMessage_Auth:(id)arg1;
+ (void)processMessage_Other:(id)arg1 msgTypeStr:(id)arg2;
+ (void)processMessage_Share:(id)arg1;
+ (int)qqVersion;
+ (_Bool)registerApp:(id)arg1;
+ (_Bool)registerApp:(id)arg1 withDelegate:(id)arg2 andOldApi:(id)arg3;
+ (id)saveDictionary:(id)arg1 toPasteBoard:(id)arg2;
+ (id)saveDictionaryByGeneralPastboard:(id)arg1;
+ (void)setTencentAuthorizeState:(int)arg1;
+ (int)tencentAuhorizeState;
+ (int)timVersion;
+ (void)unRegisterApp:(id)arg1 withDelegate:(id)arg2 andOldApi:(id)arg3;
+ (void)unRegisterAppSessionDelegate:(id)arg1;

@end

