//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AbsProjectionMode.h"

@class MDAbsObject3D, MDPlaneScaleCalculator;

__attribute__((visibility("hidden")))
@interface PlaneProjection : AbsProjectionMode
{
    MDAbsObject3D *_object3D;
    MDPlaneScaleCalculator *_calculator;
}

+ (id)create:(long long)arg1 sizeContext:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) MDPlaneScaleCalculator *calculator; // @synthesize calculator=_calculator;
- (id)getObject3D;
- (id)hijackDirectorFactory;
@property(retain, nonatomic) MDAbsObject3D *object3D; // @synthesize object3D=_object3D;
- (void)on;

@end

