//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RennParam.h"

@class NSString;

@interface PutCommentParam : RennParam
{
    NSString *_entryOwnerId;
    NSString *_entryId;
    NSString *_commentType;
    NSString *_targetUserId;
    NSString *_content;
}

@property(retain, nonatomic) NSString *commentType; // @synthesize commentType=_commentType;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void)dealloc;
@property(retain, nonatomic) NSString *entryId; // @synthesize entryId=_entryId;
@property(retain, nonatomic) NSString *entryOwnerId; // @synthesize entryOwnerId=_entryOwnerId;
- (id)init;
@property(retain, nonatomic) NSString *targetUserId; // @synthesize targetUserId=_targetUserId;

@end

