//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFUITableController.h"

@class NSString, UITextField;

__attribute__((visibility("hidden")))
@interface QLServerURLEditController : WFUITableController
{
    UITextField *tfServerURL;
    long long editorTag;
    id <QLServerURLEditor> _delegate;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *currentValue;
- (void)dealloc;
@property(nonatomic) __weak id <QLServerURLEditor> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long editorTag; // @synthesize editorTag;
- (id)initWithDelegate:(id)arg1 tag:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end

