//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QLServerURLEditController;

@protocol QLServerURLEditor <NSObject>
- (NSString *)magicValueForEditor:(QLServerURLEditController *)arg1;
- (void)requestRestoreValue:(QLServerURLEditController *)arg1;
- (void)saveValueForEditor:(QLServerURLEditController *)arg1;
- (NSString *)titleForEditor:(QLServerURLEditController *)arg1;
- (NSString *)valueForEditor:(QLServerURLEditController *)arg1;
@end

