//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface QQApi : NSObject
{
}

+ (void)cgiShareReportWithMessage:(id)arg1 andActtype:(int)arg2 andReporttype:(int)arg3 andCallsource:(int)arg4;
+ (_Bool)checkQQApiURLMessage:(id)arg1;
+ (id)getAdItemArray;
+ (id)getQQInstallURL;
+ (id)getTIMInstallURL;
+ (id)handleOpenURL:(id)arg1;
+ (id)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
+ (_Bool)isQIMInstalled;
+ (_Bool)isQQInstalled;
+ (_Bool)isQQSupportApi;
+ (_Bool)isQQSupportApiForDataLine;
+ (_Bool)isQQSupportQZoneMediaShare;
+ (_Bool)isQQSupportQZoneShare;
+ (_Bool)isTIMInstalled;
+ (_Bool)isTIMSupportApi;
+ (_Bool)isTIMSupportQZoneMediaShare;
+ (_Bool)openQQApp;
+ (_Bool)openTIMApp;
+ (void)registerAccessToken:(id)arg1;
+ (void)registerPluginWithId:(id)arg1;
+ (void)registerQQConnectAppId:(id)arg1;
+ (void)registerQQConnectOpenId:(id)arg1;
+ (void)registerQQUin:(id)arg1;
+ (int)sendMessage:(id)arg1;
+ (int)sendMessage_QQNotInstalledOrOld:(id)arg1 isOld:(_Bool)arg2;
+ (int)sendMessage_TIMNotInstalledOrOld:(id)arg1 isOld:(_Bool)arg2;
+ (void)showErrorWithWebView:(id)arg1;
+ (id)supportShareScheme;
- (id)init;

@end

