//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QQApiObject : NSObject
{
    int _shareDestType;
    NSString *_title;
    NSString *_description;
    unsigned long long _cflag;
}

@property(nonatomic) unsigned long long cflag; // @synthesize cflag=_cflag;
- (void)dealloc;
@property(retain, nonatomic) NSString *description; // @synthesize description=_description;
- (id)init;
@property(nonatomic) int shareDestType; // @synthesize shareDestType=_shareDestType;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

