//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface QQApiAdItem : NSObject
{
    NSString *_description;
    NSString *_title;
    NSData *_imageData;
    NSURL *_target;
}

- (void)dealloc;
@property(retain, nonatomic) NSString *description; // @synthesize description=_description;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSURL *target; // @synthesize target=_target;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

