//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QQBaseResp : NSObject
{
    int _type;
    NSString *_result;
    NSString *_errorDescription;
    NSString *_extendInfo;
}

- (void)dealloc;
@property(copy, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
@property(nonatomic) NSString *extendInfo; // @synthesize extendInfo=_extendInfo;
@property(copy, nonatomic) NSString *result; // @synthesize result=_result;
@property(nonatomic) int type; // @synthesize type=_type;

@end

