//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RennHttpRequestDelegate.h"

@class NSString, RennHttpRequest;

@interface RennService : NSObject <RennHttpRequestDelegate>
{
    id <RennServiveDelegate> _delegate;
    NSString *_type;
    RennHttpRequest *_request;
}

- (void)clearDelegateAndCancel;
- (void)dealloc;
@property(nonatomic) id <RennServiveDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithDelegate:(id)arg1;
@property(retain, nonatomic) RennHttpRequest *request; // @synthesize request=_request;
- (void)request:(id)arg1 failWithError:(id)arg2;
- (void)request:(id)arg1 responseWithData:(id)arg2;
- (void)sendAsynRequest:(id)arg1;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

