//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableData, NSString, NSURL, NSURLConnection;

@interface RennHttpRequest : NSObject
{
    _Bool _shouldExit;
    id <RennHttpRequestDelegate> _delegate;
    double _timeoutInterval;
    NSURL *_URL;
    NSDictionary *_param;
    NSDictionary *_data;
    NSString *_httpMethod;
    NSString *_ua;
    NSURLConnection *_connection;
    NSMutableData *_responseData;
}

@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (id)accessToken;
- (void)addAuthorization:(id)arg1;
- (void)buildMultipartFormDataPostBody:(id)arg1;
- (void)clearDelegateAndCancel;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void)dealloc;
@property(retain, nonatomic) id <RennHttpRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *httpMethod; // @synthesize httpMethod=_httpMethod;
- (id)initWithPath:(id)arg1 param:(id)arg2;
- (id)initWithURL:(id)arg1 param:(id)arg2;
@property(retain, nonatomic) NSDictionary *param; // @synthesize param=_param;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(retain, nonatomic) NSString *ua; // @synthesize ua=_ua;
- (void)startAsynchronous;

@end

