//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QQBaseReq.h"

@class QQApiObject;

__attribute__((visibility("hidden")))
@interface SendMessageToQQReq : QQBaseReq
{
    QQApiObject *_message;
}

+ (id)reqWithContent:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) QQApiObject *message; // @synthesize message=_message;

@end

