//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SMSSDKUserInfo;

__attribute__((visibility("hidden")))
@interface SMSGlobalManager : NSObject
{
    SMSSDKUserInfo *_curUserInfo;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)copyUserInfo;
@property(retain, nonatomic) SMSSDKUserInfo *curUserInfo; // @synthesize curUserInfo=_curUserInfo;
- (id)init;
- (void)saveUserInfo;
- (void)saveUserInfo:(id)arg1 zone:(id)arg2;

@end

