//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSDictionary, SMSSDKAddressBook, UIButton, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface SMSSDKUIContactTableViewCell : UITableViewCell
{
    SMSSDKAddressBook *_contact;
    unsigned long long _actionType;
    NSDictionary *_userInfo;
    id <SMSSDKUIContactTableViewCellDelegate> _delegate;
    UIImageView *_headIcon;
    UILabel *_nameLabel;
    UILabel *_nameDescLabel;
    UIView *_lineBottom;
    UIButton *_inviteBtn;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
- (void)configUI;
@property(retain, nonatomic) SMSSDKAddressBook *contact; // @synthesize contact=_contact;
@property(nonatomic) __weak id <SMSSDKUIContactTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *headIcon; // @synthesize headIcon=_headIcon;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)invite:(id)arg1;
@property(retain, nonatomic) UIButton *inviteBtn; // @synthesize inviteBtn=_inviteBtn;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *lineBottom; // @synthesize lineBottom=_lineBottom;
@property(retain, nonatomic) UILabel *nameDescLabel; // @synthesize nameDescLabel=_nameDescLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (void)updateFrameWithDescExist:(_Bool)arg1;

@end

