//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"
#import "UISearchResultsUpdating.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, UISearchBar, UITableView;

__attribute__((visibility("hidden")))
@interface SMSSDKUIZonesResultViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, UISearchResultsUpdating>
{
    UISearchBar *_searchBar;
    NSDictionary *_localList;
    CDUnknownBlockType _itemSeletectedBlock;
    UITableView *_tableView;
    NSDictionary *_dataSources;
    NSArray *_indexArr;
}

- (void).cxx_destruct;
- (void)configUI;
@property(retain, nonatomic) NSDictionary *dataSources; // @synthesize dataSources=_dataSources;
- (void)didReceiveMemoryWarning;
- (void)handleSearchWithText:(id)arg1;
@property(retain, nonatomic) NSArray *indexArr; // @synthesize indexArr=_indexArr;
@property(copy, nonatomic) CDUnknownBlockType itemSeletectedBlock; // @synthesize itemSeletectedBlock=_itemSeletectedBlock;
@property(retain, nonatomic) NSDictionary *localList; // @synthesize localList=_localList;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (id)sectionIndexTitlesForTableView:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

