//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SMSSDKDataService : NSObject
{
}

+ (id)readConfigDic;
+ (id)readContactkey;
+ (id)readCountryZone;
+ (id)readCountryZoneList;
+ (id)readFlagOfContacts;
+ (id)readPhoneNumber;
+ (long long)readTimeFlagWithInfo:(id)arg1;
+ (id)readToken;
+ (void)saveConfigDic:(id)arg1;
+ (void)saveContactkey:(id)arg1;
+ (void)saveCountryZoneList:(id)arg1;
+ (void)saveFlagOfContacts:(id)arg1;
+ (void)savePhoneAndZone;
+ (void)saveSuccessRequestTimeFlagWithInfo:(id)arg1;
+ (void)saveToken:(id)arg1;

@end

