//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMSSDKUIBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, UISearchBar, UISearchController, UITableView;

__attribute__((visibility("hidden")))
@interface SMSSDKUIZonesViewController : SMSSDKUIBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_zonesList;
    UISearchBar *_searchBar;
    CDUnknownBlockType _result;
    NSDictionary *_localList;
    NSDictionary *_dataSources;
    NSArray *_indexArr;
    UISearchController *_searchController;
}

- (void).cxx_destruct;
- (void)cancel:(id)arg1;
- (void)configBack;
- (void)configUI;
@property(retain, nonatomic) NSDictionary *dataSources; // @synthesize dataSources=_dataSources;
@property(retain, nonatomic) NSArray *indexArr; // @synthesize indexArr=_indexArr;
- (id)initWithResult:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSDictionary *localList; // @synthesize localList=_localList;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType result; // @synthesize result=_result;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
- (id)sectionIndexTitlesForTableView:(id)arg1;
@property(retain, nonatomic) UITableView *zonesList; // @synthesize zonesList=_zonesList;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

