//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

__attribute__((visibility("hidden")))
@interface SMSSDKUIZonesCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_zoneCodeLabel;
    UIView *_lineBottom;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)configUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *lineBottom; // @synthesize lineBottom=_lineBottom;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UILabel *zoneCodeLabel; // @synthesize zoneCodeLabel=_zoneCodeLabel;

@end

