//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMOBFPlugin.h"

@class NSMutableSet, NSString;

@interface SSPQQProxy : NSObject <IMOBFPlugin>
{
    NSMutableSet *_authCallbackSet;
    NSMutableSet *_shareCallbackSet;
    id _tencentOAuthInst;
}

- (void).cxx_destruct;
- (_Bool)_authorize:(id)arg1 QQShareType:(long long)arg2;
- (_Bool)_canShareQQ:(id)arg1 callback:(id)arg2;
- (_Bool)_canShareQZone:(id)arg1 callback:(id)arg2;
- (long long)_checkLoginShareType:(long long)arg1;
- (long long)_checkShareType:(long long)arg1;
- (_Bool)_handleOpenURL:(id)arg1;
- (_Bool)_handleOpenURL:(id)arg1 delegate:(id)arg2;
- (_Bool)_isQQSupportSSOLogin;
- (_Bool)_isSupportApi;
- (_Bool)_isTIMClientInstalled;
- (_Bool)_isTIMSupportApi;
- (_Bool)_isTIMSupportSSOLogin;
- (id)_registerApp:(id)arg1;
- (void)_registerAuthMethod;
- (void)_registerExtensionShare;
- (void)_registerHandleSSOCallbackMethod;
- (void)_registerHandlerShareCallbackMethod;
- (void)_registerSetupApp;
- (void)_registerShareMethod;
- (void)_sendAudio:(id)arg1 scene:(unsigned long long)arg2 callback:(id)arg3;
- (void)_sendImageToQQ:(id)arg1 callback:(id)arg2;
- (void)_sendImageToQZone:(id)arg1 callback:(id)arg2;
- (void)_sendTextToQQ:(id)arg1 callback:(id)arg2;
- (void)_sendTextToQZone:(id)arg1 callback:(id)arg2;
- (void)_sendVideo:(id)arg1 scene:(unsigned long long)arg2 callback:(id)arg3;
- (void)_sendWebpage:(id)arg1 scene:(unsigned long long)arg2 callback:(id)arg3;
- (void)_setupAppId:(id)arg1;
@property(retain, nonatomic) NSMutableSet *authCallbackSet; // @synthesize authCallbackSet=_authCallbackSet;
- (void)dealloc;
- (id)init;
- (_Bool)isClientInstalled;
- (_Bool)isQQClientInstalled;
- (_Bool)isQZoneClientInstalled;
- (void)load:(id)arg1;
- (void)onReq:(id)arg1;
- (void)onResp:(id)arg1;
- (void)registerMethod;
- (void)sendStoryResponse:(id)arg1;
@property(retain, nonatomic) NSMutableSet *shareCallbackSet; // @synthesize shareCallbackSet=_shareCallbackSet;
@property(retain, nonatomic) id tencentOAuthInst; // @synthesize tencentOAuthInst=_tencentOAuthInst;
- (void)tencentDidLogin;
- (void)tencentDidNotLogin:(_Bool)arg1;
- (void)tencentDidNotNetWork;
- (void)unload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

