//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSPSMSCell.h"

@class UILabel, UITextField;

@interface SSPSMSPhoneNumCell : SSPSMSCell
{
    UILabel *_titleLabel;
    UITextField *_textField;
}

- (void).cxx_destruct;
- (_Bool)checkPhoneNum;
- (id)init;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

