//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSPSMSCell.h"

@class UIButton;

@interface SSPSMSButtonCell : SSPSMSCell
{
    UIButton *_actButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *actButton; // @synthesize actButton=_actButton;
- (id)init;

@end

