//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSPSliceUpload.h"

#import "ISSPSliceUpload.h"

@class NSString;

@interface SSPTwitterSliceUpload : SSPSliceUpload <ISSPSliceUpload>
{
}

- (id)checkMedia:(id)arg1;
- (void)oauthServiceWithModel:(id)arg1 paramters:(id)arg2 resultEvent:(CDUnknownBlockType)arg3 progressEvent:(CDUnknownBlockType)arg4;
- (unsigned long long)setPlatform;
- (id)setPlatformName;
- (void)upLoadAppend:(id)arg1;
- (void)upLoadFinalize:(id)arg1;
- (void)upLoadInit:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

