//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPopoverControllerDelegate.h"

@class NSString, SSUIBaseShareActionSheet, SSUIPageView;

@interface SSUIiPadShareActionSheetViewController : UIViewController <UIPopoverControllerDelegate>
{
    SSUIPageView *_pageView;
    long long _itemsCount;
    SSUIBaseShareActionSheet *_shareActionSheet;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithItems:(id)arg1;
@property(nonatomic) long long itemsCount; // @synthesize itemsCount=_itemsCount;
- (long long)preferredStatusBarStyle;
@property(nonatomic) __weak SSUIBaseShareActionSheet *shareActionSheet; // @synthesize shareActionSheet=_shareActionSheet;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showInView:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

