//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class SSUIBaseShareActionSheet, SSUIShareActionSheetItem, UIImageView, UILabel;

@interface SSUIShareActinoSheetItemView : UIButton
{
    UILabel *_nameLabel;
    UIImageView *_platformIcon;
    SSUIShareActionSheetItem *_baseItem;
    long long _index;
    double _itemW;
    SSUIShareActionSheetItem *_item;
    SSUIBaseShareActionSheet *_shareActionSheet;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) long long index; // @synthesize index=_index;
- (id)initWithIndex:(long long)arg1 itemW:(double)arg2 itemH:(double)arg3;
@property(nonatomic) __weak SSUIShareActionSheetItem *item; // @synthesize item=_item;
- (void)itemClicked:(id)arg1;
@property(nonatomic) double itemW; // @synthesize itemW=_itemW;
- (void)layoutSubviews;
@property(nonatomic) __weak SSUIBaseShareActionSheet *shareActionSheet; // @synthesize shareActionSheet=_shareActionSheet;

@end

