//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIWindow;

__attribute__((visibility("hidden")))
@interface SWActionSheet : UIView
{
    UIWindow *SWActionSheetWindow;
    UIView *view;
    UIView *_bgView;
    _Bool _presented;
}

- (void).cxx_destruct;
- (id)actionSheetContainer;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
- (void)configureFrameForBounds:(struct CGRect)arg1;
- (void)destroyWindow;
- (void)dismissWithClickedButtonIndex:(int)arg1 animated:(_Bool)arg2;
- (id)initWithView:(id)arg1;
@property(nonatomic) _Bool presented; // @synthesize presented=_presented;
- (void)showFromBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)showInContainerView;
- (void)showInContainerViewAnimated:(_Bool)arg1;
- (id)window;

@end

