//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface SysUtils : NSObject
{
}

+ (void)addBlurEffectToView:(id)arg1;
+ (void)clearEdgesForViewController:(id)arg1;
+ (void)configBuglyUserId;
+ (void)customizeBarButonForController:(id)arg1;
+ (void)customizeBarForNavigationController:(id)arg1 withBackgroundImage:(id)arg2;
+ (id)dateStringFromDate:(id)arg1;
+ (id)dateStringFromTimestamp:(long long)arg1;
+ (id)deviceName;
+ (id)deviceResolution;
+ (id)deviceUDID;
+ (unsigned long long)folderSize:(id)arg1;
+ (id)getAppVersion;
+ (unsigned long long)getAppVersionNumber;
+ (id)getBuildVersion;
+ (void)hideTabBar:(_Bool)arg1;
+ (id)imageNamedEx:(id)arg1;
+ (_Bool)isIPhone4;
+ (_Bool)isIPhone4OrEarlier;
+ (_Bool)isIPhone5;
+ (_Bool)isIPhone5OrEarlier;
+ (_Bool)isIPhone6OrLater;
+ (_Bool)isIPhone6_4_7;
+ (_Bool)isIPhone6_5_5;
+ (_Bool)isIPhoneX;
+ (_Bool)isRetinaDisplay;
+ (id)modelName;
+ (id)packString:(id)arg1 withK:(id)arg2;
+ (id)platformName;
+ (void)playSoundInPath:(id)arg1;
+ (void)registerPush;
+ (void)removeBlurEffectInView:(id)arg1;
+ (void)removeOldCaches;
+ (id)secondsToHHmmss:(long long)arg1;
+ (void)showStatWindow;
+ (id)stringForCount:(long long)arg1;
+ (id)stringForViewCount:(long long)arg1;
+ (void)swizzleClassSelector:(SEL)arg1 ofClass:(Class)arg2 withNewSelector:(SEL)arg3;
+ (void)swizzleSelector:(SEL)arg1 ofClass:(Class)arg2 withNewSelector:(SEL)arg3;
+ (id)unpackString:(id)arg1 withK:(id)arg2;
+ (float)usedMemory;

@end

