//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TCWebViewControllerDelegate.h"

@class NSMutableArray, NSString, TCWebViewController, UIWindow;

@interface TCWebViewKit : NSObject <TCWebViewControllerDelegate>
{
    _Bool _isStatusBarHidden;
    _Bool _isClosing;
    UIWindow *_window;
    UIWindow *_keywindow;
    NSMutableArray *_windowsArray;
    TCWebViewController *_webViewController;
    NSString *_requestUrl;
    NSString *_webTitle;
    id <TCWebViewKitDelegate> _delegate;
}

- (void)MoveOtherWindowIntoFrame;
- (void)MoveOtherWindowOutOfFrame;
- (void)MoveWindowIntoFrame;
- (void)MoveWindowOutOfFrame:(_Bool)arg1;
- (void)animationFinished:(id)arg1 finished:(_Bool)arg2 context:(void *)arg3;
- (struct CGRect)calcFrameByOrientation:(int)arg1;
- (void)closeWindow;
- (id)createNavigationBarButton:(id)arg1 bindingJS:(id)arg2;
- (void)dealloc;
@property(nonatomic) id <TCWebViewKitDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doClose;
- (void)doCloseWithNotAnimation;
- (id)getViewControllerWithUrl:(id)arg1 webTitle:(id)arg2 delegate:(id)arg3;
- (id)initWithUrl:(id)arg1 webTitle:(id)arg2 delegate:(id)arg3;
@property(retain, nonatomic) UIWindow *keywindow; // @synthesize keywindow=_keywindow;
- (void)loadReqURL:(id)arg1 webTitle:(id)arg2 delegate:(id)arg3;
- (void)onClickBarButton:(id)arg1;
- (void)onClickClose;
- (_Bool)open;
- (void)openWithUrl:(id)arg1 webTitle:(id)arg2 delegate:(id)arg3;
@property(retain, nonatomic) NSString *requestUrl; // @synthesize requestUrl=_requestUrl;
- (struct CGRect)screenRectOrientationIndependent;
- (void)setLeftNavigationBarButton:(id)arg1 bindingJS:(id)arg2;
- (void)setNavigationBarHidden:(id)arg1 animated:(id)arg2;
- (void)setNavigationTitle:(id)arg1;
- (void)setRightNavigationBarButton:(id)arg1 bindingJS:(id)arg2;
@property(retain, nonatomic) NSString *webTitle; // @synthesize webTitle=_webTitle;
@property(retain, nonatomic) TCWebViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) NSMutableArray *windowsArray; // @synthesize windowsArray=_windowsArray;
- (_Bool)shouldAutorotateWithWebVC:(id)arg1;
- (unsigned long long)supportedInterfaceOrientationsWithWebVC:(id)arg1;
- (void)webViewController:(id)arg1 didCloseWithLastError:(id)arg2;
- (void)webViewController:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webViewController:(id)arg1 shouldAutorotateToInterfaceOrientation:(long long)arg2;
- (_Bool)webViewController:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

