//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TTURLRequestDelegate.h"

@class NSData, NSString, TLThumbView, TTURLRequest;

__attribute__((visibility("hidden")))
@interface TLButtonContent : NSObject <TTURLRequestDelegate>
{
    TLThumbView *_button;
    NSString *_imageURL;
    NSData *_GIFData;
    TTURLRequest *_request;
    id <TLImageViewDelegate> _delegate;
    _Bool _loaded;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *GIFData; // @synthesize GIFData=_GIFData;
- (void)dealloc;
@property(nonatomic) __weak id <TLImageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (id)initWithButton:(id)arg1;
@property(nonatomic) _Bool loaded; // @synthesize loaded=_loaded;
- (void)reload;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidCancelLoad:(id)arg1;
- (void)requestDidDownloadData:(id)arg1;
- (void)requestDidFinishLoad:(id)arg1;
- (void)requestDidStartLoad:(id)arg1;
- (void)stopLoading;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

