//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTImageViewDelegate.h"

@class NSData, TTImageView;

@protocol TLImageViewDelegate <TTImageViewDelegate>

@optional
- (void)imageView:(TTImageView *)arg1 didLoadImageData:(NSData *)arg2;
- (void)imageView:(TTImageView *)arg1 didUpdateProgress:(float)arg2;
@end

