//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFUITableController.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface TLListSelectorController : WFUITableController
{
    id <TLListSelectorDelegate> delegate;
    NSString *identifier;
    _Bool singleSelectionForAll;
    _Bool allowsMultipleSelection;
    NSMutableDictionary *selectedRows;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection;
- (void)dealloc;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier;
- (id)initWithDelegate:(id)arg1 title:(id)arg2 identifier:(id)arg3;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) _Bool singleSelectionForAll; // @synthesize singleSelectionForAll;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

@end

