//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TLGIFImageViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, TLButtonContent, UIImage, UIImageView, UIImageView<TLGIFImageViewProtocol>, UILabel, UITapGestureRecognizer;

__attribute__((visibility("hidden")))
@interface TLThumbView : UIView <TLGIFImageViewDelegate, UIGestureRecognizerDelegate>
{
    TLButtonContent *_content;
    UITapGestureRecognizer *_tapRecognizer;
    UIImageView *_emptyView;
    UIImageView *_gifTagView;
    UILabel *_longPicTagView;
    UIView *_progressView;
    _Bool _isLoaded;
    _Bool _isLoading;
    _Bool _showAsGIF;
    _Bool _showAsLongPic;
    _Bool _showProgress;
    _Bool _tapEnabled;
    _Bool _hasBlurEffect;
    UIImageView<TLGIFImageViewProtocol> *_gifImageView;
    id <TLImageViewDelegate> _imageDelegate;
    id <TLThumbViewDelegate> _delegate;
    UIImage *_defaultImage;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
@property(nonatomic) __weak id <TLThumbViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFailDownload;
- (void)didFailLoad;
- (void)didFinishDownload;
- (void)didFinishLoad;
- (void)didStartDownload;
- (void)didUpdateDownloadProgress:(float)arg1;
- (void)displayWithData:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
@property(readonly, nonatomic) UIImageView<TLGIFImageViewProtocol> *gifImageView; // @synthesize gifImageView=_gifImageView;
@property(nonatomic) _Bool hasBlurEffect; // @synthesize hasBlurEffect=_hasBlurEffect;
@property(retain, nonatomic) UIImage *image;
@property(nonatomic) __weak id <TLImageViewDelegate> imageDelegate; // @synthesize imageDelegate=_imageDelegate;
- (void)imageView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)imageViewDidFinishLoad:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded=_isLoaded;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(readonly, nonatomic) UILabel *longPicTagView; // @synthesize longPicTagView=_longPicTagView;
- (void)reload;
- (void)setProgress:(float)arg1;
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;
- (void)setProgressColor:(id)arg1;
@property(nonatomic) _Bool showAsGIF; // @synthesize showAsGIF=_showAsGIF;
@property(nonatomic) _Bool showAsLongPic; // @synthesize showAsLongPic=_showAsLongPic;
@property(nonatomic) _Bool showProgress; // @synthesize showProgress=_showProgress;
@property(nonatomic) _Bool tapEnabled; // @synthesize tapEnabled=_tapEnabled;
@property(copy, nonatomic) NSString *thumbURL;
- (void)showEmpty:(_Bool)arg1;
- (void)stopLoading;
- (void)suspend:(_Bool)arg1;
- (void)tapped:(id)arg1;
- (void)unsetImage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

