//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTModelViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class JYCollectionView, NSString, UICollectionView, UICollectionViewLayout, UIView;

__attribute__((visibility("hidden")))
@interface TTCollectionViewController : TTModelViewController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    JYCollectionView *_collectionView;
    UIView *_loadingView;
    UIView *_errorView;
    UIView *_emptyView;
    UICollectionViewLayout *_collectionViewLayout;
    long long _lastInterfaceOrientation;
    UIView *_overlayView;
}

- (void)addToOverlayView:(id)arg1;
- (_Bool)canShowModel;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)dealloc;
- (void)didLoadModel:(_Bool)arg1;
- (void)didShowModel:(_Bool)arg1;
@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) UIView *errorView; // @synthesize errorView=_errorView;
- (void)fadeOutView:(id)arg1;
- (void)fadingOutViewDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (id)imageForEmpty;
- (id)imageForError:(id)arg1;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)layoutOverlayView;
- (void)loadView;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
- (void)model:(id)arg1 didDeleteObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didInsertObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didUpdateObject:(id)arg2 atIndexPath:(id)arg3;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
- (struct CGRect)rectForOverlayView;
- (_Bool)reloadButtonForEmpty;
- (void)resetOverlayView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)setcollectionView:(id)arg1;
- (void)setoverlayView:(id)arg1 animated:(_Bool)arg2;
- (void)showEmpty:(_Bool)arg1;
- (void)showError:(_Bool)arg1;
- (void)showLoading:(_Bool)arg1;
- (void)showModel:(_Bool)arg1;
- (id)subtitleForEmpty;
- (id)subtitleForError:(id)arg1;
- (id)titleForEmpty;
- (id)titleForError:(id)arg1;
- (id)titleForLoading:(_Bool)arg1;
- (void)updateTableDelegate;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

