//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTViewController.h"

#import "TTModelDelegate.h"

@class NSError, NSString;

__attribute__((visibility("hidden")))
@interface TTModelViewController : TTViewController <TTModelDelegate>
{
    id <TTModel> _model;
    NSError *_modelError;
    struct {
        unsigned int isModelDidRefreshInvalid:1;
        unsigned int isModelWillLoadInvalid:1;
        unsigned int isModelDidLoadInvalid:1;
        unsigned int isModelDidLoadFirstTimeInvalid:1;
        unsigned int isModelDidShowFirstTimeInvalid:1;
        unsigned int isViewInvalid:1;
        unsigned int isViewSuspended:1;
        unsigned int isUpdatingView:1;
        unsigned int isShowingEmpty:1;
        unsigned int isShowingLoading:1;
        unsigned int isShowingModel:1;
        unsigned int isShowingError:1;
    } _flags;
}

- (void)beginUpdates;
- (_Bool)canShowModel;
- (void)createInterstitialModel;
- (void)createModel;
- (void)dealloc;
- (void)delayDidEnd;
- (void)didLoadModel:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)didRefreshModel;
- (void)didShowModel:(_Bool)arg1;
- (void)endUpdates;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)invalidateModel;
- (void)invalidateView;
- (_Bool)isModelCreated;
@property(retain, nonatomic) id <TTModel> model; // @synthesize model=_model;
- (void)model:(id)arg1 didDeleteObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)model:(id)arg1 didInsertObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didUpdateObject:(id)arg2 atIndexPath:(id)arg3;
- (void)modelDidBeginUpdates:(id)arg1;
- (void)modelDidCancelLoad:(id)arg1;
- (void)modelDidChange:(id)arg1;
- (void)modelDidEndUpdates:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
@property(retain, nonatomic) NSError *modelError; // @synthesize modelError=_modelError;
- (void)refresh;
- (void)reload;
- (void)reloadIfNeeded;
- (void)resetViewStates;
- (_Bool)shouldLoad;
- (_Bool)shouldLoadMore;
- (_Bool)shouldReload;
- (void)showEmpty:(_Bool)arg1;
- (void)showError:(_Bool)arg1;
- (void)showLoading:(_Bool)arg1;
- (void)showModel:(_Bool)arg1;
- (void)updateView;
- (void)updateViewStates;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willLoadModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

