//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTImageView.h"

#import "TTImageViewDelegate.h"

@class NSString, TLInsetLabel, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface TTPhotoView : TTImageView <TTImageViewDelegate>
{
    id <TTPhoto> _photo;
    UIActivityIndicatorView *_statusSpinner;
    TLInsetLabel *_statusLabel;
    TLInsetLabel *_captionLabel;
    int _photoVersion;
    _Bool _hidesExtras;
    _Bool _hidesCaption;
}

- (void)dealloc;
@property(nonatomic) _Bool hidesCaption; // @synthesize hidesCaption=_hidesCaption;
@property(nonatomic) _Bool hidesExtras; // @synthesize hidesExtras=_hidesExtras;
- (void)imageViewDidFailLoadWithError:(id)arg1;
- (void)imageViewDidLoadImage:(id)arg1;
- (void)imageViewDidStartLoad;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)loadImage;
- (_Bool)loadPreview:(_Bool)arg1;
- (_Bool)loadVersion:(int)arg1 fromNetwork:(_Bool)arg2;
@property(retain, nonatomic) id <TTPhoto> photo; // @synthesize photo=_photo;
- (void)setImage:(id)arg1;
- (void)showCaption:(id)arg1;
- (void)showProgress:(double)arg1;
- (void)showStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

