//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSHTTPURLResponse, NSMutableArray, NSMutableData, NSString, NSURLConnection, TTURLRequestQueue;

@interface TTRequestLoader : NSObject
{
    NSString *_urlPath;
    TTURLRequestQueue *_queue;
    NSString *_cacheKey;
    int _cachePolicy;
    double _cacheExpirationAge;
    NSMutableArray *_requests;
    NSURLConnection *_connection;
    NSHTTPURLResponse *_response;
    NSMutableData *_responseData;
    int _retriesLeft;
}

@property(readonly, nonatomic) NSString *URL;
- (void)addRequest:(id)arg1;
@property(readonly, nonatomic) double cacheExpirationAge; // @synthesize cacheExpirationAge=_cacheExpirationAge;
@property(readonly, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(readonly, nonatomic) int cachePolicy; // @synthesize cachePolicy=_cachePolicy;
- (void)cancel;
- (_Bool)cancel:(id)arg1;
- (void)connectToURL:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
- (void)deliverDataResponse:(id)arg1;
- (void)dispatchAuthenticationChallenge:(id)arg1;
- (void)dispatchDownloadProgress;
- (void)dispatchError:(id)arg1;
- (void)dispatchLoaded:(id)arg1;
- (void)dispatchLoadedBytes:(long long)arg1 expected:(long long)arg2;
- (id)initForRequest:(id)arg1 queue:(id)arg2;
@property(readonly, nonatomic) _Bool isLoading;
- (void)load:(id)arg1;
- (void)loadSynchronously:(id)arg1;
- (id)processResponse:(id)arg1 data:(id)arg2;
- (void)removeRequest:(id)arg1;
@property(readonly, nonatomic) NSArray *requests; // @synthesize requests=_requests;
@property(readonly, nonatomic) NSString *urlPath; // @synthesize urlPath=_urlPath;

@end

