//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSDictionary, NSMutableArray, NSTimer, UITouch;

__attribute__((visibility("hidden")))
@interface TTScrollView : UIView
{
    long long _centerPageIndex;
    long long _visiblePageIndex;
    _Bool _scrollEnabled;
    _Bool _zoomEnabled;
    _Bool _rotateEnabled;
    double _pageSpacing;
    double _holdsAfterTouchingForInterval;
    long long _orientation;
    id <TTScrollViewDelegate> _delegate;
    id <TTScrollViewDataSource> _dataSource;
    NSMutableArray *_pages;
    NSMutableArray *_pageQueue;
    long long _maxPages;
    long long _pageArrayIndex;
    NSTimer *_tapTimer;
    NSTimer *_holdingTimer;
    NSTimer *_animationTimer;
    NSDate *_animationStartTime;
    double _animationDuration;
    struct UIEdgeInsets _animateEdges;
    struct CGPoint _inertiaSpeed;
    struct CGPoint _renewPosition;
    double _maximumZoomScale;
    double _zoomScale;
    struct CGPoint centerOfFingers;
    double actualDistanceBetweenFingers;
    double distanceBetweenFingers;
    double _decelerationRate;
    struct UIEdgeInsets _pageEdges;
    struct UIEdgeInsets _pageStartEdges;
    struct UIEdgeInsets _touchEdges;
    struct UIEdgeInsets _touchStartEdges;
    unsigned long long _touchCount;
    double _overshoot;
    _Bool _nextLayoutAnimated;
    double _centerPageAnimationDuration;
    UITouch *_touch1;
    UITouch *_touch2;
    _Bool _dragging;
    _Bool _decelerating;
    _Bool _zooming;
    _Bool _executingZoomGesture;
    _Bool _holding;
}

- (void)acquireTouch:(id)arg1;
- (void)adjustPageEdgesForPageAtIndex:(long long)arg1;
- (void)animator;
- (void)animator2;
- (long long)arrayIndexForPageIndex:(long long)arg1 relativeToIndex:(long long)arg2;
- (void)beginHolding;
- (double)calculateZoomScaleUsingFingerDistances;
- (_Bool)canZoom;
- (void)cancelTouches;
@property(readonly, nonatomic) UIView *centerPage;
@property double centerPageAnimationDuration; // @synthesize centerPageAnimationDuration=_centerPageAnimationDuration;
@property(nonatomic) long long centerPageIndex; // @synthesize centerPageIndex=_centerPageIndex;
- (struct UIEdgeInsets)constrainEdges:(struct UIEdgeInsets)arg1 toWidth:(double)arg2;
@property(nonatomic) id <TTScrollViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
@property double decelerationRate; // @synthesize decelerationRate=_decelerationRate;
@property(nonatomic) id <TTScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)dequeueReusablePage;
- (void)deviceOrientationDidChange:(void *)arg1;
- (void)didMoveToSuperview;
- (double)distanceBetweenPointA:(struct CGPoint)arg1 andB:(struct CGPoint)arg2;
- (_Bool)draggingFromEdge;
- (_Bool)edgesAreZoomed:(struct UIEdgeInsets)arg1;
- (void)endHolding;
- (void)enqueueAllPages;
- (id)enqueuePageAtIndex:(long long)arg1;
- (void)ensureTouches;
- (_Bool)flicked;
- (_Bool)flipped;
- (struct CGRect)frameOfPageAtIndex:(long long)arg1;
@property(readonly, nonatomic) _Bool holding; // @synthesize holding=_holding;
- (void)holdingTimer:(id)arg1;
@property(nonatomic) double holdsAfterTouchingForInterval; // @synthesize holdsAfterTouchingForInterval=_holdsAfterTouchingForInterval;
- (void)inertiaAnimator;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic, getter=isDecelerating) _Bool decelerating; // @synthesize decelerating=_decelerating;
@property(readonly) _Bool isDragging; // @synthesize isDragging=_dragging;
- (_Bool)isFirstPage;
- (_Bool)isLastPage;
- (void)layoutAdjacentPages;
- (void)layoutPage;
- (void)layoutSubviews;
@property(nonatomic) double maximumZoomScale; // @synthesize maximumZoomScale=_maximumZoomScale;
- (struct CGPoint)midpointBetweenPointA:(struct CGPoint)arg1 andB:(struct CGPoint)arg2;
- (void)moveToPageAtIndex:(long long)arg1 resetEdges:(_Bool)arg2;
- (void)moveToPageAtIndex:(long long)arg1 resetEdges:(_Bool)arg2 animated:(_Bool)arg3;
@property(readonly, nonatomic) long long numberOfPages;
- (struct CGPoint)offsetForOrientation:(double)arg1 y:(double)arg2;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (double)overflowForFrame:(struct CGRect)arg1;
- (double)overshoot;
- (id)pageAtIndex:(long long)arg1;
- (id)pageAtIndex:(long long)arg1 create:(_Bool)arg2;
- (struct UIEdgeInsets)pageEdgesForAnimation;
- (double)pageHeight;
@property(nonatomic) double pageSpacing; // @synthesize pageSpacing=_pageSpacing;
- (double)pageWidth;
- (_Bool)pinched;
- (_Bool)pulled;
- (long long)realPageIndex;
- (void)reloadData;
- (id)removeTouch:(id)arg1;
- (double)resist:(double)arg1 to:(double)arg2 max:(double)arg3;
- (struct UIEdgeInsets)resistPageEdges:(struct UIEdgeInsets)arg1;
- (struct UIEdgeInsets)reversePageEdges;
@property(nonatomic) _Bool rotateEnabled; // @synthesize rotateEnabled=_rotateEnabled;
- (struct CGAffineTransform)rotateTransform:(struct CGAffineTransform)arg1;
- (void)rotationDidStop;
@property(nonatomic) _Bool scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
- (void)setCenterPageIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)setOrientation:(long long)arg1 animated:(_Bool)arg2;
@property(nonatomic) _Bool zoomEnabled; // @synthesize zoomEnabled=_zoomEnabled;
@property(nonatomic) double zoomScale; // @synthesize zoomScale=_zoomScale;
- (void)setZoomScale:(double)arg1 animated:(_Bool)arg2;
- (void)setZoomScale:(double)arg1 withPoint:(struct CGPoint)arg2 animated:(_Bool)arg3;
- (struct UIEdgeInsets)squareEdgesUsingFingerDistancesAndAnchorPoint:(struct CGPoint)arg1;
- (struct UIEdgeInsets)squareEdgesUsingZoomScale:(double)arg1 andAnchorPoint:(struct CGPoint)arg2;
- (struct UIEdgeInsets)squareTouchEdges:(struct UIEdgeInsets)arg1;
- (void)startAnimationTo:(struct UIEdgeInsets)arg1 duration:(double)arg2;
- (void)startTapTimer:(id)arg1;
- (void)stopAnimation:(_Bool)arg1;
- (void)stopDragging:(_Bool)arg1;
- (struct UIEdgeInsets)stretchTouchEdges:(struct UIEdgeInsets)arg1 toPoint:(struct CGPoint)arg2;
- (double)stretchedHeight;
- (double)stretchedWidth;
- (_Bool)supportsOrientation:(long long)arg1;
- (void)tapTimer:(id)arg1;
- (struct UIEdgeInsets)touchEdgesForPoint:(struct CGPoint)arg1;
- (struct CGPoint)touchLocation:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (double)tween:(double)arg1 b:(double)arg2 c:(double)arg3 d:(double)arg4;
- (void)updateZooming:(struct UIEdgeInsets)arg1;
@property(readonly, nonatomic) NSDictionary *visiblePages;
- (double)zoomFactor;
- (struct UIEdgeInsets)zoomPageEdgesTo:(struct CGPoint)arg1;
- (void)zoomToDistance:(double)arg1;
- (void)zoomToFit;
@property(readonly, nonatomic) _Bool zoomed;
@property(readonly, nonatomic) _Bool zooming; // @synthesize zooming=_executingZoomGesture;

@end

