//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface TTURLRequest : NSObject
{
    NSString *_urlPath;
    NSString *_redirectedUrlPath;
    NSString *_httpMethod;
    NSData *_httpBody;
    NSMutableDictionary *_parameters;
    NSMutableDictionary *_headers;
    NSString *_contentType;
    unsigned long long _charsetForMultipart;
    NSMutableArray *_files;
    id <TTURLResponse> _response;
    int _cachePolicy;
    double _cacheExpirationAge;
    NSString *_cacheKey;
    NSDate *_timestamp;
    long long _totalBytesLoaded;
    long long _totalBytesExpected;
    double _timeoutInterval;
    long long _totalBytesDownloaded;
    long long _totalContentLength;
    id _userInfo;
    _Bool _isLoading;
    _Bool _shouldHandleCookies;
    _Bool _respondedFromCache;
    _Bool _filterPasswordLogging;
    _Bool _multiPartForm;
    NSMutableArray *_delegates;
}

+ (id)request;
+ (id)requestWithURL:(id)arg1 delegate:(id)arg2;
@property(copy, nonatomic) NSString *URL;
- (void)addFile:(id)arg1 mimeType:(id)arg2 fileName:(id)arg3;
- (void)appendImageData:(id)arg1 withName:(id)arg2 toBody:(id)arg3;
@property(nonatomic) double cacheExpirationAge; // @synthesize cacheExpirationAge=_cacheExpirationAge;
@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(nonatomic) int cachePolicy; // @synthesize cachePolicy=_cachePolicy;
- (void)cancel;
@property(nonatomic) unsigned long long charsetForMultipart; // @synthesize charsetForMultipart=_charsetForMultipart;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
- (id)createNSURLRequest;
- (void)dealloc;
@property(readonly, nonatomic) NSMutableArray *delegates; // @synthesize delegates=_delegates;
- (id)description;
@property(nonatomic) _Bool filterPasswordLogging; // @synthesize filterPasswordLogging=_filterPasswordLogging;
- (id)generateCacheKey;
- (id)generateNonMultipartPostBody;
- (id)generatePostBody;
@property(readonly, nonatomic) NSMutableDictionary *headers; // @synthesize headers=_headers;
@property(retain, nonatomic) NSData *httpBody; // @synthesize httpBody=_httpBody;
@property(copy, nonatomic) NSString *httpMethod; // @synthesize httpMethod=_httpMethod;
- (id)init;
- (id)initWithURL:(id)arg1 delegate:(id)arg2;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool multiPartForm; // @synthesize multiPartForm=_multiPartForm;
@property(readonly, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *redirectedUrlPath; // @synthesize redirectedUrlPath=_redirectedUrlPath;
@property(nonatomic) _Bool respondedFromCache; // @synthesize respondedFromCache=_respondedFromCache;
@property(retain, nonatomic) id <TTURLResponse> response; // @synthesize response=_response;
- (_Bool)send;
- (_Bool)sendSynchronously;
@property(nonatomic) _Bool shouldHandleCookies; // @synthesize shouldHandleCookies=_shouldHandleCookies;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long totalBytesDownloaded; // @synthesize totalBytesDownloaded=_totalBytesDownloaded;
@property(nonatomic) long long totalBytesExpected; // @synthesize totalBytesExpected=_totalBytesExpected;
@property(nonatomic) long long totalBytesLoaded; // @synthesize totalBytesLoaded=_totalBytesLoaded;
@property(nonatomic) long long totalContentLength; // @synthesize totalContentLength=_totalContentLength;
@property(copy, nonatomic) NSString *urlPath; // @synthesize urlPath=_urlPath;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;

@end

