//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (Reachability)
+ (_Bool)addressFromString:(id)arg1 address:(struct sockaddr_in *)arg2;
+ (id)stringFromAddress:(const struct sockaddr *)arg1;
- (_Bool)activeWLAN;
- (_Bool)activeWWAN;
- (_Bool)forceWWAN;
- (id)getIPAddressForHost:(id)arg1;
- (_Bool)hostAvailable:(id)arg1;
- (id)hostname;
- (id)localIPAddress;
- (id)localWiFiIPAddress;
- (_Bool)networkAvailable;
- (_Bool)performWiFiCheck;
- (void)pingReachabilityInternal;
- (void)privateShowAlert:(id)arg1;
- (_Bool)scheduleReachabilityWatcher:(id)arg1;
- (void)shutdownWWAN;
- (void)unscheduleReachabilityWatcher;
- (id)whatismyipdotcom;
@end

