//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (TTCategory)
- (void)addRoundedRectToPath:(struct CGContext *)arg1 rect:(struct CGRect)arg2 radius:(float)arg3;
- (struct CGRect)convertRect:(struct CGRect)arg1 withContentMode:(long long)arg2;
- (void)drawInRect:(struct CGRect)arg1 contentMode:(long long)arg2;
- (void)drawInRect:(struct CGRect)arg1 radius:(double)arg2;
- (void)drawInRect:(struct CGRect)arg1 radius:(double)arg2 contentMode:(long long)arg3;
- (id)transformWidth:(double)arg1 height:(double)arg2 rotate:(_Bool)arg3;
@end

