//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (WBSDKSizes)
@property(nonatomic) double wbsdkBottom;
@property(nonatomic) double wbsdkCenterX;
@property(nonatomic) double wbsdkCenterY;
@property(nonatomic) double wbsdkHeight;
@property(nonatomic) double wbsdkLeft;
@property(nonatomic) struct CGPoint wbsdkOrigin;
@property(nonatomic) double wbsdkRight;
@property(nonatomic) struct CGSize wbsdkSize;
@property(nonatomic) double wbsdkTop;
@property(nonatomic) double wbsdkWidth;
@end

