//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue, NSString;

@interface UMOnlineConfig : NSObject
{
    NSOperationQueue *_otherQueue;
    _Bool _logEnabled;
    NSString *_appKey;
}

+ (id)arrayParams:(id)arg1;
+ (id)boolParams:(id)arg1;
+ (id)configParams;
+ (id)configParams:(id)arg1;
+ (void)fetchData;
+ (void)initWithAppkey:(id)arg1;
+ (id)numberParams:(id)arg1;
+ (void)setLogEnabled:(_Bool)arg1;
+ (id)sharedInstance;
+ (id)stringParams:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
- (id)assembleUrl;
- (void)checkOnlineUpdateTime;
- (void)fetchData;
- (id)init;
- (void)initWithAppkey:(id)arg1;
@property(nonatomic) _Bool logEnabled; // @synthesize logEnabled=_logEnabled;
- (id)onlineConfig;
- (id)onlineConfigWithKey:(id)arg1;
@property(retain, nonatomic) NSOperationQueue *otherQueue; // @synthesize otherQueue=_otherQueue;
- (void)postOnlineConfigDidFinishedNotification;
- (_Bool)processData:(id)arg1;
- (id)responseFromUrl:(id)arg1;
- (void)saveConfigure:(id)arg1;
- (id)umengID;
- (void)updateOnlineConfigWithAppkey:(id)arg1;

@end

