//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RennParam.h"

@class NSData, NSString;

@interface UploadPhotoParam : RennParam
{
    NSString *_albumId;
    NSString *_desc;
    NSData *_file;
}

@property(retain, nonatomic) NSString *albumId; // @synthesize albumId=_albumId;
- (void)dealloc;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSData *file; // @synthesize file=_file;
- (id)init;

@end

