//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UpSimpleHttpClient;

__attribute__((visibility("hidden")))
@interface UpYunFormUploader : NSObject
{
    UpSimpleHttpClient *_httpClient;
    long long _totalUnitCountToSend;
}

- (void).cxx_destruct;
- (void)cancel;
- (void)dealloc;
- (void)uploadWithBucketName:(id)arg1 operator:(id)arg2 password:(id)arg3 fileData:(id)arg4 fileName:(id)arg5 saveKey:(id)arg6 otherParameters:(id)arg7 success:(CDUnknownBlockType)arg8 failure:(CDUnknownBlockType)arg9 progress:(CDUnknownBlockType)arg10;
- (void)uploadWithOperator:(id)arg1 policy:(id)arg2 signature:(id)arg3 fileData:(id)arg4 fileName:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7 progress:(CDUnknownBlockType)arg8;

@end

