//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WBNewVideoObject : NSObject
{
    _Bool _isShareToStory;
    id <WBMediaTransferProtocol> _delegate;
    NSString *_finalAsset;
}

+ (id)dictionaryWithVideoObject:(id)arg1;
+ (id)object;
+ (id)videoObjectWithDictionary:(id)arg1;
- (void).cxx_destruct;
- (void)addVideo:(id)arg1;
- (void)addVideoAsset:(id)arg1;
@property(nonatomic) __weak id <WBMediaTransferProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *finalAsset; // @synthesize finalAsset=_finalAsset;
@property(nonatomic) _Bool isShareToStory; // @synthesize isShareToStory=_isShareToStory;
- (id)validate;

@end

