//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface WebPImageUtils : NSObject
{
}

+ (id)commonDataFromWebp:(id)arg1 isGIF:(_Bool)arg2;
+ (void)setWebPImageSupported:(_Bool)arg1;
+ (_Bool)webpImageSupported;

@end

