//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TTImageView, UILabel, WFAlbum, WFDigButton, WFFavoriteButton, WFShareButton;

__attribute__((visibility("hidden")))
@interface WFAlbumHeaderView : UIView
{
    WFAlbum *_album;
    TTImageView *_imageView2;
    UILabel *_bodyLabel;
    WFDigButton *_digUpButton;
    WFShareButton *_shareButton;
    WFFavoriteButton *_favoriteButton;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)dig:(id)arg1;
- (void)favorite:(id)arg1;
- (id)initWithAlbum:(id)arg1;
- (void)share:(id)arg1;

@end

