//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface WFAppUtils : NSObject
{
}

+ (id)currentPageCode;
+ (int)defaultWeiboType;
+ (id)errorReportSubjectWithInfo:(id)arg1;
+ (id)feedbackBody;
+ (id)feedbackSubject;
+ (id)rootViewController;
+ (id)visibleViewController;
+ (id)window;

@end

