//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTURLRequestModel.h"

@class NSDictionary, NSMutableArray, NSString, WFWeibo;

__attribute__((visibility("hidden")))
@interface WFCommentsModel : TTURLRequestModel
{
    WFWeibo *_weibo;
    NSString *_fid;
    NSString *_aid;
    int _wtype;
    int _source;
    long long _repliedCid;
    NSString *_postUpdateTime;
    _Bool _getPost;
    _Bool _getOnlyReplies;
    _Bool _shouldLoadFromWeb;
    _Bool _lastLoadSucceed;
    NSMutableArray *_items;
    NSMutableArray *_hotItems;
    NSMutableArray *_recommendedVideos;
    NSDictionary *_emojiRainConfig;
    long long _commentTotal;
    long long _replyCount;
    long long _pageIndex;
    NSString *_errorMsg;
    NSString *_errorDetail;
}

- (void).cxx_destruct;
- (void)__init;
@property(readonly, nonatomic) _Bool canLoadMore;
@property(readonly, nonatomic) long long commentTotal; // @synthesize commentTotal=_commentTotal;
- (void)dealloc;
@property(retain, nonatomic) NSDictionary *emojiRainConfig; // @synthesize emojiRainConfig=_emojiRainConfig;
@property(copy, nonatomic) NSString *errorDetail; // @synthesize errorDetail=_errorDetail;
@property(copy, nonatomic) NSString *errorMsg; // @synthesize errorMsg=_errorMsg;
@property(retain, nonatomic) NSMutableArray *hotItems; // @synthesize hotItems=_hotItems;
- (id)initWithAlbumID:(id)arg1 fid:(id)arg2 wtype:(int)arg3;
- (id)initWithFid:(id)arg1 wtype:(int)arg2 source:(int)arg3;
- (id)initWithFid:(id)arg1 wtype:(int)arg2 source:(int)arg3 onlyReplies:(_Bool)arg4 getPost:(_Bool)arg5;
- (id)initWithPostUpdateTime:(id)arg1 wtype:(int)arg2;
- (id)initWithRepliedComment:(id)arg1;
- (id)initWithWeibo:(id)arg1;
- (long long)insertNewComment:(id)arg1 aboveComment:(id)arg2;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) _Bool lastLoadSucceed; // @synthesize lastLoadSucceed=_lastLoadSucceed;
- (void)load:(int)arg1 more:(_Bool)arg2;
- (id)loadFromEntries:(id)arg1 isNewest:(_Bool)arg2;
- (unsigned long long)loadFromRootObject:(id)arg1;
@property(readonly, nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(retain, nonatomic) NSMutableArray *recommendedVideos; // @synthesize recommendedVideos=_recommendedVideos;
@property(readonly, nonatomic) long long replyCount; // @synthesize replyCount=_replyCount;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
@property(retain, nonatomic) WFWeibo *weibo; // @synthesize weibo=_weibo;

@end

