//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSString, WFWeibo;

__attribute__((visibility("hidden")))
@interface WFComment : NSObject
{
    _Bool _fromRobot;
    _Bool _isHidden;
    _Bool _isHot;
    _Bool _allBadgesOn;
    int _wtype;
    int _platform;
    NSString *_content;
    NSString *_authorName;
    NSString *_authorAvatar;
    NSDate *_createTime;
    long long _likes;
    long long _dislikes;
    NSString *_wid;
    long long _cid;
    long long _replyID;
    NSString *_uid;
    WFWeibo *_weibo;
    NSArray *_userLevels;
}

+ (id)objectFromData:(id)arg1 fromWeibo:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) _Bool allBadgesOn; // @synthesize allBadgesOn=_allBadgesOn;
@property(copy, nonatomic) NSString *authorAvatar; // @synthesize authorAvatar=_authorAvatar;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(nonatomic) long long cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSDate *createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long dislikes; // @synthesize dislikes=_dislikes;
@property(nonatomic) _Bool fromRobot; // @synthesize fromRobot=_fromRobot;
@property(nonatomic) _Bool isHidden; // @synthesize isHidden=_isHidden;
@property(nonatomic) _Bool isHot; // @synthesize isHot=_isHot;
@property(nonatomic) long long likes; // @synthesize likes=_likes;
@property(nonatomic) int platform; // @synthesize platform=_platform;
@property(nonatomic) long long replyID; // @synthesize replyID=_replyID;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSArray *userLevels; // @synthesize userLevels=_userLevels;
@property(retain, nonatomic) WFWeibo *weibo; // @synthesize weibo=_weibo;
@property(copy, nonatomic) NSString *wid; // @synthesize wid=_wid;
@property(nonatomic) int wtype; // @synthesize wtype=_wtype;

@end

