//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSlideSegmentController.h"

#import "JYSlideSegmentDelegate.h"
#import "MBProgressHUDDelegate.h"
#import "TTURLRequestDelegate.h"

@class MBProgressHUD, NSString;

__attribute__((visibility("hidden")))
@interface WFCommentRepliesController : WFSlideSegmentController <JYSlideSegmentDelegate, TTURLRequestDelegate, MBProgressHUDDelegate>
{
    MBProgressHUD *_hud;
    int _clearingType;
}

- (void).cxx_destruct;
- (void)clearAll:(id)arg1;
- (void)dealloc;
- (void)hudWasHidden:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)markNewReplies;
- (void)newReplyCountUpdated:(id)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
- (void)slideSegmentDidTapAgain:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

