//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface WFCommentDigButton : UIControl
{
    _Bool _digged;
    UILabel *_titleLabel;
    UIImageView *_iconView;
    unsigned long long _digCount;
}

- (void).cxx_destruct;
- (void)adjustSize;
@property(nonatomic) unsigned long long digCount; // @synthesize digCount=_digCount;
@property(nonatomic) _Bool digged; // @synthesize digged=_digged;
@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setDigged:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

