//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFTTTableController.h"

#import "TLThumbViewDelegate.h"
#import "WFNativeAdRefreshDelegate.h"

@class NSIndexPath, NSString, TTImageView, UILabel, UIView, WFComment, WFDigButton, WFFavoriteButton, WFNativeAdInfo, WFPostButton, WFPostCommentController, WFShareButton, WFWeibo;

__attribute__((visibility("hidden")))
@interface WFCommentsController : WFTTTableController <TLThumbViewDelegate, WFNativeAdRefreshDelegate>
{
    WFWeibo *_weibo;
    NSString *_aid;
    NSString *_fid;
    int _wtype;
    int _source;
    WFComment *_repliedComment;
    _Bool _getPost;
    _Bool _getOnlyReplies;
    _Bool _fromReplyPage;
    NSString *_postUpdateTime;
    UIView *_headView;
    TTImageView *_avatarView;
    UILabel *_userLabel;
    UILabel *_bodyLabel;
    UILabel *_timeLabel;
    WFPostButton *_postButton;
    WFDigButton *_digUpButton;
    WFFavoriteButton *_favoriteButton;
    WFShareButton *_shareButton;
    WFPostCommentController *_postController;
    WFNativeAdInfo *_nativeAdInfo;
    _Bool _triedLoadingNativeAd;
    NSIndexPath *_nativeAdIndexPath;
    _Bool _needJumpAfterPost;
    _Bool _commentDisabledBeforePublish;
    _Bool _hideUpdateTime;
}

- (void).cxx_destruct;
- (void)__init;
- (void)__refreshNativeAd;
- (void)adjustFooter;
- (_Bool)canClearViews;
- (_Bool)canRestorePosition;
- (_Bool)canShowModel;
- (void)clearReplies;
@property(nonatomic) _Bool commentDisabledBeforePublish; // @synthesize commentDisabledBeforePublish=_commentDisabledBeforePublish;
- (id)commentModel;
- (void)commentPostFinish:(id)arg1;
- (id)commentsDisabledMsg;
- (_Bool)commentsEnabled;
- (void)createModel;
- (void)dealloc;
- (void)didLoadModel:(_Bool)arg1;
- (void)didNativeAdScreenFinishPresent:(id)arg1;
- (void)didShowModel:(_Bool)arg1;
- (void)didSingleTapOnImageView:(id)arg1;
- (void)digThis:(id)arg1;
- (void)enableButtons:(_Bool)arg1;
- (void)favoriteThis:(id)arg1;
- (void)goToHisPosts:(id)arg1;
@property(nonatomic) _Bool hideUpdateTime; // @synthesize hideUpdateTime=_hideUpdateTime;
- (id)imageForEmpty;
- (id)initWithAlbumID:(id)arg1 fid:(id)arg2 wtype:(int)arg3;
- (id)initWithFid:(id)arg1 wtype:(int)arg2 source:(int)arg3;
- (id)initWithFid:(id)arg1 wtype:(int)arg2 source:(int)arg3 onlyReplies:(_Bool)arg4;
- (id)initWithPostUpdateTime:(id)arg1 wtype:(int)arg2;
- (id)initWithRepliedComment:(id)arg1;
- (id)initWithWeibo:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (void)loadNativeAd:(_Bool)arg1;
- (void)logNativeAdClick;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidCancelLoad:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
- (void)nativeAdDidRefresh:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)parentViewForCommentEditor;
- (void)postComment:(id)arg1;
- (void)postWithRepliedComment:(id)arg1;
- (long long)recommendedCellCount;
- (long long)recommendedCount;
- (void)refreshNativeAd:(id)arg1;
- (_Bool)reloadButtonForEmpty;
- (void)reportComment:(id)arg1;
- (void)resignActive:(id)arg1;
- (void)restoreViewStates;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setupCommentEditor;
- (void)setupUGCViews;
- (void)shareThis:(id)arg1;
- (void)showError:(_Bool)arg1;
- (void)showOnlyReplies:(_Bool)arg1;
- (id)subtitleForEmpty;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)titleForEmpty;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willEnterForeground:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

