//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, WFDateRangePicker;

@protocol WFDateRangePickerDelegate <NSObject>
- (void)dateRangePicker:(WFDateRangePicker *)arg1 didSelectMinDate:(NSDate *)arg2 maxDate:(NSDate *)arg3;
- (void)dateRangePickerDidCancelSelection:(WFDateRangePicker *)arg1;
- (void)dateRangePickerDidClearSelection:(WFDateRangePicker *)arg1 shouldRefresh:(_Bool)arg2;
@end

