//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "TTURLRequestDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSError, NSString, UIViewController<WFDiagnosticDelegate>;

__attribute__((visibility("hidden")))
@interface WFDiagnosticManager : NSObject <UIAlertViewDelegate, TTURLRequestDelegate, MFMailComposeViewControllerDelegate>
{
    _Bool _authenticatingWiFi;
    UIViewController<WFDiagnosticDelegate> *_delegate;
    NSError *_lastError;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)alertDiagnosticBegin;
- (void)alertDiagnosticConnected;
- (void)alertDiagnosticServerBusy;
- (void)alertDiagnosticServerUnreachable;
- (void)alertDiagnosticUnauthenticatedWiFi;
- (void)alertDiagnosticUnknownRedirection;
- (void)alertReportErrorData;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)authenticateWiFi;
@property(nonatomic) _Bool authenticatingWiFi; // @synthesize authenticatingWiFi=_authenticatingWiFi;
@property(nonatomic) __weak UIViewController<WFDiagnosticDelegate> *delegate; // @synthesize delegate=_delegate;
- (id)getClientIP;
- (_Bool)isFromWifiAuthenticationForURL:(id)arg1;
@property(retain, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)openEmailEditorWithTitle:(id)arg1;
- (void)pingTestPage;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
- (void)setClientIP:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

