//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITapGestureRecognizer, UIView, WFEmojiEmitterLayer;

__attribute__((visibility("hidden")))
@interface WFEmojiEmitterManager : NSObject
{
    _Bool _isEmitting;
    WFEmojiEmitterLayer *_emitterLayer;
    UIView *_displayView;
    UITapGestureRecognizer *_tapRecognizer;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (_Bool)emitEmojisWithName:(id)arg1 onView:(id)arg2 withDuration:(double)arg3;
- (void)removeEmitter:(id)arg1;
- (void)stopEmitter;

@end

