//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAEmitterLayer.h"

__attribute__((visibility("hidden")))
@interface WFEmojiEmitterLayer : CAEmitterLayer
{
}

- (void)dealloc;
- (id)initWithEmojiImage:(id)arg1 viewSize:(struct CGSize)arg2;

@end

