//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFSlideSegmentController.h"

#import "JYSlideSegmentDelegate.h"
#import "WFDateRangePickerDelegate.h"
#import "WFFloatingSearchBarDelegate.h"

@class NSString, UIButton, WFDateRangePicker, WFFloatingSearchBar;

__attribute__((visibility("hidden")))
@interface WFFavoriteController : WFSlideSegmentController <JYSlideSegmentDelegate, WFDateRangePickerDelegate, WFFloatingSearchBarDelegate>
{
    UIButton *_calendarButton;
    UIButton *_searchButton;
    WFDateRangePicker *_datePicker;
    WFFloatingSearchBar *_searchBar;
    long long _selectedControllerIndex;
}

- (void).cxx_destruct;
- (void)dateRangePicker:(id)arg1 didSelectMinDate:(id)arg2 maxDate:(id)arg3;
- (void)dateRangePickerDidCancelSelection:(id)arg1;
- (void)dateRangePickerDidClearSelection:(id)arg1 shouldRefresh:(_Bool)arg2;
- (void)dealloc;
- (void)didFullyShowViewController:(id)arg1;
- (void)favSyncStateChanged:(id)arg1;
- (void)filterWithDates:(id)arg1;
- (id)init;
- (void)refresh:(id)arg1;
- (void)search:(id)arg1;
- (void)searchBar:(id)arg1 didSearchKeyword:(id)arg2;
- (void)searchBarDidCancelSearch:(id)arg1;
- (void)searchBarDidClearKeyword:(id)arg1 shouldRefresh:(_Bool)arg2;
- (void)slideSegmentDidTapAgain:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

