//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WFFloatingSearchBar;

@protocol WFFloatingSearchBarDelegate <NSObject>
- (void)searchBar:(WFFloatingSearchBar *)arg1 didSearchKeyword:(NSString *)arg2;
- (void)searchBarDidCancelSearch:(WFFloatingSearchBar *)arg1;
- (void)searchBarDidClearKeyword:(WFFloatingSearchBar *)arg1 shouldRefresh:(_Bool)arg2;
@end

