//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, WFHotKeyword;

__attribute__((visibility("hidden")))
@interface WFHotKeywordCell : UITableViewCell
{
    UILabel *_keywordLabel;
    UILabel *_rankingLabel;
    WFHotKeyword *_keyword;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) WFHotKeyword *keyword; // @synthesize keyword=_keyword;
@property(readonly, nonatomic) UILabel *keywordLabel; // @synthesize keywordLabel=_keywordLabel;
- (void)layoutSubviews;
@property(readonly, nonatomic) UILabel *rankingLabel; // @synthesize rankingLabel=_rankingLabel;

@end

