//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TTURLRequest, TTURLRequestModel<WFImagePreloadableModel>;

__attribute__((visibility("hidden")))
@interface WFImagePreloadManager : NSObject
{
    TTURLRequest *_request;
    _Bool _loading;
    long long _currentItemIndex;
    long long _fromItemIndex;
    long long _lastItemIndex;
    TTURLRequestModel<WFImagePreloadableModel> *_weiboModel;
    long long _imageIndexToLoad;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(nonatomic) long long imageIndexToLoad; // @synthesize imageIndexToLoad=_imageIndexToLoad;
- (id)init;
- (void)pause;
- (void)preloadNext;
- (void)reachabilityChanged:(id)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidCancelLoad:(id)arg1;
- (void)requestDidFinishLoad:(id)arg1;
- (void)reset;
- (void)resume;
@property(retain, nonatomic) TTURLRequestModel<WFImagePreloadableModel> *weiboModel; // @synthesize weiboModel=_weiboModel;
- (void)setWeiboModel:(id)arg1 forced:(_Bool)arg2;
- (_Bool)shouldBegin;
- (void)startAtWeibo:(id)arg1;
- (void)stop;

@end

