//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface WFLeftMenuView : UIView
{
    NSMutableArray *_itemViews;
    NSMutableArray *_items;
    NSString *_selectedKey;
    id <WFLeftMenuDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <WFLeftMenuDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)insertItem:(id)arg1 atIndex:(long long)arg2;
- (_Bool)itemExistsForKey:(id)arg1;
- (void)itemTapped:(id)arg1;
- (id)itemViewForKey:(id)arg1;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
- (void)layoutSubviews;
@property(retain, nonatomic) NSString *selectedKey; // @synthesize selectedKey=_selectedKey;
- (void)setSelectedKey:(id)arg1 withCallback:(_Bool)arg2;
- (void)themeChanged:(id)arg1;

@end

