//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class WFLeftMenuItem;

__attribute__((visibility("hidden")))
@interface WFLeftMenuItemView : UIButton
{
    WFLeftMenuItem *_item;
}

+ (double)minHeightForItem:(id)arg1;
- (void).cxx_destruct;
- (void)adjustTheme;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) WFLeftMenuItem *item; // @synthesize item=_item;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;

@end

