//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMNative, NSDate;

__attribute__((visibility("hidden")))
@interface WFNativeAdInfo : NSObject
{
    _Bool _isImpressed;
    _Bool _isVideo;
    IMNative *_nativeAd;
    NSDate *_requestTime;
    double _aspectRatio;
}

- (void).cxx_destruct;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (void)dealloc;
@property(nonatomic) _Bool isImpressed; // @synthesize isImpressed=_isImpressed;
@property(nonatomic) _Bool isVideo; // @synthesize isVideo=_isVideo;
@property(retain, nonatomic) IMNative *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) NSDate *requestTime; // @synthesize requestTime=_requestTime;

@end

