//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TTImageViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, TLThumbView, UIButton, UIPanGestureRecognizer, UIScrollView;

__attribute__((visibility("hidden")))
@interface WFPhotoViewer : UIView <TTImageViewDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    UIButton *_btnDown;
    UIScrollView *_scrollView;
    UIView *_backgroundView;
    TLThumbView *_photoView;
    UIView *_superview;
    struct CGRect _fromFrame;
    struct CGRect _toFrame;
    CDUnknownBlockType _willAppearBlock;
    CDUnknownBlockType _willDisappearBlock;
    UIPanGestureRecognizer *_gifScrubberGesture;
    _Bool _isGifPlayingPreviously;
}

- (void).cxx_destruct;
- (void)addPanControlToAnimatedImageView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onGifScrubbing:(id)arg1;
- (void)savePhoto:(id)arg1;
- (void)showFromView:(id)arg1 inView:(id)arg2 withPhoto:(id)arg3 onWillAppear:(CDUnknownBlockType)arg4 onWillDisappear:(CDUnknownBlockType)arg5;
- (void)tapped:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

