//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTModelViewController.h"

#import "TTScrollViewDataSource.h"
#import "TTScrollViewDelegate.h"

@class NSString, NSTimer, TTPhotoView, TTScrollView, UIBarButtonItem, UIImage, UIToolbar, UIView;

__attribute__((visibility("hidden")))
@interface WFPhotoViewController : TTModelViewController <TTScrollViewDelegate, TTScrollViewDataSource>
{
    id <TTPhoto> _centerPhoto;
    long long _centerPhotoIndex;
    UIView *_innerView;
    TTScrollView *_scrollView;
    TTPhotoView *_photoStatusView;
    UIToolbar *_toolbar;
    UIBarButtonItem *_nextButton;
    UIBarButtonItem *_previousButton;
    UIImage *_defaultImage;
    NSString *_statusText;
    NSTimer *_slideshowTimer;
    NSTimer *_loadTimer;
    _Bool _delayLoad;
    _Bool _isEmpty;
    id <TTPhotoSource> _photoSource;
    _Bool _failedLoadingPage;
}

- (_Bool)canShowModel;
- (void)cancelImageLoadTimer;
@property(retain, nonatomic) id <TTPhoto> centerPhoto; // @synthesize centerPhoto=_centerPhoto;
@property(readonly, nonatomic) long long centerPhotoIndex; // @synthesize centerPhotoIndex=_centerPhotoIndex;
- (id)centerPhotoView;
- (id)createPhotoView;
- (void)dealloc;
@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
- (void)didLoadModel:(_Bool)arg1;
- (void)didMoveToPhoto:(id)arg1 fromPhoto:(id)arg2;
- (void)didRefreshModel;
- (void)enableToolbar:(_Bool)arg1;
- (_Bool)hasPhotoLoadedForView:(id)arg1;
- (void)hideBarsAnimationDidStop;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithPhoto:(id)arg1;
- (id)initWithPhotoSource:(id)arg1;
- (_Bool)isShowingChrome;
- (void)loadImageDelayed;
- (void)loadImages;
- (void)loadView;
- (void)model:(id)arg1 didDeleteObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)model:(id)arg1 didInsertObject:(id)arg2 atIndexPath:(id)arg3;
- (void)model:(id)arg1 didUpdateObject:(id)arg2 atIndexPath:(id)arg3;
- (void)modelDidCancelLoad:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
- (void)moveToNextValidPhoto;
- (void)moveToPhoto:(id)arg1;
- (void)moveToPhotoAtIndex:(long long)arg1 withDelay:(_Bool)arg2;
- (void)nextAction;
- (long long)numberOfPagesInScrollView:(id)arg1;
- (struct CGSize)pageSize;
- (void)pauseAction;
@property(retain, nonatomic) id <TTPhotoSource> photoSource; // @synthesize photoSource=_photoSource;
- (void)playAction;
- (void)previousAction;
- (void)reloadAction;
- (void)resetVisiblePhotoViews;
- (id)rotatingFooterView;
- (void)saveAction;
- (void)scrollView:(id)arg1 didMoveToPageAtIndex:(long long)arg2;
- (id)scrollView:(id)arg1 pageAtIndex:(long long)arg2;
- (struct CGSize)scrollView:(id)arg1 sizeOfPageAtIndex:(long long)arg2;
- (void)scrollView:(id)arg1 tapped:(id)arg2;
- (void)scrollViewDidBeginZooming:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1;
- (void)scrollViewDidRotate:(id)arg1;
- (_Bool)scrollViewShouldZoom:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillRotate:(id)arg1 toOrientation:(long long)arg2;
- (void)shareAction;
- (_Bool)shouldLoad;
- (_Bool)shouldLoadMore;
- (_Bool)shouldReload;
- (void)showActivity:(id)arg1;
- (void)showBars:(_Bool)arg1 animated:(_Bool)arg2;
- (void)showBarsAnimationDidStop;
- (void)showEmpty:(_Bool)arg1;
- (void)showError:(_Bool)arg1;
- (void)showLoading:(_Bool)arg1;
- (void)showPhoto:(id)arg1 inView:(id)arg2;
- (void)showProgress:(double)arg1;
- (void)showStatus:(id)arg1;
- (void)slideshowTimer;
- (void)startImageLoadTimer:(double)arg1;
- (id)statusView;
- (void)updateChrome;
- (void)updatePhotoView;
- (void)updateToolbarWithOrientation:(long long)arg1;
- (void)updateVisiblePhotoViews;
- (void)viewDidUnload;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

