//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WFPopupMenu;

@protocol WFPopupMenuDelegate <NSObject>
- (void)popupMenu:(WFPopupMenu *)arg1 didDismissAtIndex:(long long)arg2 withKey:(NSString *)arg3;
@end

