//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WFProgressManager : NSObject
{
    NSString *_progressDir;
    NSString *_postsProgressDir;
    NSString *_albumsProgressDir;
    NSString *_hotWeibosProgressDir;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)albumsProgressDir;
- (void)clearProgress:(_Bool)arg1 isOfficial:(_Bool)arg2;
- (void)clearProgressForAlbumID:(id)arg1;
- (void)clearProgressForHotWeibos:(_Bool)arg1;
- (void)clearProgressForType:(int)arg1 clearData:(_Bool)arg2 isOfficial:(_Bool)arg3;
- (id)errorPathForType:(int)arg1 atPage:(long long)arg2;
- (id)hotWeibosProgressDir;
- (id)init;
- (long long)lastBaseTimestampForType:(int)arg1 isOfficial:(_Bool)arg2;
- (double)lastReadOffsetForHotWeibos;
- (double)lastReadOffsetForType:(int)arg1 isOfficial:(_Bool)arg2;
- (long long)lastReadPageForHotWeibos;
- (long long)lastReadPageForType:(int)arg1 isOfficial:(_Bool)arg2;
- (int)lastReadTypeForOfficial:(_Bool)arg1;
- (int)lastSourceTypeForType:(int)arg1 isOfficial:(_Bool)arg2;
- (long long)lastWeiboCountForType:(int)arg1 isOfficial:(_Bool)arg2;
- (id)pathForAlbumID:(id)arg1 atPage:(long long)arg2;
- (id)pathForHotWeibosAtPage:(long long)arg1;
- (id)pathForType:(int)arg1 atPage:(long long)arg2 isOfficial:(_Bool)arg3;
- (_Bool)saveData:(id)arg1 atPage:(long long)arg2 forAlbumID:(id)arg3;
- (_Bool)saveData:(id)arg1 atPage:(long long)arg2 forType:(int)arg3 isOfficial:(_Bool)arg4;
- (_Bool)saveErrorData:(id)arg1 atPage:(long long)arg2 forType:(int)arg3;
- (_Bool)saveHotWeibosData:(id)arg1 atPage:(long long)arg2;
- (void)setHotWeibosLastReadOffset:(double)arg1;
- (void)setLastBaseTimestamp:(long long)arg1 forType:(int)arg2 isOfficial:(_Bool)arg3;
- (void)setLastReadOffset:(double)arg1 forType:(int)arg2 isOfficial:(_Bool)arg3;
- (void)setLastReadPage:(long long)arg1 forType:(int)arg2 isOfficial:(_Bool)arg3;
- (void)setLastReadPageForHotWeibos:(long long)arg1;
- (void)setLastReadType:(int)arg1 isOfficial:(_Bool)arg2;
- (void)setLastSourceType:(int)arg1 forType:(int)arg2 isOfficial:(_Bool)arg3;
- (void)setLastWeiboCount:(unsigned long long)arg1 forType:(int)arg2 isOfficial:(_Bool)arg3;

@end

