//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface WFPrivateDialog : NSObject
{
    long long _cid;
    NSString *_lastContent;
    NSString *_senderUid;
    NSString *_senderName;
    NSString *_senderAvatar;
    NSDate *_lastSendTime;
}

+ (id)objectFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *lastContent; // @synthesize lastContent=_lastContent;
@property(retain, nonatomic) NSDate *lastSendTime; // @synthesize lastSendTime=_lastSendTime;
@property(copy, nonatomic) NSString *senderAvatar; // @synthesize senderAvatar=_senderAvatar;
@property(copy, nonatomic) NSString *senderName; // @synthesize senderName=_senderName;
@property(copy, nonatomic) NSString *senderUid; // @synthesize senderUid=_senderUid;

@end

