//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "TLImageViewDelegate.h"
#import "UITextViewDelegate.h"

@class NSDateFormatter, NSString, TLThumbView, TTImageView, UIImageView, UILabel, UITextView, WFPrivateMsg;

__attribute__((visibility("hidden")))
@interface WFPrivateMsgCell : UITableViewCell <UITextViewDelegate, TLImageViewDelegate, MFMailComposeViewControllerDelegate>
{
    UIImageView *_avatarBackView;
    UIImageView *_contentBackView;
    NSDateFormatter *_dateFormatter;
    TTImageView *_avatarView;
    TLThumbView *_imageView2;
    UITextView *_contentLabel;
    UILabel *_timeLabel;
    WFPrivateMsg *_msg;
}

+ (id)attributedStringForContent:(id)arg1;
+ (double)heightForMsg:(id)arg1;
+ (struct CGSize)sizeForContent:(id)arg1 inWidth:(double)arg2;
+ (double)viewWidth;
- (void).cxx_destruct;
@property(readonly, nonatomic) TTImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(readonly, nonatomic) UITextView *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void)dealloc;
- (void)didMoveToSuperview;
@property(readonly, nonatomic) TLThumbView *imageView2; // @synthesize imageView2=_imageView2;
- (void)imageView:(id)arg1 willSendARequest:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
@property(retain, nonatomic) WFPrivateMsg *msg; // @synthesize msg=_msg;
- (void)prepareForReuse;
- (void)setContent:(id)arg1;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3;
@property(readonly, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

