//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WFPushNotificationManager : NSObject
{
    int _jumpMode;
    long long _pid;
    int _wtype;
    NSString *_jid;
    int _postSource;
    NSString *_publicMsgTitle;
    NSString *_publicMsgURL;
    NSString *_newAlbumID;
    NSString *_privateMsgUsername;
    NSString *_badgeType;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(nonatomic) _Bool commentReplyPushEnabled;
@property(copy, nonatomic) NSString *deviceToken;
- (void)doJump;
@property(readonly, nonatomic) int jumpMode; // @synthesize jumpMode=_jumpMode;
- (_Bool)parseData:(id)arg1;
- (void)presentController:(id)arg1 fromController:(id)arg2;
@property(nonatomic) _Bool pushEnabled;
- (void)reset;
- (void)saveUsageReportTime;
- (_Bool)shouldReportUsage;

@end

