//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBaseViewController.h"

#import "WFLeftMenuDelegate.h"

@class NSString, UINavigationController, WFInfoPanel, WFLeftMenuView, WFWeiboController;

__attribute__((visibility("hidden")))
@interface WFRootControllerPad : WFBaseViewController <WFLeftMenuDelegate>
{
    WFInfoPanel *_infoPanel;
    WFLeftMenuView *_leftMenu;
    WFWeiboController *_weiboController;
    UINavigationController *_rightController;
}

- (void).cxx_destruct;
- (id)getGirlsMenuItem;
- (id)getMenuItemKeyByType:(int)arg1;
- (id)getUGCMenuItem;
- (id)getWeiboControllerWithSelectedType:(int)arg1 menuKey:(id *)arg2;
- (int)getWeiboTypeByMenuItemKey:(id)arg1;
- (void)girlsVisibilityChanged:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)isOfficialForSourceType:(int)arg1;
@property(retain, nonatomic) WFLeftMenuView *leftMenu; // @synthesize leftMenu=_leftMenu;
- (void)leftMenu:(id)arg1 didSelectItem:(id)arg2;
- (void)newAlbumsUpdated:(id)arg1;
@property(retain, nonatomic) UINavigationController *rightController; // @synthesize rightController=_rightController;
@property(retain, nonatomic) WFWeiboController *weiboController; // @synthesize weiboController=_weiboController;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showTopMsg;
- (unsigned long long)supportedInterfaceOrientations;
- (void)ugcVisibilityChanged:(id)arg1;
- (void)unreadMsgUpdated:(id)arg1;
- (void)updateAlbumBadgeNumber;
- (void)updateBadgeNumber:(long long)arg1 forMenuKey:(id)arg2;
- (void)updateMsgBadgeNumber;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

