//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFUITableController.h"

#import "QLServerURLEditor.h"
#import "TLListSelectorDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WFSwitchCellDelegate.h"

@class NSArray, NSMutableArray, NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface WFSettingsController : WFUITableController <TLListSelectorDelegate, UIActionSheetDelegate, QLServerURLEditor, WFSwitchCellDelegate, UIAlertViewDelegate>
{
    NSMutableArray *settingTitles;
    NSMutableArray *sectionTitles;
    NSArray *picResolutions;
    NSArray *picSizes;
    NSArray *wordSearchSites;
    int debugGesture;
    NSTimer *timerGesture;
    _Bool isClearingCache;
    _Bool isConfiguringPushSettings;
    long long pushAuthStatus;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)adjustTheme;
- (void)appendDebugOptions;
- (_Bool)canBecomeFirstResponder;
- (void)clearCacheInBackground;
- (void)dealloc;
- (void)gestureTimedOut:(id)arg1;
- (id)init;
- (id)magicValueForEditor:(id)arg1;
- (void)motionEnded:(long long)arg1 withEvent:(id)arg2;
- (long long)numberOfSectionsInSelector:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshAppPlatformCell:(id)arg1;
- (void)refreshClearCacheCell:(id)arg1;
- (void)refreshCmtReplyCell:(id)arg1;
- (void)refreshFeedbackCell:(id)arg1;
- (void)refreshFontSizeCell:(id)arg1;
- (void)refreshGameCenterCell:(id)arg1;
- (void)refreshPicSizeCell:(id)arg1;
- (void)refreshPlayerCoreCell:(id)arg1;
- (void)refreshPrivateMsgCell:(id)arg1;
- (void)refreshPubMsgCell:(id)arg1;
- (void)refreshWordSearchCell:(id)arg1;
- (void)requestRestoreValue:(id)arg1;
- (void)saveValueForEditor:(id)arg1;
- (void)selector:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)selector:(id)arg1 didUnselectRowAtIndexPath:(id)arg2;
- (long long)selector:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)selector:(id)arg1 shouldSelectRowAtIndexPath:(id)arg2;
- (id)selector:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)selector:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)selector:(id)arg1 titleForRowAtIndexPath:(id)arg2;
- (void)swiped:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableViewCell:(id)arg1 switchValueChanged:(id)arg2;
- (id)titleForEditor:(id)arg1;
- (id)valueForEditor:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

