//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBaseViewController.h"

#import "UIAlertViewDelegate.h"

@class MBProgressHUD, NSString, SSDKUser;

__attribute__((visibility("hidden")))
@interface WFSNSLoginController : WFBaseViewController <UIAlertViewDelegate>
{
    MBProgressHUD *_hud;
    unsigned long long _snsType;
    SSDKUser *_userInfo;
    NSString *_userName;
    NSString *_accessToken;
    NSString *_platformUid;
    id _userData;
}

- (void).cxx_destruct;
- (void)alertRegFailWithMsg:(id)arg1;
- (void)alertRegSuccessWithMsg:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)connect:(id)arg1;
- (void)dealloc;
- (void)hideHUD;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithUserData:(id)arg1;
- (void)loadView;
- (void)onGetUserInfo:(id)arg1;
- (void)quit;
- (void)registerUser:(_Bool)arg1;
- (void)request:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)requestDidFinishLoad:(id)arg1;
- (void)showUserNameDialogWithTitle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

