//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class NSTimer, UILabel;

__attribute__((visibility("hidden")))
@interface WFStatWindow : UIWindow
{
    NSTimer *_statTimer;
    UILabel *_memoryUsageLabel;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) UILabel *memoryUsageLabel; // @synthesize memoryUsageLabel=_memoryUsageLabel;
- (void)refresh:(id)arg1;
- (void)start;

@end

