//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface WFSysMsg : NSObject
{
    int _type;
    NSString *_mid;
    NSString *_title;
    NSString *_body;
    NSDate *_updateTime;
}

+ (id)objectFromData:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSDate *updateTime; // @synthesize updateTime=_updateTime;

@end

