//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTTableViewController.h"

@class TTTableFooterDragRefreshView, TTTableHeaderDragRefreshView;

__attribute__((visibility("hidden")))
@interface WFTTTableController : TTTableViewController
{
    TTTableHeaderDragRefreshView *_headerView;
    TTTableFooterDragRefreshView *_footerView;
    int _loadingStatus;
    _Bool _shouldRestorePosition;
    _Bool _shouldRestoreViews;
    double _lastContentOffsetY;
}

- (void).cxx_destruct;
- (_Bool)canClearViews;
- (_Bool)canRestorePosition;
- (void)clearMemory;
- (void)didReceiveMemoryWarning;
- (void)didShowModel:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)restoreViewStates;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

@end

