//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

__attribute__((visibility("hidden")))
@interface WFURLProtocol : NSURLProtocol
{
}

+ (_Bool)canInitWithRequest:(id)arg1;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (void)setHijackRegex:(id)arg1 headerKeys:(id)arg2 forSourceURL:(id)arg3;
- (void)dealloc;
- (void)startLoading;
- (void)stopLoading;

@end

