//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WFPhotoData.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface WFUserPost : NSObject <WFPhotoData>
{
    _Bool _isGIF;
    _Bool _isApproved;
    int _wtype;
    NSString *_pid;
    NSString *_fid;
    NSString *_body;
    NSDate *_createTime;
    NSString *_picURL;
    double _picWidth;
    double _picHeight;
    NSString *_sourceURL;
    NSString *_reviewState;
    NSString *_reviewMemo;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(retain, nonatomic) NSDate *createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *fid; // @synthesize fid=_fid;
@property(nonatomic) _Bool isApproved; // @synthesize isApproved=_isApproved;
@property(nonatomic) _Bool isGIF; // @synthesize isGIF=_isGIF;
@property(nonatomic) double picHeight; // @synthesize picHeight=_picHeight;
@property(copy, nonatomic) NSString *picURL; // @synthesize picURL=_picURL;
@property(nonatomic) double picWidth; // @synthesize picWidth=_picWidth;
@property(copy, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(copy, nonatomic) NSString *reviewMemo; // @synthesize reviewMemo=_reviewMemo;
@property(copy, nonatomic) NSString *reviewState; // @synthesize reviewState=_reviewState;
@property(copy, nonatomic) NSString *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(nonatomic) int wtype; // @synthesize wtype=_wtype;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

