//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TTImageView;

__attribute__((visibility("hidden")))
@interface WFUserLoginCell : UITableViewCell
{
    TTImageView *_avatarView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TTImageView *avatarView; // @synthesize avatarView=_avatarView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end

