//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFBaseViewController.h"

#import "BBPlayerControllerDelegate.h"
#import "UIWebViewDelegate.h"

@class BBPlayerViewController, NSString, NSTimer, UIButton, UIWebView, WFComment, WFCommentsController, WFVideo, WFVideoURLFetcher;

__attribute__((visibility("hidden")))
@interface WFVideoController3 : WFBaseViewController <BBPlayerControllerDelegate, UIWebViewDelegate>
{
    BBPlayerViewController *_playerController;
    WFCommentsController *_commentsController;
    UIButton *_btnReturn;
    UIButton *_btnClose;
    WFVideo *_video;
    NSString *_fid;
    int _source;
    WFComment *_repliedComment;
    _Bool _getOnlyReplies;
    NSString *_postUpdateTime;
    NSTimer *_loadTimer;
    WFVideoURLFetcher *_videoFetcher;
    UIWebView *_hiddenWebView;
    _Bool _useLuaAfterHijack;
    NSString *_webViewHijackedURL;
    NSString *_webViewHijackedPreJS;
    _Bool _agreedToPlayOnCellular;
    _Bool _alertingPlayOnCellular;
    _Bool _alertingPlaybackError;
    _Bool _shouldHideAd;
    _Bool _commentDisabledBeforePublish;
    _Bool _hideUpdateTime;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)__init;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)canPlayOnCellularNetwork:(id)arg1;
- (void)clearWebViewHijack;
@property(nonatomic) _Bool commentDisabledBeforePublish; // @synthesize commentDisabledBeforePublish=_commentDisabledBeforePublish;
- (void)commentsLoaded:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
@property(nonatomic) _Bool hideUpdateTime; // @synthesize hideUpdateTime=_hideUpdateTime;
- (void)initViews;
- (id)initWithFid:(id)arg1 source:(int)arg2;
- (id)initWithFid:(id)arg1 source:(int)arg2 onlyReplies:(_Bool)arg3;
- (id)initWithPostUpdateTime:(id)arg1;
- (id)initWithRepliedComment:(id)arg1;
- (id)initWithVideo:(id)arg1;
- (void)loadTimedOut:(id)arg1;
- (void)loadView;
- (void)openVideoInWebpage;
- (void)pause;
- (void)play;
- (void)player:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)player:(id)arg1 didSwitchToFullscreen:(_Bool)arg2;
- (void)player:(id)arg1 didSwitchToWindow:(_Bool)arg2;
- (void)playerDidBecomeReadyToPlay:(id)arg1;
- (_Bool)playerDidClickPlay:(id)arg1;
- (void)playerDidPlayToEnd:(id)arg1;
- (void)playerDidStartWaitingForContentURL:(id)arg1;
- (void)playerDidSwitchToCellularNetwork:(id)arg1;
- (void)popBack:(id)arg1;
- (void)popToRoot:(id)arg1;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)reportVideoLoadError:(id)arg1;
- (void)seekTo:(double)arg1;
@property(nonatomic) _Bool shouldHideAd; // @synthesize shouldHideAd=_shouldHideAd;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldFetchContentURLDynamically:(id)arg1;
- (void)startLoadTimer;
- (void)startPlaying;
- (void)stopPlayer;
- (unsigned long long)supportedInterfaceOrientations;
- (void)videoURLFetchDidCompleteWithPlayURL:(id)arg1 sourceURL:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewHijackDidFail;
- (void)webViewHijackDidSucceed:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

