//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface WFVideoURLFetcher : NSOperation
{
    NSString *_siteCode;
    NSString *_videoID;
    NSString *_sourceURL;
    NSString *_hijackedURL;
    NSString *_hijackedHeaders;
    CDUnknownBlockType _completionBlock;
    NSString *_playURL;
}

+ (void)downloadScriptForSite:(id)arg1;
+ (void)initCommonScripts;
+ (id)scriptPathForSite:(id)arg1;
+ (id)scriptsDirectory;
+ (id)siteCodeForSourceURL:(id)arg1;
+ (id)syncGetBodyForURL:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)fetchURL;
- (id)initWithSiteCode:(id)arg1 hijackedURL:(id)arg2 sourceURL:(id)arg3 hijackedHeaders:(id)arg4 onCompletion:(CDUnknownBlockType)arg5;
- (id)initWithSiteCode:(id)arg1 videoID:(id)arg2 sourceURL:(id)arg3 onCompletion:(CDUnknownBlockType)arg4;
- (void)main;

@end

