//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TTImageViewDelegate.h"

@class NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface WFVideoCellPad : UITableViewCell <TTImageViewDelegate>
{
    long long _columnCount;
    NSMutableArray *_thumbViews;
    NSArray *_videos;
}

- (void).cxx_destruct;
- (void)clearCell;
- (void)dealloc;
- (id)initWithColumnCount:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)playVideo:(id)arg1;
- (void)prepareForReuse;
@property(retain, nonatomic) NSArray *videos; // @synthesize videos=_videos;
@property(readonly, nonatomic) NSArray *thumbViews; // @synthesize thumbViews=_thumbViews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

