//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFTTTableController.h"

#import "LSBannerAdManagerDelegate.h"
#import "MBProgressHUDDelegate.h"
#import "TLThumbViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WFDatePickerDelegate.h"
#import "WFDiagnosticDelegate.h"
#import "WFPopupMenuDelegate.h"

@class MBProgressHUD, NSString, WFAlbum, WFAlbumHeaderView;

__attribute__((visibility("hidden")))
@interface WFWeiboController : WFTTTableController <TLThumbViewDelegate, UIAlertViewDelegate, WFPopupMenuDelegate, WFDatePickerDelegate, LSBannerAdManagerDelegate, WFDiagnosticDelegate, MBProgressHUDDelegate>
{
    int _weiboType;
    int _sourceType;
    long long _baseTimestamp;
    WFAlbum *_album;
    NSString *_aid;
    _Bool _getAlbum;
    WFAlbumHeaderView *_albumHeaderView;
    MBProgressHUD *_dbUpgradeHUD;
    _Bool shouldReloadData;
    _Bool _canLoadFromProgress;
    _Bool _showSearchBar;
    _Bool _refreshingManually;
    _Bool _shouldHideAd;
    _Bool _shouldReloadAfterFavSync;
}

- (void).cxx_destruct;
- (void)__init;
- (void)adjustHeaderFooter;
- (void)adjustViewColors;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)canClearViews;
- (_Bool)canRefresh;
- (_Bool)canShowHeaderView;
- (void)categorySyncFinished:(id)arg1;
- (Class)cellClassForWeibo:(id)arg1;
- (id)cellIdentifierForWeibo:(id)arg1;
- (void)clearMemoryForType:(int)arg1;
- (void)createModel;
- (void)datePicker:(id)arg1 didSelectDate:(id)arg2;
- (void)dealloc;
- (void)diagnosticDidFinish;
- (void)diagnosticWillBegin;
- (void)didLoadModel:(_Bool)arg1;
- (void)didShowModel:(_Bool)arg1;
- (void)didSingleTapOnImageView:(id)arg1;
- (void)enterBackground:(id)arg1;
- (void)getMoney;
- (void)hudWasHidden:(id)arg1;
- (id)imageForEmpty;
- (id)initWithAlbum:(id)arg1;
- (id)initWithType:(int)arg1 albumID:(id)arg2;
- (id)initWithType:(int)arg1 albumID:(id)arg2 isLong:(_Bool)arg3;
- (id)initWithType:(int)arg1 sourceType:(int)arg2;
- (_Bool)isFavorites;
- (_Bool)isHomePage;
- (_Bool)isOfficial;
- (_Bool)isRandom;
- (_Bool)isUGC;
- (id)itemAtIndexPath:(id)arg1;
- (void)loadLatest:(_Bool)arg1;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidCancelLoad:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openPhotoController:(id)arg1;
- (long long)pageIndexToReport;
- (void)popupMenu:(id)arg1 didDismissAtIndex:(long long)arg2 withKey:(id)arg3;
- (void)refreshByDate;
- (void)refreshLatest;
- (void)refreshRandom;
- (void)refreshRandomFromHeader:(_Bool)arg1;
- (_Bool)reloadButtonForEmpty;
- (void)reloadTableView:(id)arg1;
- (void)reloadViews;
- (void)restoreViewStates;
- (void)retry;
- (void)saveReadProgress;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) _Bool shouldHideAd; // @synthesize shouldHideAd=_shouldHideAd;
@property(nonatomic) _Bool shouldReloadAfterFavSync; // @synthesize shouldReloadAfterFavSync=_shouldReloadAfterFavSync;
- (void)setWeiboType:(int)arg1 isUGC:(_Bool)arg2;
- (_Bool)shouldReload;
- (_Bool)shouldSaveProgress;
- (void)showPopupMenu:(id)arg1;
@property(readonly, nonatomic) int sourceType; // @synthesize sourceType=_sourceType;
- (id)subtitleForEmpty;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (struct UIEdgeInsets)tableViewInsets;
- (id)titleForEmpty;
- (id)titleForLoading:(_Bool)arg1;
- (void)upgradeDatabase;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)weiboModel;
@property(readonly, nonatomic) int weiboType; // @synthesize weiboType=_weiboType;
- (int)weiboTypeToReport;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

