//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WFTTTableController.h"

#import "LSBannerAdManagerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, TLTextField;

__attribute__((visibility("hidden")))
@interface WFWeiboSearchController : WFTTTableController <UITextFieldDelegate, LSBannerAdManagerDelegate>
{
    int _weiboType;
    _Bool _fromHot;
    TLTextField *_tfKeyword;
    _Bool _shouldHideAd;
}

- (void).cxx_destruct;
- (void)adjustFooter;
- (void)adjustViewColors;
- (_Bool)canClearViews;
- (_Bool)canSearch;
- (void)cancelSearch:(id)arg1;
- (void)createModel;
- (void)dealloc;
- (void)didShowModel:(_Bool)arg1;
- (void)getMoney;
- (id)imageForEmpty;
- (id)initWithType:(int)arg1;
- (void)model:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)modelDidCancelLoad:(id)arg1;
- (void)modelDidFinishLoad:(id)arg1;
- (void)modelDidStartLoad:(id)arg1;
- (_Bool)reloadButtonForEmpty;
- (void)restoreViewStates;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)searchKeyword;
- (id)searchModel;
@property(nonatomic) _Bool shouldHideAd; // @synthesize shouldHideAd=_shouldHideAd;
- (_Bool)shouldReload;
- (id)subtitleForEmpty;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (struct UIEdgeInsets)tableViewInsets;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)titleForEmpty;
- (id)titleForLoading:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

