//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WXOMTAGCDAsyncSocketDelegate.h"

@class NSData, NSMutableArray, NSMutableData, NSString, WXOMTAGCDAsyncSocket;

@interface WXOMTASocket : NSObject <WXOMTAGCDAsyncSocketDelegate>
{
    struct dispatch_queue_s *task_queue;
    NSMutableData *readBuf;
    _Bool readHeaderComplete;
    _Bool readComplete;
    WXOMTAGCDAsyncSocket *mtaSocket;
    _Bool isConnecting;
    _Bool isSending;
    NSData *magic;
    NSData *ver;
    NSData *config;
    long long bodyLen;
    NSMutableArray *jsonEventsQueue;
    NSMutableArray *sendCallbackQueue;
    id _jsonEvents;
    CDUnknownBlockType _sendCallback;
}

+ (id)getInstance;
- (void).cxx_destruct;
- (void)closeBuffer;
- (id)filterBodyData:(id)arg1 configData:(id)arg2;
- (id)getSendData:(id)arg1;
- (void)handleBodyResult:(id)arg1 configData:(id)arg2;
- (void)handleSendError;
- (id)init;
- (void)initConfig;
- (void)initMagic;
- (void)initVer;
- (_Bool)isEqualToMagic:(id)arg1;
@property(retain, nonatomic) id jsonEvents; // @synthesize jsonEvents=_jsonEvents;
- (void)send:(id)arg1 callback:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) CDUnknownBlockType sendCallback; // @synthesize sendCallback=_sendCallback;
- (void)sendData;
- (void)sendEvent:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;
- (double)socket:(id)arg1 shouldTimeoutReadWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (double)socket:(id)arg1 shouldTimeoutWriteWithTag:(long long)arg2 elapsed:(double)arg3 bytesDone:(unsigned long long)arg4;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)startSocket:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)tcpRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

