//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WXOMTAEnv, WXOMTAUser;

@interface WXOMTAHelper : NSObject
{
    WXOMTAEnv *env;
    WXOMTAUser *user;
    _Bool _MTAEnableFlag;
    _Bool _autoTM;
    _Bool _reportNewCrashReport;
}

+ (void)ChiperRC4:(id)arg1;
+ (int)GUnzip:(id)arg1 Out:(id *)arg2;
+ (int)GZip:(id)arg1 Out:(id *)arg2;
+ (id)getCTTelephonyNetworkInfo;
+ (id)getInstance;
+ (id)getMacAddress;
+ (_Bool)isWiFiAvailable;
+ (id)md5encrypt:(id)arg1;
- (void).cxx_destruct;
@property _Bool MTAEnableFlag; // @synthesize MTAEnableFlag=_MTAEnableFlag;
@property _Bool autoTM; // @synthesize autoTM=_autoTM;
- (_Bool)checkMTAEnable;
- (id)fetchSSIDInfo;
- (id)getEnv;
- (id)getJson:(id)arg1;
- (id)getNetworkType;
- (id)getUser;
- (id)init;
@property _Bool reportNewCrashReport; // @synthesize reportNewCrashReport=_reportNewCrashReport;

@end

