//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface YYImageEncoder : NSObject
{
    NSMutableArray *_images;
    NSMutableArray *_durations;
    _Bool _lossless;
    unsigned long long _type;
    unsigned long long _loopCount;
    double _quality;
}

+ (id)encodeImage:(id)arg1 type:(unsigned long long)arg2 quality:(double)arg3;
+ (id)encodeImageWithDecoder:(id)arg1 type:(unsigned long long)arg2 quality:(double)arg3;
- (void).cxx_destruct;
- (id)_encodeAPNG;
- (void)_encodeImageWithDestination:(struct CGImageDestination *)arg1 imageCount:(unsigned long long)arg2;
- (id)_encodeWebP;
- (id)_encodeWithImageIO;
- (_Bool)_encodeWithImageIO:(id)arg1;
- (_Bool)_imageIOAvaliable;
- (struct CGImage *)_newCGImageFromIndex:(unsigned long long)arg1 decoded:(_Bool)arg2;
- (struct CGImageDestination *)_newImageDestination:(id)arg1 imageCount:(unsigned long long)arg2;
- (void)addImage:(id)arg1 duration:(double)arg2;
- (void)addImageWithData:(id)arg1 duration:(double)arg2;
- (void)addImageWithFile:(id)arg1 duration:(double)arg2;
- (id)encode;
- (_Bool)encodeToFile:(id)arg1;
- (id)init;
- (id)initWithType:(unsigned long long)arg1;
@property(nonatomic) unsigned long long loopCount; // @synthesize loopCount=_loopCount;
@property(nonatomic) _Bool lossless; // @synthesize lossless=_lossless;
@property(nonatomic) double quality; // @synthesize quality=_quality;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;

@end

